// Generated by gencpp from file itri_msgs/BehaviorState.msg
// DO NOT EDIT!


#ifndef ITRI_MSGS_MESSAGE_BEHAVIORSTATE_H
#define ITRI_MSGS_MESSAGE_BEHAVIORSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace itri_msgs
{
template <class ContainerAllocator>
struct BehaviorState_
{
  typedef BehaviorState_<ContainerAllocator> Type;

  BehaviorState_()
    : behavior_state(0)
    , behavior_stete_string()
    , obj_id(0)
    , obstacles(false)
    , avoidance(false)  {
    }
  BehaviorState_(const ContainerAllocator& _alloc)
    : behavior_state(0)
    , behavior_stete_string(_alloc)
    , obj_id(0)
    , obstacles(false)
    , avoidance(false)  {
  (void)_alloc;
    }



   typedef int32_t _behavior_state_type;
  _behavior_state_type behavior_state;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _behavior_stete_string_type;
  _behavior_stete_string_type behavior_stete_string;

   typedef int32_t _obj_id_type;
  _obj_id_type obj_id;

   typedef uint8_t _obstacles_type;
  _obstacles_type obstacles;

   typedef uint8_t _avoidance_type;
  _avoidance_type avoidance;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(INITIAL)
  #undef INITIAL
#endif
#if defined(_WIN32) && defined(AEB)
  #undef AEB
#endif
#if defined(_WIN32) && defined(LANE_FOLLOW)
  #undef LANE_FOLLOW
#endif
#if defined(_WIN32) && defined(LANE_CHANGE)
  #undef LANE_CHANGE
#endif
#if defined(_WIN32) && defined(AVOIDANCE)
  #undef AVOIDANCE
#endif
#if defined(_WIN32) && defined(STOP)
  #undef STOP
#endif
#if defined(_WIN32) && defined(PARKING)
  #undef PARKING
#endif
#if defined(_WIN32) && defined(EMERGENCY)
  #undef EMERGENCY
#endif
#if defined(_WIN32) && defined(FINISH)
  #undef FINISH
#endif
#if defined(_WIN32) && defined(ACC)
  #undef ACC
#endif
#if defined(_WIN32) && defined(BUMP)
  #undef BUMP
#endif
#if defined(_WIN32) && defined(INTERSECTION)
  #undef INTERSECTION
#endif
#if defined(_WIN32) && defined(TRAFFIC_LIGHT_RED)
  #undef TRAFFIC_LIGHT_RED
#endif
#if defined(_WIN32) && defined(TRAFFIC_LIGHT_WAIT_FOR_TURN_LEFT)
  #undef TRAFFIC_LIGHT_WAIT_FOR_TURN_LEFT
#endif
#if defined(_WIN32) && defined(TRAFFIC_LIGHT_WAIT_FOR_TURN_RIGHT)
  #undef TRAFFIC_LIGHT_WAIT_FOR_TURN_RIGHT
#endif
#if defined(_WIN32) && defined(CURVE)
  #undef CURVE
#endif
#if defined(_WIN32) && defined(SPEEDUP)
  #undef SPEEDUP
#endif
#if defined(_WIN32) && defined(DestinationWaypoints)
  #undef DestinationWaypoints
#endif
#if defined(_WIN32) && defined(DestinationGlobalPath)
  #undef DestinationGlobalPath
#endif

  enum {
    INITIAL = 0u,
    AEB = 1u,
    LANE_FOLLOW = 2u,
    LANE_CHANGE = 3u,
    AVOIDANCE = 4u,
    STOP = 5u,
    PARKING = 6u,
    EMERGENCY = 7u,
    FINISH = 8u,
    ACC = 9u,
    BUMP = 10u,
    INTERSECTION = 11u,
    TRAFFIC_LIGHT_RED = 12u,
    TRAFFIC_LIGHT_WAIT_FOR_TURN_LEFT = 13u,
    TRAFFIC_LIGHT_WAIT_FOR_TURN_RIGHT = 14u,
    CURVE = 15u,
    SPEEDUP = 16u,
    DestinationWaypoints = 17u,
    DestinationGlobalPath = 18u,
  };


  typedef boost::shared_ptr< ::itri_msgs::BehaviorState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::itri_msgs::BehaviorState_<ContainerAllocator> const> ConstPtr;

}; // struct BehaviorState_

typedef ::itri_msgs::BehaviorState_<std::allocator<void> > BehaviorState;

typedef boost::shared_ptr< ::itri_msgs::BehaviorState > BehaviorStatePtr;
typedef boost::shared_ptr< ::itri_msgs::BehaviorState const> BehaviorStateConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::itri_msgs::BehaviorState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::itri_msgs::BehaviorState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::itri_msgs::BehaviorState_<ContainerAllocator1> & lhs, const ::itri_msgs::BehaviorState_<ContainerAllocator2> & rhs)
{
  return lhs.behavior_state == rhs.behavior_state &&
    lhs.behavior_stete_string == rhs.behavior_stete_string &&
    lhs.obj_id == rhs.obj_id &&
    lhs.obstacles == rhs.obstacles &&
    lhs.avoidance == rhs.avoidance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::itri_msgs::BehaviorState_<ContainerAllocator1> & lhs, const ::itri_msgs::BehaviorState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace itri_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::itri_msgs::BehaviorState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::itri_msgs::BehaviorState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::itri_msgs::BehaviorState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::itri_msgs::BehaviorState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::itri_msgs::BehaviorState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::itri_msgs::BehaviorState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::itri_msgs::BehaviorState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b7ef9dd36a2ceb7fe32edd273643bca2";
  }

  static const char* value(const ::itri_msgs::BehaviorState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb7ef9dd36a2ceb7fULL;
  static const uint64_t static_value2 = 0xe32edd273643bca2ULL;
};

template<class ContainerAllocator>
struct DataType< ::itri_msgs::BehaviorState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "itri_msgs/BehaviorState";
  }

  static const char* value(const ::itri_msgs::BehaviorState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::itri_msgs::BehaviorState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 behavior_state\n"
"string behavior_stete_string\n"
"\n"
"uint8 INITIAL = 0\n"
"uint8 AEB = 1\n"
"uint8 LANE_FOLLOW = 2\n"
"uint8 LANE_CHANGE = 3\n"
"uint8 AVOIDANCE = 4\n"
"uint8 STOP = 5\n"
"uint8 PARKING = 6\n"
"uint8 EMERGENCY = 7\n"
"uint8 FINISH = 8\n"
"uint8 ACC = 9\n"
"uint8 BUMP = 10\n"
"uint8 INTERSECTION = 11\n"
"uint8 TRAFFIC_LIGHT_RED = 12\n"
"uint8 TRAFFIC_LIGHT_WAIT_FOR_TURN_LEFT = 13\n"
"uint8 TRAFFIC_LIGHT_WAIT_FOR_TURN_RIGHT = 14\n"
"uint8 CURVE = 15\n"
"uint8 SPEEDUP = 16\n"
"uint8 DestinationWaypoints = 17\n"
"uint8 DestinationGlobalPath = 18\n"
"\n"
"\n"
"int32 obj_id\n"
"bool obstacles\n"
"bool avoidance\n"
;
  }

  static const char* value(const ::itri_msgs::BehaviorState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::itri_msgs::BehaviorState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.behavior_state);
      stream.next(m.behavior_stete_string);
      stream.next(m.obj_id);
      stream.next(m.obstacles);
      stream.next(m.avoidance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BehaviorState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::itri_msgs::BehaviorState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::itri_msgs::BehaviorState_<ContainerAllocator>& v)
  {
    s << indent << "behavior_state: ";
    Printer<int32_t>::stream(s, indent + "  ", v.behavior_state);
    s << indent << "behavior_stete_string: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.behavior_stete_string);
    s << indent << "obj_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.obj_id);
    s << indent << "obstacles: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.obstacles);
    s << indent << "avoidance: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.avoidance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ITRI_MSGS_MESSAGE_BEHAVIORSTATE_H
