// Generated by gencpp from file itri_msgs/lane_waypoints_info.msg
// DO NOT EDIT!


#ifndef ITRI_MSGS_MESSAGE_LANE_WAYPOINTS_INFO_H
#define ITRI_MSGS_MESSAGE_LANE_WAYPOINTS_INFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <itri_msgs/lane_info.h>

namespace itri_msgs
{
template <class ContainerAllocator>
struct lane_waypoints_info_
{
  typedef lane_waypoints_info_<ContainerAllocator> Type;

  lane_waypoints_info_()
    : header()
    , point()  {
    }
  lane_waypoints_info_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , point(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::itri_msgs::lane_info_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::itri_msgs::lane_info_<ContainerAllocator> >::other >  _point_type;
  _point_type point;





  typedef boost::shared_ptr< ::itri_msgs::lane_waypoints_info_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::itri_msgs::lane_waypoints_info_<ContainerAllocator> const> ConstPtr;

}; // struct lane_waypoints_info_

typedef ::itri_msgs::lane_waypoints_info_<std::allocator<void> > lane_waypoints_info;

typedef boost::shared_ptr< ::itri_msgs::lane_waypoints_info > lane_waypoints_infoPtr;
typedef boost::shared_ptr< ::itri_msgs::lane_waypoints_info const> lane_waypoints_infoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::itri_msgs::lane_waypoints_info_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::itri_msgs::lane_waypoints_info_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::itri_msgs::lane_waypoints_info_<ContainerAllocator1> & lhs, const ::itri_msgs::lane_waypoints_info_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.point == rhs.point;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::itri_msgs::lane_waypoints_info_<ContainerAllocator1> & lhs, const ::itri_msgs::lane_waypoints_info_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace itri_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::itri_msgs::lane_waypoints_info_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::itri_msgs::lane_waypoints_info_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::itri_msgs::lane_waypoints_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::itri_msgs::lane_waypoints_info_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::itri_msgs::lane_waypoints_info_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::itri_msgs::lane_waypoints_info_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::itri_msgs::lane_waypoints_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "01267141f4f69eaeb661c3d3af07f166";
  }

  static const char* value(const ::itri_msgs::lane_waypoints_info_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x01267141f4f69eaeULL;
  static const uint64_t static_value2 = 0xb661c3d3af07f166ULL;
};

template<class ContainerAllocator>
struct DataType< ::itri_msgs::lane_waypoints_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "itri_msgs/lane_waypoints_info";
  }

  static const char* value(const ::itri_msgs::lane_waypoints_info_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::itri_msgs::lane_waypoints_info_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"lane_info[] point\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: itri_msgs/lane_info\n"
"Header header\n"
"int32 lane_id   #current lane\n"
"int32 lane_num  #total number of lane\n"
"float32 lane_width\n"
"\n"
"string[] line_pos\n"
"\n"
"# Right = 'R'\n"
"# Left  = 'L'\n"
"# Front = 'F'\n"
"\n"
"uint32[] line_type\n"
"\n"
"# EMPTY = 0\n"
"# WHITE_DASHED_LINE = 1\n"
"# WHITE_SOLID_LINE = 2\n"
"# WHITE_DOUBLE_LINE = 3\n"
"# YELLOW_DASHED_LINE\n"
"# YELLOW_SOLID_LINE\n"
"# YELLOW_DOUBLE_LINE\n"
"# RED_SOLID_LINE\n"
"# STRAIGHT_ARROW\n"
"# TURN_LEFT_ARROW\n"
"# TURN_RIGHT_ARROW\n"
"# STRAIGHT_OR_RIGHT_ARROW\n"
"# STRAIGHT_OR_LEFT_ARROW\n"
"# TURN_RIGHT_ONLY\n"
"# STOP_LINE\n"
"# LONGER_BUMP\n"
"# SHORTER_BUMP\n"
"# SLOWDOWN\n"
"# YIELD\n"
"# STOP_SIGN\n"
"# SPEED_LIMIT_20KPH\n"
"# SPEED_LIMIT_30KPH\n"
"# SPEED_LIMIT_50KPH\n"
"# SCOOTER_PARKING_PLACE\n"
"# PARKING_SPACE\n"
"\n"
"float64 front_line_dis\n"
"\n"
"bool[] on_route_hint\n"
"int32[] traffic_stop_line\n"
"int32[] bumper\n"
"int32[] start_right_turn\n"
"int32[] end_right_turn\n"
"int32[] start_left_turn\n"
"int32[] end_left_turn\n"
"\n"
"Waypoint front_marker_point\n"
"\n"
"StationInfo[] stations\n"
"string station_msg\n"
"\n"
"float64 remind_distance\n"
"int32 remind_time\n"
"\n"
"int32 turn_type\n"
"float64 length_to_turn\n"
"\n"
"================================================================================\n"
"MSG: itri_msgs/Waypoint\n"
"geometry_msgs/PoseStamped pose\n"
"geometry_msgs/TwistStamped twist\n"
"int32 laneId\n"
"int32 pointId\n"
"geometry_msgs/Point point\n"
"float32 heading\n"
"float32 curvature\n"
"float32 speed_limit\n"
"int32 point_id\n"
"int32 lane_id\n"
"int32 nroad_id\n"
"float32 s\n"
"float32 d\n"
"float32 left_space\n"
"float32 right_space\n"
"float32 width\n"
"int32 road_type\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/TwistStamped\n"
"# A twist with reference coordinate frame and timestamp\n"
"Header header\n"
"Twist twist\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: itri_msgs/StationInfo\n"
"string name\n"
"bool isPass\n"
"Waypoint location\n"
"int32 nearPointIndex\n"
;
  }

  static const char* value(const ::itri_msgs::lane_waypoints_info_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::itri_msgs::lane_waypoints_info_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.point);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct lane_waypoints_info_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::itri_msgs::lane_waypoints_info_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::itri_msgs::lane_waypoints_info_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "point[]" << std::endl;
    for (size_t i = 0; i < v.point.size(); ++i)
    {
      s << indent << "  point[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::itri_msgs::lane_info_<ContainerAllocator> >::stream(s, indent + "    ", v.point[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ITRI_MSGS_MESSAGE_LANE_WAYPOINTS_INFO_H
