// Generated by gencpp from file itri_msgs/PredictedPath.msg
// DO NOT EDIT!


#ifndef ITRI_MSGS_MESSAGE_PREDICTEDPATH_H
#define ITRI_MSGS_MESSAGE_PREDICTEDPATH_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace itri_msgs
{
template <class ContainerAllocator>
struct PredictedPath_
{
  typedef PredictedPath_<ContainerAllocator> Type;

  PredictedPath_()
    : probability(0.0)
    , predicted_path()
    , predicted_velocity()  {
    }
  PredictedPath_(const ContainerAllocator& _alloc)
    : probability(0.0)
    , predicted_path(_alloc)
    , predicted_velocity(_alloc)  {
  (void)_alloc;
    }



   typedef float _probability_type;
  _probability_type probability;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _predicted_path_type;
  _predicted_path_type predicted_path;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _predicted_velocity_type;
  _predicted_velocity_type predicted_velocity;





  typedef boost::shared_ptr< ::itri_msgs::PredictedPath_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::itri_msgs::PredictedPath_<ContainerAllocator> const> ConstPtr;

}; // struct PredictedPath_

typedef ::itri_msgs::PredictedPath_<std::allocator<void> > PredictedPath;

typedef boost::shared_ptr< ::itri_msgs::PredictedPath > PredictedPathPtr;
typedef boost::shared_ptr< ::itri_msgs::PredictedPath const> PredictedPathConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::itri_msgs::PredictedPath_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::itri_msgs::PredictedPath_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::itri_msgs::PredictedPath_<ContainerAllocator1> & lhs, const ::itri_msgs::PredictedPath_<ContainerAllocator2> & rhs)
{
  return lhs.probability == rhs.probability &&
    lhs.predicted_path == rhs.predicted_path &&
    lhs.predicted_velocity == rhs.predicted_velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::itri_msgs::PredictedPath_<ContainerAllocator1> & lhs, const ::itri_msgs::PredictedPath_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace itri_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::itri_msgs::PredictedPath_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::itri_msgs::PredictedPath_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::itri_msgs::PredictedPath_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::itri_msgs::PredictedPath_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::itri_msgs::PredictedPath_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::itri_msgs::PredictedPath_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::itri_msgs::PredictedPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "46863c23a206bf9673e0a4bf16fae636";
  }

  static const char* value(const ::itri_msgs::PredictedPath_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x46863c23a206bf96ULL;
  static const uint64_t static_value2 = 0x73e0a4bf16fae636ULL;
};

template<class ContainerAllocator>
struct DataType< ::itri_msgs::PredictedPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "itri_msgs/PredictedPath";
  }

  static const char* value(const ::itri_msgs::PredictedPath_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::itri_msgs::PredictedPath_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 probability\n"
"geometry_msgs/Point[] predicted_path\n"
"geometry_msgs/Point[] predicted_velocity\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::itri_msgs::PredictedPath_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::itri_msgs::PredictedPath_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.probability);
      stream.next(m.predicted_path);
      stream.next(m.predicted_velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PredictedPath_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::itri_msgs::PredictedPath_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::itri_msgs::PredictedPath_<ContainerAllocator>& v)
  {
    s << indent << "probability: ";
    Printer<float>::stream(s, indent + "  ", v.probability);
    s << indent << "predicted_path[]" << std::endl;
    for (size_t i = 0; i < v.predicted_path.size(); ++i)
    {
      s << indent << "  predicted_path[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.predicted_path[i]);
    }
    s << indent << "predicted_velocity[]" << std::endl;
    for (size_t i = 0; i < v.predicted_velocity.size(); ++i)
    {
      s << indent << "  predicted_velocity[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.predicted_velocity[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ITRI_MSGS_MESSAGE_PREDICTEDPATH_H
