// Generated by gencpp from file itri_msgs/speed_cmd.msg
// DO NOT EDIT!


#ifndef ITRI_MSGS_MESSAGE_SPEED_CMD_H
#define ITRI_MSGS_MESSAGE_SPEED_CMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace itri_msgs
{
template <class ContainerAllocator>
struct speed_cmd_
{
  typedef speed_cmd_<ContainerAllocator> Type;

  speed_cmd_()
    : header()
    , type(0)
    , kph(0.0)
    , acceleration(0.0)
    , velocityCmdState(0)  {
    }
  speed_cmd_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , type(0)
    , kph(0.0)
    , acceleration(0.0)
    , velocityCmdState(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _type_type;
  _type_type type;

   typedef float _kph_type;
  _kph_type kph;

   typedef float _acceleration_type;
  _acceleration_type acceleration;

   typedef uint8_t _velocityCmdState_type;
  _velocityCmdState_type velocityCmdState;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(OPEN_LOOP)
  #undef OPEN_LOOP
#endif
#if defined(_WIN32) && defined(CLOSE_LOOP)
  #undef CLOSE_LOOP
#endif
#if defined(_WIN32) && defined(NON_DEFINE)
  #undef NON_DEFINE
#endif
#if defined(_WIN32) && defined(ACCELERATION)
  #undef ACCELERATION
#endif
#if defined(_WIN32) && defined(CONSTANT_SPEED)
  #undef CONSTANT_SPEED
#endif
#if defined(_WIN32) && defined(DEACCELERATION)
  #undef DEACCELERATION
#endif

  enum {
    OPEN_LOOP = 0u,
    CLOSE_LOOP = 1u,
    NON_DEFINE = 0u,
    ACCELERATION = 1u,
    CONSTANT_SPEED = 2u,
    DEACCELERATION = 3u,
  };


  typedef boost::shared_ptr< ::itri_msgs::speed_cmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::itri_msgs::speed_cmd_<ContainerAllocator> const> ConstPtr;

}; // struct speed_cmd_

typedef ::itri_msgs::speed_cmd_<std::allocator<void> > speed_cmd;

typedef boost::shared_ptr< ::itri_msgs::speed_cmd > speed_cmdPtr;
typedef boost::shared_ptr< ::itri_msgs::speed_cmd const> speed_cmdConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::itri_msgs::speed_cmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::itri_msgs::speed_cmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::itri_msgs::speed_cmd_<ContainerAllocator1> & lhs, const ::itri_msgs::speed_cmd_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.type == rhs.type &&
    lhs.kph == rhs.kph &&
    lhs.acceleration == rhs.acceleration &&
    lhs.velocityCmdState == rhs.velocityCmdState;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::itri_msgs::speed_cmd_<ContainerAllocator1> & lhs, const ::itri_msgs::speed_cmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace itri_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::itri_msgs::speed_cmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::itri_msgs::speed_cmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::itri_msgs::speed_cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::itri_msgs::speed_cmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::itri_msgs::speed_cmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::itri_msgs::speed_cmd_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::itri_msgs::speed_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "72fdcf92cab2efe452f034bb122ac210";
  }

  static const char* value(const ::itri_msgs::speed_cmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x72fdcf92cab2efe4ULL;
  static const uint64_t static_value2 = 0x52f034bb122ac210ULL;
};

template<class ContainerAllocator>
struct DataType< ::itri_msgs::speed_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "itri_msgs/speed_cmd";
  }

  static const char* value(const ::itri_msgs::speed_cmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::itri_msgs::speed_cmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"uint8 OPEN_LOOP = 0\n"
"uint8 CLOSE_LOOP = 1\n"
"\n"
"uint8 NON_DEFINE = 0\n"
"uint8 ACCELERATION = 1\n"
"uint8 CONSTANT_SPEED = 2\n"
"uint8 DEACCELERATION = 3\n"
"\n"
"uint8 type\n"
"float32 kph\n"
"float32 acceleration\n"
"uint8 velocityCmdState\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::itri_msgs::speed_cmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::itri_msgs::speed_cmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.type);
      stream.next(m.kph);
      stream.next(m.acceleration);
      stream.next(m.velocityCmdState);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct speed_cmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::itri_msgs::speed_cmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::itri_msgs::speed_cmd_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.type);
    s << indent << "kph: ";
    Printer<float>::stream(s, indent + "  ", v.kph);
    s << indent << "acceleration: ";
    Printer<float>::stream(s, indent + "  ", v.acceleration);
    s << indent << "velocityCmdState: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.velocityCmdState);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ITRI_MSGS_MESSAGE_SPEED_CMD_H
