// Generated by gencpp from file itri_msgs/TrafficSignObjects.msg
// DO NOT EDIT!


#ifndef ITRI_MSGS_MESSAGE_TRAFFICSIGNOBJECTS_H
#define ITRI_MSGS_MESSAGE_TRAFFICSIGNOBJECTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <itri_msgs/TrafficSignObject.h>

namespace itri_msgs
{
template <class ContainerAllocator>
struct TrafficSignObjects_
{
  typedef TrafficSignObjects_<ContainerAllocator> Type;

  TrafficSignObjects_()
    : header()
    , signs()  {
    }
  TrafficSignObjects_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , signs(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::itri_msgs::TrafficSignObject_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::itri_msgs::TrafficSignObject_<ContainerAllocator> >::other >  _signs_type;
  _signs_type signs;





  typedef boost::shared_ptr< ::itri_msgs::TrafficSignObjects_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::itri_msgs::TrafficSignObjects_<ContainerAllocator> const> ConstPtr;

}; // struct TrafficSignObjects_

typedef ::itri_msgs::TrafficSignObjects_<std::allocator<void> > TrafficSignObjects;

typedef boost::shared_ptr< ::itri_msgs::TrafficSignObjects > TrafficSignObjectsPtr;
typedef boost::shared_ptr< ::itri_msgs::TrafficSignObjects const> TrafficSignObjectsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::itri_msgs::TrafficSignObjects_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::itri_msgs::TrafficSignObjects_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::itri_msgs::TrafficSignObjects_<ContainerAllocator1> & lhs, const ::itri_msgs::TrafficSignObjects_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.signs == rhs.signs;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::itri_msgs::TrafficSignObjects_<ContainerAllocator1> & lhs, const ::itri_msgs::TrafficSignObjects_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace itri_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::itri_msgs::TrafficSignObjects_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::itri_msgs::TrafficSignObjects_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::itri_msgs::TrafficSignObjects_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::itri_msgs::TrafficSignObjects_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::itri_msgs::TrafficSignObjects_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::itri_msgs::TrafficSignObjects_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::itri_msgs::TrafficSignObjects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "87034deff55157e68a423890ed562f90";
  }

  static const char* value(const ::itri_msgs::TrafficSignObjects_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x87034deff55157e6ULL;
  static const uint64_t static_value2 = 0x8a423890ed562f90ULL;
};

template<class ContainerAllocator>
struct DataType< ::itri_msgs::TrafficSignObjects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "itri_msgs/TrafficSignObjects";
  }

  static const char* value(const ::itri_msgs::TrafficSignObjects_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::itri_msgs::TrafficSignObjects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"TrafficSignObject[] signs\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: itri_msgs/TrafficSignObject\n"
"bool stop\n"
"\n"
"sensor_msgs/RegionOfInterest roi\n"
"float32 score\n"
"\n"
"int32 id\n"
"float32 distance\n"
"string[] sign\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/RegionOfInterest\n"
"# This message is used to specify a region of interest within an image.\n"
"#\n"
"# When used to specify the ROI setting of the camera when the image was\n"
"# taken, the height and width fields should either match the height and\n"
"# width fields for the associated image; or height = width = 0\n"
"# indicates that the full resolution image was captured.\n"
"\n"
"uint32 x_offset  # Leftmost pixel of the ROI\n"
"                 # (0 if the ROI includes the left edge of the image)\n"
"uint32 y_offset  # Topmost pixel of the ROI\n"
"                 # (0 if the ROI includes the top edge of the image)\n"
"uint32 height    # Height of ROI\n"
"uint32 width     # Width of ROI\n"
"\n"
"# True if a distinct rectified ROI should be calculated from the \"raw\"\n"
"# ROI in this message. Typically this should be False if the full image\n"
"# is captured (ROI not used), and True if a subwindow is captured (ROI\n"
"# used).\n"
"bool do_rectify\n"
;
  }

  static const char* value(const ::itri_msgs::TrafficSignObjects_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::itri_msgs::TrafficSignObjects_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.signs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrafficSignObjects_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::itri_msgs::TrafficSignObjects_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::itri_msgs::TrafficSignObjects_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "signs[]" << std::endl;
    for (size_t i = 0; i < v.signs.size(); ++i)
    {
      s << indent << "  signs[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::itri_msgs::TrafficSignObject_<ContainerAllocator> >::stream(s, indent + "    ", v.signs[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ITRI_MSGS_MESSAGE_TRAFFICSIGNOBJECTS_H
