// Generated by gencpp from file itri_msgs/WaypointArrays.msg
// DO NOT EDIT!


#ifndef ITRI_MSGS_MESSAGE_WAYPOINTARRAYS_H
#define ITRI_MSGS_MESSAGE_WAYPOINTARRAYS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <itri_msgs/WaypointArray.h>

namespace itri_msgs
{
template <class ContainerAllocator>
struct WaypointArrays_
{
  typedef WaypointArrays_<ContainerAllocator> Type;

  WaypointArrays_()
    : header()
    , waypointArrays()  {
    }
  WaypointArrays_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , waypointArrays(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::itri_msgs::WaypointArray_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::itri_msgs::WaypointArray_<ContainerAllocator> >::other >  _waypointArrays_type;
  _waypointArrays_type waypointArrays;





  typedef boost::shared_ptr< ::itri_msgs::WaypointArrays_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::itri_msgs::WaypointArrays_<ContainerAllocator> const> ConstPtr;

}; // struct WaypointArrays_

typedef ::itri_msgs::WaypointArrays_<std::allocator<void> > WaypointArrays;

typedef boost::shared_ptr< ::itri_msgs::WaypointArrays > WaypointArraysPtr;
typedef boost::shared_ptr< ::itri_msgs::WaypointArrays const> WaypointArraysConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::itri_msgs::WaypointArrays_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::itri_msgs::WaypointArrays_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::itri_msgs::WaypointArrays_<ContainerAllocator1> & lhs, const ::itri_msgs::WaypointArrays_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.waypointArrays == rhs.waypointArrays;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::itri_msgs::WaypointArrays_<ContainerAllocator1> & lhs, const ::itri_msgs::WaypointArrays_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace itri_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::itri_msgs::WaypointArrays_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::itri_msgs::WaypointArrays_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::itri_msgs::WaypointArrays_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::itri_msgs::WaypointArrays_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::itri_msgs::WaypointArrays_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::itri_msgs::WaypointArrays_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::itri_msgs::WaypointArrays_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5cf91a176a73c53c3ba629de506b492f";
  }

  static const char* value(const ::itri_msgs::WaypointArrays_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5cf91a176a73c53cULL;
  static const uint64_t static_value2 = 0x3ba629de506b492fULL;
};

template<class ContainerAllocator>
struct DataType< ::itri_msgs::WaypointArrays_<ContainerAllocator> >
{
  static const char* value()
  {
    return "itri_msgs/WaypointArrays";
  }

  static const char* value(const ::itri_msgs::WaypointArrays_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::itri_msgs::WaypointArrays_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"WaypointArray[] waypointArrays\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: itri_msgs/WaypointArray\n"
"Header header\n"
"\n"
"uint8 FORWARD = 0\n"
"uint8 BACKWARD = 1\n"
"uint8 direction\n"
"\n"
"uint8 REGULAR = 0\n"
"uint8 RRT = 1\n"
"uint8 NONE = 2\n"
"uint8 type\n"
"\n"
"Waypoint[] waypoints\n"
"\n"
"uint8 updateId\n"
"float32 prob\n"
"\n"
"================================================================================\n"
"MSG: itri_msgs/Waypoint\n"
"geometry_msgs/PoseStamped pose\n"
"geometry_msgs/TwistStamped twist\n"
"int32 laneId\n"
"int32 pointId\n"
"geometry_msgs/Point point\n"
"float32 heading\n"
"float32 curvature\n"
"float32 speed_limit\n"
"int32 point_id\n"
"int32 lane_id\n"
"int32 nroad_id\n"
"float32 s\n"
"float32 d\n"
"float32 left_space\n"
"float32 right_space\n"
"float32 width\n"
"int32 road_type\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/TwistStamped\n"
"# A twist with reference coordinate frame and timestamp\n"
"Header header\n"
"Twist twist\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::itri_msgs::WaypointArrays_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::itri_msgs::WaypointArrays_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.waypointArrays);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WaypointArrays_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::itri_msgs::WaypointArrays_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::itri_msgs::WaypointArrays_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "waypointArrays[]" << std::endl;
    for (size_t i = 0; i < v.waypointArrays.size(); ++i)
    {
      s << indent << "  waypointArrays[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::itri_msgs::WaypointArray_<ContainerAllocator> >::stream(s, indent + "    ", v.waypointArrays[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ITRI_MSGS_MESSAGE_WAYPOINTARRAYS_H
