// Generated by gencpp from file route_mission_handler/LaneNavgRoadArray.msg
// DO NOT EDIT!


#ifndef ROUTE_MISSION_HANDLER_MESSAGE_LANENAVGROADARRAY_H
#define ROUTE_MISSION_HANDLER_MESSAGE_LANENAVGROADARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <route_mission_handler/LaneNavgRoad.h>

namespace route_mission_handler
{
template <class ContainerAllocator>
struct LaneNavgRoadArray_
{
  typedef LaneNavgRoadArray_<ContainerAllocator> Type;

  LaneNavgRoadArray_()
    : lanenavgroads()  {
    }
  LaneNavgRoadArray_(const ContainerAllocator& _alloc)
    : lanenavgroads(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::route_mission_handler::LaneNavgRoad_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::route_mission_handler::LaneNavgRoad_<ContainerAllocator> >::other >  _lanenavgroads_type;
  _lanenavgroads_type lanenavgroads;





  typedef boost::shared_ptr< ::route_mission_handler::LaneNavgRoadArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::route_mission_handler::LaneNavgRoadArray_<ContainerAllocator> const> ConstPtr;

}; // struct LaneNavgRoadArray_

typedef ::route_mission_handler::LaneNavgRoadArray_<std::allocator<void> > LaneNavgRoadArray;

typedef boost::shared_ptr< ::route_mission_handler::LaneNavgRoadArray > LaneNavgRoadArrayPtr;
typedef boost::shared_ptr< ::route_mission_handler::LaneNavgRoadArray const> LaneNavgRoadArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::route_mission_handler::LaneNavgRoadArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::route_mission_handler::LaneNavgRoadArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::route_mission_handler::LaneNavgRoadArray_<ContainerAllocator1> & lhs, const ::route_mission_handler::LaneNavgRoadArray_<ContainerAllocator2> & rhs)
{
  return lhs.lanenavgroads == rhs.lanenavgroads;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::route_mission_handler::LaneNavgRoadArray_<ContainerAllocator1> & lhs, const ::route_mission_handler::LaneNavgRoadArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace route_mission_handler

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::route_mission_handler::LaneNavgRoadArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::route_mission_handler::LaneNavgRoadArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::route_mission_handler::LaneNavgRoadArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::route_mission_handler::LaneNavgRoadArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::route_mission_handler::LaneNavgRoadArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::route_mission_handler::LaneNavgRoadArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::route_mission_handler::LaneNavgRoadArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9dd8b7cd48bd0df0290a75d6bb5b2e91";
  }

  static const char* value(const ::route_mission_handler::LaneNavgRoadArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9dd8b7cd48bd0df0ULL;
  static const uint64_t static_value2 = 0x290a75d6bb5b2e91ULL;
};

template<class ContainerAllocator>
struct DataType< ::route_mission_handler::LaneNavgRoadArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "route_mission_handler/LaneNavgRoadArray";
  }

  static const char* value(const ::route_mission_handler::LaneNavgRoadArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::route_mission_handler::LaneNavgRoadArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "LaneNavgRoad[] lanenavgroads\n"
"\n"
"================================================================================\n"
"MSG: route_mission_handler/LaneNavgRoad\n"
"int32 lane_id\n"
"int32 laneno\n"
"int32 navgroad1\n"
"bool isPositive1\n"
"int32 navgroad2\n"
"bool isPositive2\n"
"string seqner\n"
;
  }

  static const char* value(const ::route_mission_handler::LaneNavgRoadArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::route_mission_handler::LaneNavgRoadArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lanenavgroads);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LaneNavgRoadArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::route_mission_handler::LaneNavgRoadArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::route_mission_handler::LaneNavgRoadArray_<ContainerAllocator>& v)
  {
    s << indent << "lanenavgroads[]" << std::endl;
    for (size_t i = 0; i < v.lanenavgroads.size(); ++i)
    {
      s << indent << "  lanenavgroads[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::route_mission_handler::LaneNavgRoad_<ContainerAllocator> >::stream(s, indent + "    ", v.lanenavgroads[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROUTE_MISSION_HANDLER_MESSAGE_LANENAVGROADARRAY_H
