// Generated by gencpp from file route_mission_handler/Pair.msg
// DO NOT EDIT!


#ifndef ROUTE_MISSION_HANDLER_MESSAGE_PAIR_H
#define ROUTE_MISSION_HANDLER_MESSAGE_PAIR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace route_mission_handler
{
template <class ContainerAllocator>
struct Pair_
{
  typedef Pair_<ContainerAllocator> Type;

  Pair_()
    : laneId(0)
    , pointIds()  {
    }
  Pair_(const ContainerAllocator& _alloc)
    : laneId(0)
    , pointIds(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _laneId_type;
  _laneId_type laneId;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _pointIds_type;
  _pointIds_type pointIds;





  typedef boost::shared_ptr< ::route_mission_handler::Pair_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::route_mission_handler::Pair_<ContainerAllocator> const> ConstPtr;

}; // struct Pair_

typedef ::route_mission_handler::Pair_<std::allocator<void> > Pair;

typedef boost::shared_ptr< ::route_mission_handler::Pair > PairPtr;
typedef boost::shared_ptr< ::route_mission_handler::Pair const> PairConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::route_mission_handler::Pair_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::route_mission_handler::Pair_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::route_mission_handler::Pair_<ContainerAllocator1> & lhs, const ::route_mission_handler::Pair_<ContainerAllocator2> & rhs)
{
  return lhs.laneId == rhs.laneId &&
    lhs.pointIds == rhs.pointIds;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::route_mission_handler::Pair_<ContainerAllocator1> & lhs, const ::route_mission_handler::Pair_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace route_mission_handler

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::route_mission_handler::Pair_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::route_mission_handler::Pair_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::route_mission_handler::Pair_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::route_mission_handler::Pair_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::route_mission_handler::Pair_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::route_mission_handler::Pair_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::route_mission_handler::Pair_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9c79f7b537dfd0f3480010c95f09d489";
  }

  static const char* value(const ::route_mission_handler::Pair_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9c79f7b537dfd0f3ULL;
  static const uint64_t static_value2 = 0x480010c95f09d489ULL;
};

template<class ContainerAllocator>
struct DataType< ::route_mission_handler::Pair_<ContainerAllocator> >
{
  static const char* value()
  {
    return "route_mission_handler/Pair";
  }

  static const char* value(const ::route_mission_handler::Pair_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::route_mission_handler::Pair_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 laneId\n"
"int32[] pointIds\n"
;
  }

  static const char* value(const ::route_mission_handler::Pair_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::route_mission_handler::Pair_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.laneId);
      stream.next(m.pointIds);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Pair_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::route_mission_handler::Pair_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::route_mission_handler::Pair_<ContainerAllocator>& v)
  {
    s << indent << "laneId: ";
    Printer<int32_t>::stream(s, indent + "  ", v.laneId);
    s << indent << "pointIds[]" << std::endl;
    for (size_t i = 0; i < v.pointIds.size(); ++i)
    {
      s << indent << "  pointIds[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.pointIds[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROUTE_MISSION_HANDLER_MESSAGE_PAIR_H
