(cl:in-package dbw_pacifica_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          TURN_SIGNAL_STATE-VAL
          TURN_SIGNAL_STATE
          HIGH_BEAM_HEADLIGHTS_STATE-VAL
          HIGH_BEAM_HEADLIGHTS_STATE
          LOW_BEAM_HEADLIGHTS_STATE-VAL
          LOW_BEAM_HEADLIGHTS_STATE
          FRONT_WIPER_STATE-VAL
          FRONT_WIPER_STATE
          REAR_WIPER_STATE-VAL
          REAR_WIPER_STATE
          ROLLING_COUNTER-VAL
          ROLLING_COUNTER
          IGNITION_STATE-VAL
          IGNITION_STATE
          REAR_LEFT_DOOR_STATE-VAL
          REAR_LEFT_DOOR_STATE
          REAR_RIGHT_DOOR_STATE-VAL
          REAR_RIGHT_DOOR_STATE
          LIFTGATE_STATE-VAL
          LIFTGATE_STATE
          DOOR_LOCK_STATE-VAL
          DOOR_LOCK_STATE
))