(cl:in-package dbw_pacifica_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          DBW_BATTERY_VOLTS-VAL
          DBW_BATTERY_VOLTS
          VEHICLE_BATTERY_VOLTS-VAL
          VEHICLE_BATTERY_VOLTS
          VEHICLE_BATTERY_CURRENT-VAL
          VEHICLE_BATTERY_CURRENT
          VEHICLE_ALTERNATOR_CURRENT-VAL
          VEHICLE_ALTERNATOR_CURRENT
          DCDC_CURRENT-VAL
          DCDC_CURRENT
          ALTERNATOR_CURRENT-VAL
          ALTERNATOR_CURRENT
          AUX_BATTERY_CONTACTOR-VAL
          AUX_BATTERY_CONTACTOR
          AUX_INVERTER_CONTACTOR-VAL
          AUX_INVERTER_CONTACTOR
))