(cl:in-package dbw_pacifica_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          AUTO_DISABLE_NO_BRAKES-VAL
          AUTO_DISABLE_NO_BRAKES
          AUTO_DISABLE_APPLY_BRAKES-VAL
          AUTO_DISABLE_APPLY_BRAKES
          DBW_CAN_GATEWAY_DISABLE-VAL
          DBW_CAN_GATEWAY_DISABLE
          INVERTER_CNT_CONTROL_DISABLE-VAL
          INVERTER_CNT_CONTROL_DISABLE
          PREVENT_ENTER_AUTO_MODE-VAL
          PREVENT_ENTER_AUTO_MODE
          WARN_DRIVER_ONLY-VAL
          WARN_DRIVER_ONLY
          CHIME_FCW_BEEPS-VAL
          CHIME_FCW_BEEPS
))