Header header

# Turn Signal enumeration
TurnSignal turn_signal_state

# High beams
HighBeam high_beam_headlights_state

# Low beams
LowBeam low_beam_headlights_state

# Windshield Wipers enumeration
WiperFront front_wiper_state
WiperRear rear_wiper_state

# Watchdog counter
uint8 rolling_counter

# Ignition
Ignition ignition_state

# HornState
#HornState

# Door status
Door rear_left_door_state
Door rear_right_door_state
Door liftgate_state

#Door lock
DoorLock door_lock_state
