// Generated by gencpp from file dbw_pacifica_msgs/ActuatorsReport.msg
// DO NOT EDIT!


#ifndef DBW_PACIFICA_MSGS_MESSAGE_ACTUATORSREPORT_H
#define DBW_PACIFICA_MSGS_MESSAGE_ACTUATORSREPORT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <dbw_pacifica_msgs/TurnSignal.h>
#include <dbw_pacifica_msgs/HighBeam.h>
#include <dbw_pacifica_msgs/LowBeam.h>
#include <dbw_pacifica_msgs/WiperFront.h>
#include <dbw_pacifica_msgs/WiperRear.h>
#include <dbw_pacifica_msgs/Ignition.h>
#include <dbw_pacifica_msgs/Door.h>
#include <dbw_pacifica_msgs/Door.h>
#include <dbw_pacifica_msgs/Door.h>
#include <dbw_pacifica_msgs/DoorLock.h>

namespace dbw_pacifica_msgs
{
template <class ContainerAllocator>
struct ActuatorsReport_
{
  typedef ActuatorsReport_<ContainerAllocator> Type;

  ActuatorsReport_()
    : header()
    , turn_signal_state()
    , high_beam_headlights_state()
    , low_beam_headlights_state()
    , front_wiper_state()
    , rear_wiper_state()
    , rolling_counter(0)
    , ignition_state()
    , rear_left_door_state()
    , rear_right_door_state()
    , liftgate_state()
    , door_lock_state()  {
    }
  ActuatorsReport_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , turn_signal_state(_alloc)
    , high_beam_headlights_state(_alloc)
    , low_beam_headlights_state(_alloc)
    , front_wiper_state(_alloc)
    , rear_wiper_state(_alloc)
    , rolling_counter(0)
    , ignition_state(_alloc)
    , rear_left_door_state(_alloc)
    , rear_right_door_state(_alloc)
    , liftgate_state(_alloc)
    , door_lock_state(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::dbw_pacifica_msgs::TurnSignal_<ContainerAllocator>  _turn_signal_state_type;
  _turn_signal_state_type turn_signal_state;

   typedef  ::dbw_pacifica_msgs::HighBeam_<ContainerAllocator>  _high_beam_headlights_state_type;
  _high_beam_headlights_state_type high_beam_headlights_state;

   typedef  ::dbw_pacifica_msgs::LowBeam_<ContainerAllocator>  _low_beam_headlights_state_type;
  _low_beam_headlights_state_type low_beam_headlights_state;

   typedef  ::dbw_pacifica_msgs::WiperFront_<ContainerAllocator>  _front_wiper_state_type;
  _front_wiper_state_type front_wiper_state;

   typedef  ::dbw_pacifica_msgs::WiperRear_<ContainerAllocator>  _rear_wiper_state_type;
  _rear_wiper_state_type rear_wiper_state;

   typedef uint8_t _rolling_counter_type;
  _rolling_counter_type rolling_counter;

   typedef  ::dbw_pacifica_msgs::Ignition_<ContainerAllocator>  _ignition_state_type;
  _ignition_state_type ignition_state;

   typedef  ::dbw_pacifica_msgs::Door_<ContainerAllocator>  _rear_left_door_state_type;
  _rear_left_door_state_type rear_left_door_state;

   typedef  ::dbw_pacifica_msgs::Door_<ContainerAllocator>  _rear_right_door_state_type;
  _rear_right_door_state_type rear_right_door_state;

   typedef  ::dbw_pacifica_msgs::Door_<ContainerAllocator>  _liftgate_state_type;
  _liftgate_state_type liftgate_state;

   typedef  ::dbw_pacifica_msgs::DoorLock_<ContainerAllocator>  _door_lock_state_type;
  _door_lock_state_type door_lock_state;





  typedef boost::shared_ptr< ::dbw_pacifica_msgs::ActuatorsReport_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dbw_pacifica_msgs::ActuatorsReport_<ContainerAllocator> const> ConstPtr;

}; // struct ActuatorsReport_

typedef ::dbw_pacifica_msgs::ActuatorsReport_<std::allocator<void> > ActuatorsReport;

typedef boost::shared_ptr< ::dbw_pacifica_msgs::ActuatorsReport > ActuatorsReportPtr;
typedef boost::shared_ptr< ::dbw_pacifica_msgs::ActuatorsReport const> ActuatorsReportConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dbw_pacifica_msgs::ActuatorsReport_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dbw_pacifica_msgs::ActuatorsReport_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dbw_pacifica_msgs::ActuatorsReport_<ContainerAllocator1> & lhs, const ::dbw_pacifica_msgs::ActuatorsReport_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.turn_signal_state == rhs.turn_signal_state &&
    lhs.high_beam_headlights_state == rhs.high_beam_headlights_state &&
    lhs.low_beam_headlights_state == rhs.low_beam_headlights_state &&
    lhs.front_wiper_state == rhs.front_wiper_state &&
    lhs.rear_wiper_state == rhs.rear_wiper_state &&
    lhs.rolling_counter == rhs.rolling_counter &&
    lhs.ignition_state == rhs.ignition_state &&
    lhs.rear_left_door_state == rhs.rear_left_door_state &&
    lhs.rear_right_door_state == rhs.rear_right_door_state &&
    lhs.liftgate_state == rhs.liftgate_state &&
    lhs.door_lock_state == rhs.door_lock_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dbw_pacifica_msgs::ActuatorsReport_<ContainerAllocator1> & lhs, const ::dbw_pacifica_msgs::ActuatorsReport_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dbw_pacifica_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::dbw_pacifica_msgs::ActuatorsReport_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dbw_pacifica_msgs::ActuatorsReport_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dbw_pacifica_msgs::ActuatorsReport_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dbw_pacifica_msgs::ActuatorsReport_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dbw_pacifica_msgs::ActuatorsReport_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dbw_pacifica_msgs::ActuatorsReport_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dbw_pacifica_msgs::ActuatorsReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d66d15b164e1cf2d467650778182b722";
  }

  static const char* value(const ::dbw_pacifica_msgs::ActuatorsReport_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd66d15b164e1cf2dULL;
  static const uint64_t static_value2 = 0x467650778182b722ULL;
};

template<class ContainerAllocator>
struct DataType< ::dbw_pacifica_msgs::ActuatorsReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dbw_pacifica_msgs/ActuatorsReport";
  }

  static const char* value(const ::dbw_pacifica_msgs::ActuatorsReport_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dbw_pacifica_msgs::ActuatorsReport_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"# Turn Signal enumeration\n"
"TurnSignal turn_signal_state\n"
"\n"
"# High beams\n"
"HighBeam high_beam_headlights_state\n"
"\n"
"# Low beams\n"
"LowBeam low_beam_headlights_state\n"
"\n"
"# Windshield Wipers enumeration\n"
"WiperFront front_wiper_state\n"
"WiperRear rear_wiper_state\n"
"\n"
"# Watchdog counter\n"
"uint8 rolling_counter\n"
"\n"
"# Ignition\n"
"Ignition ignition_state\n"
"\n"
"# HornState\n"
"#HornState\n"
"\n"
"# Door status\n"
"Door rear_left_door_state\n"
"Door rear_right_door_state\n"
"Door liftgate_state\n"
"\n"
"#Door lock\n"
"DoorLock door_lock_state\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: dbw_pacifica_msgs/TurnSignal\n"
"uint8 value\n"
"\n"
"uint8 NONE=0\n"
"uint8 LEFT=1\n"
"uint8 RIGHT=2\n"
"\n"
"================================================================================\n"
"MSG: dbw_pacifica_msgs/HighBeam\n"
"uint8 status\n"
"\n"
"uint8 OFF = 0\n"
"uint8 ON = 1\n"
"uint8 FLASH = 2\n"
"\n"
"================================================================================\n"
"MSG: dbw_pacifica_msgs/LowBeam\n"
"uint8 status\n"
"\n"
"uint8 OFF = 0\n"
"uint8 ON = 1\n"
"uint8 FLASH = 2\n"
"\n"
"================================================================================\n"
"MSG: dbw_pacifica_msgs/WiperFront\n"
"uint8 status\n"
"\n"
"uint8 OFF = 0\n"
"uint8 INTERVAL_1 = 1\n"
"uint8 INTERVAL_2 = 2\n"
"uint8 INTERVAL_3 = 3\n"
"uint8 INTERVAL_4 = 4\n"
"uint8 INTERVAL_5 = 5\n"
"uint8 INTERVAL_6 = 6\n"
"uint8 CONSTANT_LOW = 11\n"
"uint8 CONSTANT_HIGH = 12\n"
"uint8 WASH_BRIEF = 13\n"
"uint8 WASH_CONTINUOUS = 14\n"
"\n"
"================================================================================\n"
"MSG: dbw_pacifica_msgs/WiperRear\n"
"uint8 status\n"
"\n"
"uint8 OFF = 0\n"
"uint8 INTERVAL_1 = 1\n"
"uint8 CONSTANT_LOW = 11\n"
"uint8 CONSTANT_HIGH = 12\n"
"uint8 WASH_BRIEF = 13\n"
"uint8 WASH_CONTINUOUS = 14\n"
"\n"
"================================================================================\n"
"MSG: dbw_pacifica_msgs/Ignition\n"
"uint8 status\n"
"\n"
"uint8 NO_REQUEST = 0\n"
"uint8 FORCE_OFF = 0\n"
"uint8 ACCESSORY = 0\n"
"uint8 RUN = 0\n"
"uint8 CRANK = 0\n"
"================================================================================\n"
"MSG: dbw_pacifica_msgs/Door\n"
"uint8 value\n"
"\n"
"uint8 NO_REQUEST=0\n"
"uint8 CLOSE_DOOR=1\n"
"uint8 OPEN_DOOR=2\n"
"\n"
"================================================================================\n"
"MSG: dbw_pacifica_msgs/DoorLock\n"
"uint8 value\n"
"\n"
"uint8 NOREQUEST=0\n"
"uint8 UNLOCK=1\n"
"uint8 LOCK=2\n"
;
  }

  static const char* value(const ::dbw_pacifica_msgs::ActuatorsReport_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dbw_pacifica_msgs::ActuatorsReport_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.turn_signal_state);
      stream.next(m.high_beam_headlights_state);
      stream.next(m.low_beam_headlights_state);
      stream.next(m.front_wiper_state);
      stream.next(m.rear_wiper_state);
      stream.next(m.rolling_counter);
      stream.next(m.ignition_state);
      stream.next(m.rear_left_door_state);
      stream.next(m.rear_right_door_state);
      stream.next(m.liftgate_state);
      stream.next(m.door_lock_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActuatorsReport_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dbw_pacifica_msgs::ActuatorsReport_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dbw_pacifica_msgs::ActuatorsReport_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "turn_signal_state: ";
    s << std::endl;
    Printer< ::dbw_pacifica_msgs::TurnSignal_<ContainerAllocator> >::stream(s, indent + "  ", v.turn_signal_state);
    s << indent << "high_beam_headlights_state: ";
    s << std::endl;
    Printer< ::dbw_pacifica_msgs::HighBeam_<ContainerAllocator> >::stream(s, indent + "  ", v.high_beam_headlights_state);
    s << indent << "low_beam_headlights_state: ";
    s << std::endl;
    Printer< ::dbw_pacifica_msgs::LowBeam_<ContainerAllocator> >::stream(s, indent + "  ", v.low_beam_headlights_state);
    s << indent << "front_wiper_state: ";
    s << std::endl;
    Printer< ::dbw_pacifica_msgs::WiperFront_<ContainerAllocator> >::stream(s, indent + "  ", v.front_wiper_state);
    s << indent << "rear_wiper_state: ";
    s << std::endl;
    Printer< ::dbw_pacifica_msgs::WiperRear_<ContainerAllocator> >::stream(s, indent + "  ", v.rear_wiper_state);
    s << indent << "rolling_counter: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.rolling_counter);
    s << indent << "ignition_state: ";
    s << std::endl;
    Printer< ::dbw_pacifica_msgs::Ignition_<ContainerAllocator> >::stream(s, indent + "  ", v.ignition_state);
    s << indent << "rear_left_door_state: ";
    s << std::endl;
    Printer< ::dbw_pacifica_msgs::Door_<ContainerAllocator> >::stream(s, indent + "  ", v.rear_left_door_state);
    s << indent << "rear_right_door_state: ";
    s << std::endl;
    Printer< ::dbw_pacifica_msgs::Door_<ContainerAllocator> >::stream(s, indent + "  ", v.rear_right_door_state);
    s << indent << "liftgate_state: ";
    s << std::endl;
    Printer< ::dbw_pacifica_msgs::Door_<ContainerAllocator> >::stream(s, indent + "  ", v.liftgate_state);
    s << indent << "door_lock_state: ";
    s << std::endl;
    Printer< ::dbw_pacifica_msgs::DoorLock_<ContainerAllocator> >::stream(s, indent + "  ", v.door_lock_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DBW_PACIFICA_MSGS_MESSAGE_ACTUATORSREPORT_H
