// Generated by gencpp from file dbw_pacifica_msgs/MiscCmd.msg
// DO NOT EDIT!


#ifndef DBW_PACIFICA_MSGS_MESSAGE_MISCCMD_H
#define DBW_PACIFICA_MSGS_MESSAGE_MISCCMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <dbw_pacifica_msgs/TurnSignal.h>
#include <dbw_pacifica_msgs/Door.h>
#include <dbw_pacifica_msgs/HighBeam.h>
#include <dbw_pacifica_msgs/WiperFront.h>
#include <dbw_pacifica_msgs/WiperRear.h>
#include <dbw_pacifica_msgs/Ignition.h>
#include <dbw_pacifica_msgs/Door.h>
#include <dbw_pacifica_msgs/Door.h>
#include <dbw_pacifica_msgs/LowBeam.h>

namespace dbw_pacifica_msgs
{
template <class ContainerAllocator>
struct MiscCmd_
{
  typedef MiscCmd_<ContainerAllocator> Type;

  MiscCmd_()
    : cmd()
    , door_request_right_rear()
    , rolling_counter(0)
    , high_beam_cmd()
    , front_wiper_cmd()
    , rear_wiper_cmd()
    , ignition_cmd()
    , door_request_left_rear()
    , door_request_lift_gate()
    , block_standard_cruise_buttons(false)
    , block_adaptive_cruise_buttons(false)
    , block_turn_signal_stalk(false)
    , actuators_cmd_checksum(0.0)
    , hornReq(false)
    , low_beam_cmd()  {
    }
  MiscCmd_(const ContainerAllocator& _alloc)
    : cmd(_alloc)
    , door_request_right_rear(_alloc)
    , rolling_counter(0)
    , high_beam_cmd(_alloc)
    , front_wiper_cmd(_alloc)
    , rear_wiper_cmd(_alloc)
    , ignition_cmd(_alloc)
    , door_request_left_rear(_alloc)
    , door_request_lift_gate(_alloc)
    , block_standard_cruise_buttons(false)
    , block_adaptive_cruise_buttons(false)
    , block_turn_signal_stalk(false)
    , actuators_cmd_checksum(0.0)
    , hornReq(false)
    , low_beam_cmd(_alloc)  {
  (void)_alloc;
    }



   typedef  ::dbw_pacifica_msgs::TurnSignal_<ContainerAllocator>  _cmd_type;
  _cmd_type cmd;

   typedef  ::dbw_pacifica_msgs::Door_<ContainerAllocator>  _door_request_right_rear_type;
  _door_request_right_rear_type door_request_right_rear;

   typedef uint8_t _rolling_counter_type;
  _rolling_counter_type rolling_counter;

   typedef  ::dbw_pacifica_msgs::HighBeam_<ContainerAllocator>  _high_beam_cmd_type;
  _high_beam_cmd_type high_beam_cmd;

   typedef  ::dbw_pacifica_msgs::WiperFront_<ContainerAllocator>  _front_wiper_cmd_type;
  _front_wiper_cmd_type front_wiper_cmd;

   typedef  ::dbw_pacifica_msgs::WiperRear_<ContainerAllocator>  _rear_wiper_cmd_type;
  _rear_wiper_cmd_type rear_wiper_cmd;

   typedef  ::dbw_pacifica_msgs::Ignition_<ContainerAllocator>  _ignition_cmd_type;
  _ignition_cmd_type ignition_cmd;

   typedef  ::dbw_pacifica_msgs::Door_<ContainerAllocator>  _door_request_left_rear_type;
  _door_request_left_rear_type door_request_left_rear;

   typedef  ::dbw_pacifica_msgs::Door_<ContainerAllocator>  _door_request_lift_gate_type;
  _door_request_lift_gate_type door_request_lift_gate;

   typedef uint8_t _block_standard_cruise_buttons_type;
  _block_standard_cruise_buttons_type block_standard_cruise_buttons;

   typedef uint8_t _block_adaptive_cruise_buttons_type;
  _block_adaptive_cruise_buttons_type block_adaptive_cruise_buttons;

   typedef uint8_t _block_turn_signal_stalk_type;
  _block_turn_signal_stalk_type block_turn_signal_stalk;

   typedef float _actuators_cmd_checksum_type;
  _actuators_cmd_checksum_type actuators_cmd_checksum;

   typedef uint8_t _hornReq_type;
  _hornReq_type hornReq;

   typedef  ::dbw_pacifica_msgs::LowBeam_<ContainerAllocator>  _low_beam_cmd_type;
  _low_beam_cmd_type low_beam_cmd;





  typedef boost::shared_ptr< ::dbw_pacifica_msgs::MiscCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dbw_pacifica_msgs::MiscCmd_<ContainerAllocator> const> ConstPtr;

}; // struct MiscCmd_

typedef ::dbw_pacifica_msgs::MiscCmd_<std::allocator<void> > MiscCmd;

typedef boost::shared_ptr< ::dbw_pacifica_msgs::MiscCmd > MiscCmdPtr;
typedef boost::shared_ptr< ::dbw_pacifica_msgs::MiscCmd const> MiscCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dbw_pacifica_msgs::MiscCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dbw_pacifica_msgs::MiscCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dbw_pacifica_msgs::MiscCmd_<ContainerAllocator1> & lhs, const ::dbw_pacifica_msgs::MiscCmd_<ContainerAllocator2> & rhs)
{
  return lhs.cmd == rhs.cmd &&
    lhs.door_request_right_rear == rhs.door_request_right_rear &&
    lhs.rolling_counter == rhs.rolling_counter &&
    lhs.high_beam_cmd == rhs.high_beam_cmd &&
    lhs.front_wiper_cmd == rhs.front_wiper_cmd &&
    lhs.rear_wiper_cmd == rhs.rear_wiper_cmd &&
    lhs.ignition_cmd == rhs.ignition_cmd &&
    lhs.door_request_left_rear == rhs.door_request_left_rear &&
    lhs.door_request_lift_gate == rhs.door_request_lift_gate &&
    lhs.block_standard_cruise_buttons == rhs.block_standard_cruise_buttons &&
    lhs.block_adaptive_cruise_buttons == rhs.block_adaptive_cruise_buttons &&
    lhs.block_turn_signal_stalk == rhs.block_turn_signal_stalk &&
    lhs.actuators_cmd_checksum == rhs.actuators_cmd_checksum &&
    lhs.hornReq == rhs.hornReq &&
    lhs.low_beam_cmd == rhs.low_beam_cmd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dbw_pacifica_msgs::MiscCmd_<ContainerAllocator1> & lhs, const ::dbw_pacifica_msgs::MiscCmd_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dbw_pacifica_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::dbw_pacifica_msgs::MiscCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dbw_pacifica_msgs::MiscCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dbw_pacifica_msgs::MiscCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dbw_pacifica_msgs::MiscCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dbw_pacifica_msgs::MiscCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dbw_pacifica_msgs::MiscCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dbw_pacifica_msgs::MiscCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c5a8f076a15a9659536c514cdcd82275";
  }

  static const char* value(const ::dbw_pacifica_msgs::MiscCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc5a8f076a15a9659ULL;
  static const uint64_t static_value2 = 0x536c514cdcd82275ULL;
};

template<class ContainerAllocator>
struct DataType< ::dbw_pacifica_msgs::MiscCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dbw_pacifica_msgs/MiscCmd";
  }

  static const char* value(const ::dbw_pacifica_msgs::MiscCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dbw_pacifica_msgs::MiscCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Turn signal command enumeration\n"
"\n"
"TurnSignal cmd\n"
"\n"
"Door door_request_right_rear\n"
"\n"
"uint8 rolling_counter\n"
"\n"
"HighBeam high_beam_cmd\n"
"\n"
"WiperFront front_wiper_cmd\n"
"\n"
"WiperRear rear_wiper_cmd\n"
"\n"
"Ignition ignition_cmd\n"
"Door door_request_left_rear\n"
"Door door_request_lift_gate\n"
"\n"
"bool block_standard_cruise_buttons\n"
"bool block_adaptive_cruise_buttons\n"
"bool block_turn_signal_stalk\n"
"\n"
"float32 actuators_cmd_checksum\n"
"\n"
"bool hornReq\n"
"LowBeam low_beam_cmd\n"
"\n"
"================================================================================\n"
"MSG: dbw_pacifica_msgs/TurnSignal\n"
"uint8 value\n"
"\n"
"uint8 NONE=0\n"
"uint8 LEFT=1\n"
"uint8 RIGHT=2\n"
"\n"
"================================================================================\n"
"MSG: dbw_pacifica_msgs/Door\n"
"uint8 value\n"
"\n"
"uint8 NO_REQUEST=0\n"
"uint8 CLOSE_DOOR=1\n"
"uint8 OPEN_DOOR=2\n"
"\n"
"================================================================================\n"
"MSG: dbw_pacifica_msgs/HighBeam\n"
"uint8 status\n"
"\n"
"uint8 OFF = 0\n"
"uint8 ON = 1\n"
"uint8 FLASH = 2\n"
"\n"
"================================================================================\n"
"MSG: dbw_pacifica_msgs/WiperFront\n"
"uint8 status\n"
"\n"
"uint8 OFF = 0\n"
"uint8 INTERVAL_1 = 1\n"
"uint8 INTERVAL_2 = 2\n"
"uint8 INTERVAL_3 = 3\n"
"uint8 INTERVAL_4 = 4\n"
"uint8 INTERVAL_5 = 5\n"
"uint8 INTERVAL_6 = 6\n"
"uint8 CONSTANT_LOW = 11\n"
"uint8 CONSTANT_HIGH = 12\n"
"uint8 WASH_BRIEF = 13\n"
"uint8 WASH_CONTINUOUS = 14\n"
"\n"
"================================================================================\n"
"MSG: dbw_pacifica_msgs/WiperRear\n"
"uint8 status\n"
"\n"
"uint8 OFF = 0\n"
"uint8 INTERVAL_1 = 1\n"
"uint8 CONSTANT_LOW = 11\n"
"uint8 CONSTANT_HIGH = 12\n"
"uint8 WASH_BRIEF = 13\n"
"uint8 WASH_CONTINUOUS = 14\n"
"\n"
"================================================================================\n"
"MSG: dbw_pacifica_msgs/Ignition\n"
"uint8 status\n"
"\n"
"uint8 NO_REQUEST = 0\n"
"uint8 FORCE_OFF = 0\n"
"uint8 ACCESSORY = 0\n"
"uint8 RUN = 0\n"
"uint8 CRANK = 0\n"
"================================================================================\n"
"MSG: dbw_pacifica_msgs/LowBeam\n"
"uint8 status\n"
"\n"
"uint8 OFF = 0\n"
"uint8 ON = 1\n"
"uint8 FLASH = 2\n"
;
  }

  static const char* value(const ::dbw_pacifica_msgs::MiscCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dbw_pacifica_msgs::MiscCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cmd);
      stream.next(m.door_request_right_rear);
      stream.next(m.rolling_counter);
      stream.next(m.high_beam_cmd);
      stream.next(m.front_wiper_cmd);
      stream.next(m.rear_wiper_cmd);
      stream.next(m.ignition_cmd);
      stream.next(m.door_request_left_rear);
      stream.next(m.door_request_lift_gate);
      stream.next(m.block_standard_cruise_buttons);
      stream.next(m.block_adaptive_cruise_buttons);
      stream.next(m.block_turn_signal_stalk);
      stream.next(m.actuators_cmd_checksum);
      stream.next(m.hornReq);
      stream.next(m.low_beam_cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MiscCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dbw_pacifica_msgs::MiscCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dbw_pacifica_msgs::MiscCmd_<ContainerAllocator>& v)
  {
    s << indent << "cmd: ";
    s << std::endl;
    Printer< ::dbw_pacifica_msgs::TurnSignal_<ContainerAllocator> >::stream(s, indent + "  ", v.cmd);
    s << indent << "door_request_right_rear: ";
    s << std::endl;
    Printer< ::dbw_pacifica_msgs::Door_<ContainerAllocator> >::stream(s, indent + "  ", v.door_request_right_rear);
    s << indent << "rolling_counter: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.rolling_counter);
    s << indent << "high_beam_cmd: ";
    s << std::endl;
    Printer< ::dbw_pacifica_msgs::HighBeam_<ContainerAllocator> >::stream(s, indent + "  ", v.high_beam_cmd);
    s << indent << "front_wiper_cmd: ";
    s << std::endl;
    Printer< ::dbw_pacifica_msgs::WiperFront_<ContainerAllocator> >::stream(s, indent + "  ", v.front_wiper_cmd);
    s << indent << "rear_wiper_cmd: ";
    s << std::endl;
    Printer< ::dbw_pacifica_msgs::WiperRear_<ContainerAllocator> >::stream(s, indent + "  ", v.rear_wiper_cmd);
    s << indent << "ignition_cmd: ";
    s << std::endl;
    Printer< ::dbw_pacifica_msgs::Ignition_<ContainerAllocator> >::stream(s, indent + "  ", v.ignition_cmd);
    s << indent << "door_request_left_rear: ";
    s << std::endl;
    Printer< ::dbw_pacifica_msgs::Door_<ContainerAllocator> >::stream(s, indent + "  ", v.door_request_left_rear);
    s << indent << "door_request_lift_gate: ";
    s << std::endl;
    Printer< ::dbw_pacifica_msgs::Door_<ContainerAllocator> >::stream(s, indent + "  ", v.door_request_lift_gate);
    s << indent << "block_standard_cruise_buttons: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.block_standard_cruise_buttons);
    s << indent << "block_adaptive_cruise_buttons: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.block_adaptive_cruise_buttons);
    s << indent << "block_turn_signal_stalk: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.block_turn_signal_stalk);
    s << indent << "actuators_cmd_checksum: ";
    Printer<float>::stream(s, indent + "  ", v.actuators_cmd_checksum);
    s << indent << "hornReq: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.hornReq);
    s << indent << "low_beam_cmd: ";
    s << std::endl;
    Printer< ::dbw_pacifica_msgs::LowBeam_<ContainerAllocator> >::stream(s, indent + "  ", v.low_beam_cmd);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DBW_PACIFICA_MSGS_MESSAGE_MISCCMD_H
