(cl:in-package openpilot_bridge-msg)
(cl:export '(HEADER-VAL
          HEADER
          GEARSHIFTER-VAL
          GEARSHIFTER
          SEATBELTUNLATCHED-VAL
          SEATBELTUNLATCHED
          CLUTCHPRESSED-VAL
          CLUTCHPRESSED
          VEGORAW-VAL
          VEGORAW
          ERRORSDEPRECATED-VAL
          ERRORSDEPRECATED
          BRAKE-VAL
          BRAKE
          VEGO-VAL
          VEGO
          STEERINGANGLE-VAL
          STEERINGANGLE
          LEFTBLINKER-VAL
          LEFTBLINKER
          WHEELSPEEDS-VAL
          WHEELSPEEDS
          STEERINGRATELIMITED-VAL
          STEERINGRATELIMITED
          STOCKFCW-VAL
          STOCKFCW
          DOOROPEN-VAL
          DOOROPEN
          STEERINGRATE-VAL
          STEERINGRATE
          EVENTS-VAL
          EVENTS
          STEERINGPRESSED-VAL
          STEERINGPRESSED
          CANVALID-VAL
          CANVALID
          CRUISESTATE-VAL
          CRUISESTATE
          YAWRATE-VAL
          YAWRATE
          STEERINGTORQUEEPS-VAL
          STEERINGTORQUEEPS
          GAS-VAL
          GAS
          STEERINGTORQUE-VAL
          STEERINGTORQUE
          GENERICTOGGLE-VAL
          GENERICTOGGLE
          BRAKELIGHTS-VAL
          BRAKELIGHTS
          BUTTONEVENTS-VAL
          BUTTONEVENTS
          STANDSTILL-VAL
          STANDSTILL
          GASPRESSED-VAL
          GASPRESSED
          STOCKAEB-VAL
          STOCKAEB
          RIGHTBLINKER-VAL
          RIGHTBLINKER
          BRAKEPRESSED-VAL
          BRAKEPRESSED
          AEGO-VAL
          AEGO
          CANMONOTIMES-VAL
          CANMONOTIMES
))