(cl:in-package openpilot_bridge-msg)
(cl:export '(HEADER-VAL
          HEADER
          PITCH-VAL
          PITCH
          POSITIONECEF-VAL
          POSITIONECEF
          ALT-VAL
          ALT
          SPEED-VAL
          SPEED
          LON-VAL
          LON
          SOURCE-VAL
          SOURCE
          ROLL-VAL
          ROLL
          ACCURACY-VAL
          ACCURACY
          STATUS-VAL
          STATUS
          YAWCALIBRATION-VAL
          YAWCALIBRATION
          VNED-VAL
          VNED
          ACCEL-VAL
          ACCEL
          FIXMONOTIME-VAL
          FIXMONOTIME
          LAT-VAL
          LAT
          IMUFRAME-VAL
          IMUFRAME
          PITCHCALIBRATION-VAL
          PITCHCALIBRATION
          GYRO-VAL
          GYRO
          TIMEOFWEEK-VAL
          TIMEOFWEEK
          POSEQUATECEF-VAL
          POSEQUATECEF
          GPSWEEK-VAL
          GPSWEEK
          TRACKANGLE-VAL
          TRACKANGLE
          HEADING-VAL
          HEADING
          WANDERANGLE-VAL
          WANDERANGLE
))