(cl:in-package openpilot_bridge-msg)
(cl:export '(HEADER-VAL
          HEADER
          RADIOVERSION-VAL
          RADIOVERSION
          VERSIONCODENAME-VAL
          VERSIONCODENAME
          HARDWARE-VAL
          HARDWARE
          VERSIONSECURITYPATCH-VAL
          VERSIONSECURITYPATCH
          SUPPORTEDABIS-VAL
          SUPPORTEDABIS
          ID-VAL
          ID
          BOARD-VAL
          BOARD
          TYPE-VAL
          TYPE
          PRODUCT-VAL
          PRODUCT
          TAGS-VAL
          TAGS
          BRAND-VAL
          BRAND
          HOST-VAL
          HOST
          USER-VAL
          USER
          FINGERPRINT-VAL
          FINGERPRINT
          DEVICE-VAL
          DEVICE
          BOOTLOADER-VAL
          BOOTLOADER
          MODEL-VAL
          MODEL
          SERIAL-VAL
          SERIAL
          MANUFACTURER-VAL
          MANUFACTURER
          VERSIONRELEASE-VAL
          VERSIONRELEASE
          TIME-VAL
          TIME
          VERSIONSDK-VAL
          VERSIONSDK
          DISPLAY-VAL
          DISPLAY
))