(cl:in-package openpilot_bridge-msg)
(cl:export '(HEADER-VAL
          HEADER
          XYZN-VAL
          XYZN
          HASSBASIONO-VAL
          HASSBASIONO
          POSITIONUNCERTAINTY-VAL
          POSITIONUNCERTAINTY
          SVID-VAL
          SVID
          ELEVATIONUNCERTAINTY-VAL
          ELEVATIONUNCERTAINTY
          POLYFROMXTRA-VAL
          POLYFROMXTRA
          OTHER-VAL
          OTHER
          IONODOT-VAL
          IONODOT
          HASIONO-VAL
          HASIONO
          FREQUENCYINDEX-VAL
          FREQUENCYINDEX
          VELOCITYCOEFF-VAL
          VELOCITYCOEFF
          ELEVATION-VAL
          ELEVATION
          IONODELAY-VAL
          IONODELAY
          SBASIONODELAY-VAL
          SBASIONODELAY
          HASPOSITION-VAL
          HASPOSITION
          HASELEVATION-VAL
          HASELEVATION
          IODE-VAL
          IODE
          ELEVATIONDOT-VAL
          ELEVATIONDOT
          T0-VAL
          T0
          XYZ0-VAL
          XYZ0
          HASTROPO-VAL
          HASTROPO
          TROPODELAY-VAL
          TROPODELAY
          SBASIONODOT-VAL
          SBASIONODOT
))