(cl:in-package openpilot_bridge-msg)
(cl:export '(HEADER-VAL
          HEADER
          BEARING-VAL
          BEARING
          VNED-VAL
          VNED
          TIMESTAMP-VAL
          TIMESTAMP
          ALTITUDE-VAL
          ALTITUDE
          LONGITUDE-VAL
          LONGITUDE
          SOURCE-VAL
          SOURCE
          SPEEDACCURACY-VAL
          SPEEDACCURACY
          FLAGS-VAL
          FLAGS
          LATITUDE-VAL
          LATITUDE
          BEARINGACCURACY-VAL
          BEARINGACCURACY
          SPEED-VAL
          SPEED
          VERTICALACCURACY-VAL
          VERTICALACCURACY
          ACCURACY-VAL
          ACCURACY
))