(cl:in-package openpilot_bridge-msg)
(cl:export '(HEADER-VAL
          HEADER
          IODC-VAL
          IODC
          FITINTERVAL-VAL
          FITINTERVAL
          MONTH-VAL
          MONTH
          SECOND-VAL
          SECOND
          TGD-VAL
          TGD
          YEAR-VAL
          YEAR
          GPSWEEK-VAL
          GPSWEEK
          CUS-VAL
          CUS
          IONOCOEFFSVALID-VAL
          IONOCOEFFSVALID
          SVID-VAL
          SVID
          SVACC-VAL
          SVACC
          CUC-VAL
          CUC
          M0-VAL
          M0
          TOC-VAL
          TOC
          DELTAN-VAL
          DELTAN
          TOE-VAL
          TOE
          CIC-VAL
          CIC
          IONOBETA-VAL
          IONOBETA
          ECC-VAL
          ECC
          IDOT-VAL
          IDOT
          I0-VAL
          I0
          SVHEALTH-VAL
          SVHEALTH
          CODESL2-VAL
          CODESL2
          OMEGA-VAL
          OMEGA
          DAY-VAL
          DAY
          MINUTE-VAL
          MINUTE
          A-VAL
          A
          CRS-VAL
          CRS
          IONOALPHA-VAL
          IONOALPHA
          HOUR-VAL
          HOUR
          IODE-VAL
          IODE
          AF1-VAL
          AF1
          CIS-VAL
          CIS
          CRC-VAL
          CRC
          L2-VAL
          L2
          OMEGADOT-VAL
          OMEGADOT
          AF0-VAL
          AF0
          OMEGA0-VAL
          OMEGA0
          AF2-VAL
          AF2
          TRANSMISSIONTIME-VAL
          TRANSMISSIONTIME
))