(cl:in-package openpilot_bridge-msg)
(cl:export '(HEADER-VAL
          HEADER
          BATTERYVOLTAGE-VAL
          BATTERYVOLTAGE
          CHARGINGERROR-VAL
          CHARGINGERROR
          CPUPERC-VAL
          CPUPERC
          CHARGINGDISABLED-VAL
          CHARGINGDISABLED
          FANSPEED-VAL
          FANSPEED
          BATTERYCURRENT-VAL
          BATTERYCURRENT
          STARTED-VAL
          STARTED
          PA0-VAL
          PA0
          BATTERYPERCENT-VAL
          BATTERYPERCENT
          GPU-VAL
          GPU
          THERMALSTATUS-VAL
          THERMALSTATUS
          FREESPACE-VAL
          FREESPACE
          USBONLINE-VAL
          USBONLINE
          MEM-VAL
          MEM
          CPU2-VAL
          CPU2
          CPU3-VAL
          CPU3
          CPU0-VAL
          CPU0
          CPU1-VAL
          CPU1
          STARTEDTS-VAL
          STARTEDTS
          BATTERYSTATUS-VAL
          BATTERYSTATUS
          MEMUSEDPERCENT-VAL
          MEMUSEDPERCENT
          BAT-VAL
          BAT
))