(cl:in-package openpilot_bridge-msg)
(cl:export '(HEADER-VAL
          HEADER
          DREL-VAL
          DREL
          YREL-VAL
          YREL
          VREL-VAL
          VREL
          AREL-VAL
          AREL
          VLEAD-VAL
          VLEAD
          ALEADDEPRECATED-VAL
          ALEADDEPRECATED
          DPATH-VAL
          DPATH
          VLAT-VAL
          VLAT
          VLEADK-VAL
          VLEADK
          ALEADK-VAL
          ALEADK
          FCW-VAL
          FCW
          STATUS-VAL
          STATUS
          ALEADTAU-VAL
          ALEADTAU
          MODELPROB-VAL
          MODELPROB
          RADAR-VAL
          RADAR
))