(cl:in-package openpilot_bridge-msg)
(cl:export '(HEADER-VAL
          HEADER
          EXE-VAL
          EXE
          NAME-VAL
          NAME
          CMDLINE-VAL
          CMDLINE
          CPUUSER-VAL
          CPUUSER
          NUMTHREADS-VAL
          NUMTHREADS
          MEMRSS-VAL
          MEMRSS
          PID-VAL
          PID
          MEMVMS-VAL
          MEMVMS
          PRIORITY-VAL
          PRIORITY
          CPUSYSTEM-VAL
          CPUSYSTEM
          STATE-VAL
          STATE
          STARTTIME-VAL
          STARTTIME
          NICE-VAL
          NICE
          CPUCHILDRENUSER-VAL
          CPUCHILDRENUSER
          PPID-VAL
          PPID
          PROCESSOR-VAL
          PROCESSOR
          CPUCHILDRENSYSTEM-VAL
          CPUCHILDRENSYSTEM
))