(cl:in-package openpilot_bridge-msg)
(cl:export '(HEADER-VAL
          HEADER
          INTEGLINES-VAL
          INTEGLINES
          FRAMELENGTH-VAL
          FRAMELENGTH
          TIMESTAMPSOF-VAL
          TIMESTAMPSOF
          LENSTRUEPOS-VAL
          LENSTRUEPOS
          TIMESTAMPEOF-VAL
          TIMESTAMPEOF
          TRANSFORM-VAL
          TRANSFORM
          FRAMEID-VAL
          FRAMEID
          ENCODEID-VAL
          ENCODEID
          ANDROIDCAPTURERESULT-VAL
          ANDROIDCAPTURERESULT
          GAINFRAC-VAL
          GAINFRAC
          LENSSAG-VAL
          LENSSAG
          GLOBALGAIN-VAL
          GLOBALGAIN
          LENSERR-VAL
          LENSERR
          IMAGE-VAL
          IMAGE
          FRAMETYPE-VAL
          FRAMETYPE
          LENSPOS-VAL
          LENSPOS
))