(cl:in-package openpilot_bridge-msg)
(cl:export '(HEADER-VAL
          HEADER
          KERNELVERSION-VAL
          KERNELVERSION
          CHFFRANDROIDEXTRA-VAL
          CHFFRANDROIDEXTRA
          ANDROIDPROPERTIES-VAL
          ANDROIDPROPERTIES
          ANDROIDSENSORS-VAL
          ANDROIDSENSORS
          PANDAINFO-VAL
          PANDAINFO
          IOSBUILDINFO-VAL
          IOSBUILDINFO
          GITREMOTE-VAL
          GITREMOTE
          ANDROIDBUILDINFO-VAL
          ANDROIDBUILDINFO
          PASSIVE-VAL
          PASSIVE
          PARAMS-VAL
          PARAMS
          VERSION-VAL
          VERSION
          DEVICETYPE-VAL
          DEVICETYPE
          KERNELARGS-VAL
          KERNELARGS
          GITCOMMIT-VAL
          GITCOMMIT
          GITBRANCH-VAL
          GITBRANCH
          DONGLEID-VAL
          DONGLEID
          GCTX-VAL
          GCTX
          DIRTY-VAL
          DIRTY
))