(cl:in-package openpilot_bridge-msg)
(cl:export '(HEADER-VAL
          HEADER
          IS80211MCRESPONDER-VAL
          IS80211MCRESPONDER
          OPERATORFRIENDLYNAME-VAL
          OPERATORFRIENDLYNAME
          CHANNELWIDTH-VAL
          CHANNELWIDTH
          DISTANCESDCM-VAL
          DISTANCESDCM
          SSID-VAL
          SSID
          BSSID-VAL
          BSSID
          LEVEL-VAL
          LEVEL
          TIMESTAMP-VAL
          TIMESTAMP
          CAPABILITIES-VAL
          CAPABILITIES
          DISTANCECM-VAL
          DISTANCECM
          CENTERFREQ0-VAL
          CENTERFREQ0
          CENTERFREQ1-VAL
          CENTERFREQ1
          FREQUENCY-VAL
          FREQUENCY
          PASSPOINT-VAL
          PASSPOINT
          VENUENAME-VAL
          VENUENAME
))