(cl:in-package openpilot_bridge-msg)
(cl:export '(HEADER-VAL
          HEADER
          VNEDERROR-VAL
          VNEDERROR
          ROLLERROR-VAL
          ROLLERROR
          HEADINGERROR-VAL
          HEADINGERROR
          ELLIPSOIDSEMIMAJORERROR-VAL
          ELLIPSOIDSEMIMAJORERROR
          ELLIPSOIDORIENTATIONERROR-VAL
          ELLIPSOIDORIENTATIONERROR
          PNEDERROR-VAL
          PNEDERROR
          ELLIPSOIDSEMIMINORERROR-VAL
          ELLIPSOIDSEMIMINORERROR
          PITCHERROR-VAL
          PITCHERROR
))