(cl:in-package openpilot_bridge-msg)
(cl:export '(HEADER-VAL
          HEADER
          EXPOSURETIME-VAL
          EXPOSURETIME
          DISPLAYROTATION-VAL
          DISPLAYROTATION
          COLORCORRECTIONGAINS-VAL
          COLORCORRECTIONGAINS
          SENSITIVITY-VAL
          SENSITIVITY
          ROLLINGSHUTTERSKEW-VAL
          ROLLINGSHUTTERSKEW
          COLORCORRECTIONTRANSFORM-VAL
          COLORCORRECTIONTRANSFORM
          FRAMEDURATION-VAL
          FRAMEDURATION
))