(cl:in-package openpilot_bridge-msg)
(cl:export '(HEADER-VAL
          HEADER
          GNSSID-VAL
          GNSSID
          CARRIERPHASESTDEV-VAL
          CARRIERPHASESTDEV
          PSEUDORANGE-VAL
          PSEUDORANGE
          DOPPLER-VAL
          DOPPLER
          SIGID-VAL
          SIGID
          SVID-VAL
          SVID
          CARRIERCYCLES-VAL
          CARRIERCYCLES
          DOPPLERSTDEV-VAL
          DOPPLERSTDEV
          PSEUDORANGESTDEV-VAL
          PSEUDORANGESTDEV
          CNO-VAL
          CNO
          LOCKTIME-VAL
          LOCKTIME
          GLONASSFREQUENCYINDEX-VAL
          GLONASSFREQUENCYINDEX
          TRACKINGSTATUS-VAL
          TRACKINGSTATUS
))