(cl:in-package openpilot_bridge-msg)
(cl:export '(HEADER-VAL
          HEADER
          ACCELERATION-VAL
          ACCELERATION
          GYROUNCALIBRATED-VAL
          GYROUNCALIBRATED
          LIGHT-VAL
          LIGHT
          ORIENTATION-VAL
          ORIENTATION
          PRESSURE-VAL
          PRESSURE
          SENSOR-VAL
          SENSOR
          MAGNETIC-VAL
          MAGNETIC
          MAGNETICUNCALIBRATED-VAL
          MAGNETICUNCALIBRATED
          SOURCE-VAL
          SOURCE
          GYRO-VAL
          GYRO
          VERSION-VAL
          VERSION
          TIMESTAMP-VAL
          TIMESTAMP
          TYPE-VAL
          TYPE
          PROXIMITY-VAL
          PROXIMITY
          UNCALIBRATEDDEPRECATED-VAL
          UNCALIBRATEDDEPRECATED
))