(cl:in-package openpilot_bridge-msg)
(cl:export '(HEADER-VAL
          HEADER
          MAXRANGE-VAL
          MAXRANGE
          STRINGTYPE-VAL
          STRINGTYPE
          MAXDELAY-VAL
          MAXDELAY
          HANDLE-VAL
          HANDLE
          NAME-VAL
          NAME
          POWER-VAL
          POWER
          MINDELAY-VAL
          MINDELAY
          RESOLUTION-VAL
          RESOLUTION
          FIFOMAXEVENTCOUNT-VAL
          FIFOMAXEVENTCOUNT
          VERSION-VAL
          VERSION
          FIFORESERVEDEVENTCOUNT-VAL
          FIFORESERVEDEVENTCOUNT
          VENDOR-VAL
          VENDOR
          TYPE-VAL
          TYPE
          ID-VAL
          ID
))