(cl:in-package route_mission_handler-msg)
(cl:export '(ID-VAL
          ID
          POSITIVELANENUM-VAL
          POSITIVELANENUM
          NEGATIVELANENUM-VAL
          NEGATIVELANENUM
          TWOWAY-VAL
          TWOWAY
          POSITIVELANEIDS-VAL
          POSITIVELANEIDS
          NEGATIVELANEIDS-VAL
          NEGATIVELANEIDS
          MODE-VAL
          MODE
          R_CLASS-VAL
          R_CLASS
          ROUTING-VAL
          ROUTING
          N_AS-VAL
          N_AS
          N_KPH-VAL
          N_KPH
          P_AS-VAL
          P_AS
          P_KPH-VAL
          P_KPH
          LENGTH-VAL
          LENGTH
          POINTS-VAL
          POINTS
          HEADS-VAL
          HEADS
          TAILS-VAL
          TAILS
          TYPE-VAL
          TYPE
))