(cl:in-package route_mission_handler-msg)
(cl:export '(LANE_ID-VAL
          LANE_ID
          POINT_ID-VAL
          POINT_ID
          NROAD_ID-VAL
          NROAD_ID
          ROADWIDTH-VAL
          ROADWIDTH
          DISTTORIGHTLINE-VAL
          DISTTORIGHTLINE
          DISTTOLEFTLINE-VAL
          DISTTOLEFTLINE
          RIGHT_ROAD_BOUND-VAL
          RIGHT_ROAD_BOUND
          LEFT_ROAD_BOUND-VAL
          LEFT_ROAD_BOUND
          CURVATURE-VAL
          CURVATURE
          HEADING-VAL
          HEADING
          POINT-VAL
          POINT
          MARKERIDS-VAL
          MARKERIDS
          MARKERTYPES-VAL
          MARKERTYPES
          PARKINGLOTID-VAL
          PARKINGLOTID
          PARKINGLOTLANEID-VAL
          PARKINGLOTLANEID
))