# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from route_mission_handler/MarkerPolygon.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import route_mission_handler.msg

class MarkerPolygon(genpy.Message):
  _md5sum = "040152815f20ff5033794b4d0e7f012f"
  _type = "route_mission_handler/MarkerPolygon"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 id
int32 type
int32 navgId
Pair[] pairs
geometry_msgs/Point center_point
geometry_msgs/Point[] corner_points
bool on
string value

================================================================================
MSG: route_mission_handler/Pair
int32 laneId
int32[] pointIds

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['id','type','navgId','pairs','center_point','corner_points','on','value']
  _slot_types = ['int32','int32','int32','route_mission_handler/Pair[]','geometry_msgs/Point','geometry_msgs/Point[]','bool','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,type,navgId,pairs,center_point,corner_points,on,value

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MarkerPolygon, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.type is None:
        self.type = 0
      if self.navgId is None:
        self.navgId = 0
      if self.pairs is None:
        self.pairs = []
      if self.center_point is None:
        self.center_point = geometry_msgs.msg.Point()
      if self.corner_points is None:
        self.corner_points = []
      if self.on is None:
        self.on = False
      if self.value is None:
        self.value = ''
    else:
      self.id = 0
      self.type = 0
      self.navgId = 0
      self.pairs = []
      self.center_point = geometry_msgs.msg.Point()
      self.corner_points = []
      self.on = False
      self.value = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3i().pack(_x.id, _x.type, _x.navgId))
      length = len(self.pairs)
      buff.write(_struct_I.pack(length))
      for val1 in self.pairs:
        _x = val1.laneId
        buff.write(_get_struct_i().pack(_x))
        length = len(val1.pointIds)
        buff.write(_struct_I.pack(length))
        pattern = '<%si'%length
        buff.write(struct.Struct(pattern).pack(*val1.pointIds))
      _x = self
      buff.write(_get_struct_3d().pack(_x.center_point.x, _x.center_point.y, _x.center_point.z))
      length = len(self.corner_points)
      buff.write(_struct_I.pack(length))
      for val1 in self.corner_points:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      _x = self.on
      buff.write(_get_struct_B().pack(_x))
      _x = self.value
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pairs is None:
        self.pairs = None
      if self.center_point is None:
        self.center_point = geometry_msgs.msg.Point()
      if self.corner_points is None:
        self.corner_points = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.id, _x.type, _x.navgId,) = _get_struct_3i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.pairs = []
      for i in range(0, length):
        val1 = route_mission_handler.msg.Pair()
        start = end
        end += 4
        (val1.laneId,) = _get_struct_i().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%si'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.pointIds = s.unpack(str[start:end])
        self.pairs.append(val1)
      _x = self
      start = end
      end += 24
      (_x.center_point.x, _x.center_point.y, _x.center_point.z,) = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.corner_points = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.corner_points.append(val1)
      start = end
      end += 1
      (self.on,) = _get_struct_B().unpack(str[start:end])
      self.on = bool(self.on)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.value = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.value = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3i().pack(_x.id, _x.type, _x.navgId))
      length = len(self.pairs)
      buff.write(_struct_I.pack(length))
      for val1 in self.pairs:
        _x = val1.laneId
        buff.write(_get_struct_i().pack(_x))
        length = len(val1.pointIds)
        buff.write(_struct_I.pack(length))
        pattern = '<%si'%length
        buff.write(val1.pointIds.tostring())
      _x = self
      buff.write(_get_struct_3d().pack(_x.center_point.x, _x.center_point.y, _x.center_point.z))
      length = len(self.corner_points)
      buff.write(_struct_I.pack(length))
      for val1 in self.corner_points:
        _x = val1
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
      _x = self.on
      buff.write(_get_struct_B().pack(_x))
      _x = self.value
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.pairs is None:
        self.pairs = None
      if self.center_point is None:
        self.center_point = geometry_msgs.msg.Point()
      if self.corner_points is None:
        self.corner_points = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.id, _x.type, _x.navgId,) = _get_struct_3i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.pairs = []
      for i in range(0, length):
        val1 = route_mission_handler.msg.Pair()
        start = end
        end += 4
        (val1.laneId,) = _get_struct_i().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%si'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.pointIds = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
        self.pairs.append(val1)
      _x = self
      start = end
      end += 24
      (_x.center_point.x, _x.center_point.y, _x.center_point.z,) = _get_struct_3d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.corner_points = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point()
        _x = val1
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        self.corner_points.append(val1)
      start = end
      end += 1
      (self.on,) = _get_struct_B().unpack(str[start:end])
      self.on = bool(self.on)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.value = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.value = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_3i = None
def _get_struct_3i():
    global _struct_3i
    if _struct_3i is None:
        _struct_3i = struct.Struct("<3i")
    return _struct_3i
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
