# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from route_mission_handler/ObjectsInRange.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import route_mission_handler.msg

class ObjectsInRange(genpy.Message):
  _md5sum = "23414e3f925d00431df85f0ca877074c"
  _type = "route_mission_handler/ObjectsInRange"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """bool changed
geometry_msgs/Polygon range
route_mission_handler/Lanes[] lanes
geometry_msgs/Polygon[] objects

================================================================================
MSG: geometry_msgs/Polygon
#A specification of a polygon where the first and last points are assumed to be connected
Point32[] points

================================================================================
MSG: geometry_msgs/Point32
# This contains the position of a point in free space(with 32 bits of precision).
# It is recommeded to use Point wherever possible instead of Point32.  
# 
# This recommendation is to promote interoperability.  
#
# This message is designed to take up less space when sending
# lots of points at once, as in the case of a PointCloud.  

float32 x
float32 y
float32 z
================================================================================
MSG: route_mission_handler/Lanes
int32 type
int32 NORMAL=0
int32 SPLIT_LEFT=1
int32 SPLIT_RIGHT=2
int32 MERGE_TO_RIGHT=3
int32 MERGE_TO_LEFT=4
int32 TOBE_MERGED=5
int32 SPLIT_STRAIGHT=6

int32 id
bool isTurn
bool direction
int32 laneno
int32[] nexts
int32[] roadLineIds
Waypoints[] points
int32 max_speed_limit
int32 roadType

================================================================================
MSG: route_mission_handler/Waypoints
int32 laneId
int32 pointId
float32 roadWidth
float32 distToRightLine
float32 distToLeftLine
float32 right_road_bound
float32 left_road_bound
float32 curve
float32 slope
float32 bank_angle
geometry_msgs/Pose pose
int32[] markerIds
int32[] markerTypes

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['changed','range','lanes','objects']
  _slot_types = ['bool','geometry_msgs/Polygon','route_mission_handler/Lanes[]','geometry_msgs/Polygon[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       changed,range,lanes,objects

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ObjectsInRange, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.changed is None:
        self.changed = False
      if self.range is None:
        self.range = geometry_msgs.msg.Polygon()
      if self.lanes is None:
        self.lanes = []
      if self.objects is None:
        self.objects = []
    else:
      self.changed = False
      self.range = geometry_msgs.msg.Polygon()
      self.lanes = []
      self.objects = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.changed
      buff.write(_get_struct_B().pack(_x))
      length = len(self.range.points)
      buff.write(_struct_I.pack(length))
      for val1 in self.range.points:
        _x = val1
        buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
      length = len(self.lanes)
      buff.write(_struct_I.pack(length))
      for val1 in self.lanes:
        _x = val1
        buff.write(_get_struct_2i2Bi().pack(_x.type, _x.id, _x.isTurn, _x.direction, _x.laneno))
        length = len(val1.nexts)
        buff.write(_struct_I.pack(length))
        pattern = '<%si'%length
        buff.write(struct.Struct(pattern).pack(*val1.nexts))
        length = len(val1.roadLineIds)
        buff.write(_struct_I.pack(length))
        pattern = '<%si'%length
        buff.write(struct.Struct(pattern).pack(*val1.roadLineIds))
        length = len(val1.points)
        buff.write(_struct_I.pack(length))
        for val2 in val1.points:
          _x = val2
          buff.write(_get_struct_2i8f().pack(_x.laneId, _x.pointId, _x.roadWidth, _x.distToRightLine, _x.distToLeftLine, _x.right_road_bound, _x.left_road_bound, _x.curve, _x.slope, _x.bank_angle))
          _v1 = val2.pose
          _v2 = _v1.position
          _x = _v2
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _v3 = _v1.orientation
          _x = _v3
          buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
          length = len(val2.markerIds)
          buff.write(_struct_I.pack(length))
          pattern = '<%si'%length
          buff.write(struct.Struct(pattern).pack(*val2.markerIds))
          length = len(val2.markerTypes)
          buff.write(_struct_I.pack(length))
          pattern = '<%si'%length
          buff.write(struct.Struct(pattern).pack(*val2.markerTypes))
        _x = val1
        buff.write(_get_struct_2i().pack(_x.max_speed_limit, _x.roadType))
      length = len(self.objects)
      buff.write(_struct_I.pack(length))
      for val1 in self.objects:
        length = len(val1.points)
        buff.write(_struct_I.pack(length))
        for val2 in val1.points:
          _x = val2
          buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.range is None:
        self.range = geometry_msgs.msg.Polygon()
      if self.lanes is None:
        self.lanes = None
      if self.objects is None:
        self.objects = None
      end = 0
      start = end
      end += 1
      (self.changed,) = _get_struct_B().unpack(str[start:end])
      self.changed = bool(self.changed)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.range.points = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point32()
        _x = val1
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
        self.range.points.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.lanes = []
      for i in range(0, length):
        val1 = route_mission_handler.msg.Lanes()
        _x = val1
        start = end
        end += 14
        (_x.type, _x.id, _x.isTurn, _x.direction, _x.laneno,) = _get_struct_2i2Bi().unpack(str[start:end])
        val1.isTurn = bool(val1.isTurn)
        val1.direction = bool(val1.direction)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%si'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.nexts = s.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%si'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.roadLineIds = s.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.points = []
        for i in range(0, length):
          val2 = route_mission_handler.msg.Waypoints()
          _x = val2
          start = end
          end += 40
          (_x.laneId, _x.pointId, _x.roadWidth, _x.distToRightLine, _x.distToLeftLine, _x.right_road_bound, _x.left_road_bound, _x.curve, _x.slope, _x.bank_angle,) = _get_struct_2i8f().unpack(str[start:end])
          _v4 = val2.pose
          _v5 = _v4.position
          _x = _v5
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          _v6 = _v4.orientation
          _x = _v6
          start = end
          end += 32
          (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          pattern = '<%si'%length
          start = end
          s = struct.Struct(pattern)
          end += s.size
          val2.markerIds = s.unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          pattern = '<%si'%length
          start = end
          s = struct.Struct(pattern)
          end += s.size
          val2.markerTypes = s.unpack(str[start:end])
          val1.points.append(val2)
        _x = val1
        start = end
        end += 8
        (_x.max_speed_limit, _x.roadType,) = _get_struct_2i().unpack(str[start:end])
        self.lanes.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.objects = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Polygon()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.points = []
        for i in range(0, length):
          val2 = geometry_msgs.msg.Point32()
          _x = val2
          start = end
          end += 12
          (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
          val1.points.append(val2)
        self.objects.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.changed
      buff.write(_get_struct_B().pack(_x))
      length = len(self.range.points)
      buff.write(_struct_I.pack(length))
      for val1 in self.range.points:
        _x = val1
        buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
      length = len(self.lanes)
      buff.write(_struct_I.pack(length))
      for val1 in self.lanes:
        _x = val1
        buff.write(_get_struct_2i2Bi().pack(_x.type, _x.id, _x.isTurn, _x.direction, _x.laneno))
        length = len(val1.nexts)
        buff.write(_struct_I.pack(length))
        pattern = '<%si'%length
        buff.write(val1.nexts.tostring())
        length = len(val1.roadLineIds)
        buff.write(_struct_I.pack(length))
        pattern = '<%si'%length
        buff.write(val1.roadLineIds.tostring())
        length = len(val1.points)
        buff.write(_struct_I.pack(length))
        for val2 in val1.points:
          _x = val2
          buff.write(_get_struct_2i8f().pack(_x.laneId, _x.pointId, _x.roadWidth, _x.distToRightLine, _x.distToLeftLine, _x.right_road_bound, _x.left_road_bound, _x.curve, _x.slope, _x.bank_angle))
          _v7 = val2.pose
          _v8 = _v7.position
          _x = _v8
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _v9 = _v7.orientation
          _x = _v9
          buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
          length = len(val2.markerIds)
          buff.write(_struct_I.pack(length))
          pattern = '<%si'%length
          buff.write(val2.markerIds.tostring())
          length = len(val2.markerTypes)
          buff.write(_struct_I.pack(length))
          pattern = '<%si'%length
          buff.write(val2.markerTypes.tostring())
        _x = val1
        buff.write(_get_struct_2i().pack(_x.max_speed_limit, _x.roadType))
      length = len(self.objects)
      buff.write(_struct_I.pack(length))
      for val1 in self.objects:
        length = len(val1.points)
        buff.write(_struct_I.pack(length))
        for val2 in val1.points:
          _x = val2
          buff.write(_get_struct_3f().pack(_x.x, _x.y, _x.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.range is None:
        self.range = geometry_msgs.msg.Polygon()
      if self.lanes is None:
        self.lanes = None
      if self.objects is None:
        self.objects = None
      end = 0
      start = end
      end += 1
      (self.changed,) = _get_struct_B().unpack(str[start:end])
      self.changed = bool(self.changed)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.range.points = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Point32()
        _x = val1
        start = end
        end += 12
        (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
        self.range.points.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.lanes = []
      for i in range(0, length):
        val1 = route_mission_handler.msg.Lanes()
        _x = val1
        start = end
        end += 14
        (_x.type, _x.id, _x.isTurn, _x.direction, _x.laneno,) = _get_struct_2i2Bi().unpack(str[start:end])
        val1.isTurn = bool(val1.isTurn)
        val1.direction = bool(val1.direction)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%si'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.nexts = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%si'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.roadLineIds = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.points = []
        for i in range(0, length):
          val2 = route_mission_handler.msg.Waypoints()
          _x = val2
          start = end
          end += 40
          (_x.laneId, _x.pointId, _x.roadWidth, _x.distToRightLine, _x.distToLeftLine, _x.right_road_bound, _x.left_road_bound, _x.curve, _x.slope, _x.bank_angle,) = _get_struct_2i8f().unpack(str[start:end])
          _v10 = val2.pose
          _v11 = _v10.position
          _x = _v11
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          _v12 = _v10.orientation
          _x = _v12
          start = end
          end += 32
          (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          pattern = '<%si'%length
          start = end
          s = struct.Struct(pattern)
          end += s.size
          val2.markerIds = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          pattern = '<%si'%length
          start = end
          s = struct.Struct(pattern)
          end += s.size
          val2.markerTypes = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
          val1.points.append(val2)
        _x = val1
        start = end
        end += 8
        (_x.max_speed_limit, _x.roadType,) = _get_struct_2i().unpack(str[start:end])
        self.lanes.append(val1)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.objects = []
      for i in range(0, length):
        val1 = geometry_msgs.msg.Polygon()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.points = []
        for i in range(0, length):
          val2 = geometry_msgs.msg.Point32()
          _x = val2
          start = end
          end += 12
          (_x.x, _x.y, _x.z,) = _get_struct_3f().unpack(str[start:end])
          val1.points.append(val2)
        self.objects.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2i = None
def _get_struct_2i():
    global _struct_2i
    if _struct_2i is None:
        _struct_2i = struct.Struct("<2i")
    return _struct_2i
_struct_2i2Bi = None
def _get_struct_2i2Bi():
    global _struct_2i2Bi
    if _struct_2i2Bi is None:
        _struct_2i2Bi = struct.Struct("<2i2Bi")
    return _struct_2i2Bi
_struct_2i8f = None
def _get_struct_2i8f():
    global _struct_2i8f
    if _struct_2i8f is None:
        _struct_2i8f = struct.Struct("<2i8f")
    return _struct_2i8f
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
