version: "3"

services:
  payload:
    build:
      context: ./server/payload
    restart: unless-stopped
    env_file: .env
    volumes:
      - ${HOST_DATA_MOUNT_PATH}/uploads:/data/uploads
    ports:
      - 3000:3000
    depends_on:
      - mongo
    command: ["node", "dist/server.js"]

  mongo:
    image: mongo:7.0.8
    env_file: .env
    volumes:
      - ${HOST_DATA_MOUNT_PATH}/db:/data/db
    logging:
      driver: none
    # ports:
    #   - 27017:27017
    command:
      - --storageEngine=wiredTiger

  # analysis:
  #   build:
  #     context: ./server/payload/extensions/analysis
  #   restart: unless-stopped
  #   env_file: .env
  #   ports:
  #     - 9000:8001
  #   command:
  #     ["litestar", "run", "--debug", "--host", "0.0.0.0", "--port", "8001"]

  sampling:
    profiles: ["sampling"]
    build:
      context: ./server/scenario_search/sampling
    restart: unless-stopped
    env_file: .env
    ports:
      - ${HOST_SAMPLING_PORT}:8000
    command:
      [
        "conda",
        "run",
        "--no-capture-output",
        "-n",
        "sampling",
        "litestar",
        "run",
        "--debug",
        "--host",
        "0.0.0.0",
      ]
