#!/bin/bash

# Add aliases you would like to use inside the container here.

source /opt/ros/melodic/setup.bash
export HOME_DIR="$SDC_CONFIG_DIR/machines/$HOSTNAME"

# Sourcing Aliases
alias sw="source /repository/ros/install/setup.bash"
alias ss="source /project/mmsl_simulation/devel/setup.bash"
alias psw="sw;ss"

# cd Aliases
alias cdp="cd /project"
alias cds="cd /project/mmsl_simulation/"
alias cdw="cd /repository/ros"

# Compile Aliases
alias cm="time catkin_make"

# Command Aliases
alias run="psw; roslaunch sdc run.launch"

# ROS Master Settings
function rmp(){
    default_port=11311
    port=$(($1+$default_port))
    export ROS_MASTER_URI="http://localhost:$port"
    alias roslaunch="roslaunch -p $port"
    alias roscore="roscore -p $port"
    echo "ROS_MASTER_URI: $ROS_MASTER_URI"
}
