<?xml version="1.0"?>
<package format="2">
  <name>path</name>
  <version>0.0.1</version>
  <description>The path package</description>
  <maintainer email="chenhuihu@itri.org.tw">user</maintainer>
  <license>ITRI</license>
  <buildtool_depend>catkin</buildtool_depend>
  <depend>geometry_msgs</depend>
  <depend>roscpp</depend>
  <depend>std_msgs</depend>
  <depend>message_generation</depend>
  <depend>simulation_utils</depend>
  <depend>path_msgs</depend>
  <depend>route_mission_handler</depend>
  <export>
  </export>
</package>
