version: '3'

services:
  payload:
    build:
      context: ./
      target: prod
    restart: unless-stopped
    ports:
      - '3007:3000'
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - /mnt/hdd/gpl-odd-data/uploads:/data/uploads

  postgres:
    restart: always
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: payloadpass
      POSTGRES_DB: payloaddb
    volumes:
      - /mnt/hdd/gpl-odd-data/data:/var/lib/postgresql/data
    # ports:
    #   - '5433:5432'
