services:
  payload:
    build:
      context: ./
      target: prod
    restart: unless-stopped
    ports:
      - '3020:3000'
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - "${HOST_DATA_MOUNT_PATH}/uploads:/data/uploads"

  postgres:
    restart: always
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: payloadpass
      POSTGRES_DB: payloaddb
    volumes:
      - "${HOST_DATA_MOUNT_PATH}/data:/var/lib/postgresql/data"
    # ports:
    #   - '5433:5432'
