# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from itri_msgs/EsrDetection.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class EsrDetection(genpy.Message):
  _md5sum = "3accabc22902f1ec54cb36c33644a9c0"
  _type = "itri_msgs/EsrDetection"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header
uint8 path_id_acc_stat
uint8 path_id_acc
uint8 path_id_cmbb_move
uint8 path_id_cmbb_stat
uint8 path_id_fcw_move
uint8 path_id_fcw_stat
uint8 water_spray_target_id
float32 filtered_xohp_acc_cipv
uint8 path_id_acc_2
uint8 path_id_acc_3
bool lr_only_grating_lobe_det
bool truck_target_det

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','path_id_acc_stat','path_id_acc','path_id_cmbb_move','path_id_cmbb_stat','path_id_fcw_move','path_id_fcw_stat','water_spray_target_id','filtered_xohp_acc_cipv','path_id_acc_2','path_id_acc_3','lr_only_grating_lobe_det','truck_target_det']
  _slot_types = ['std_msgs/Header','uint8','uint8','uint8','uint8','uint8','uint8','uint8','float32','uint8','uint8','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,path_id_acc_stat,path_id_acc,path_id_cmbb_move,path_id_cmbb_stat,path_id_fcw_move,path_id_fcw_stat,water_spray_target_id,filtered_xohp_acc_cipv,path_id_acc_2,path_id_acc_3,lr_only_grating_lobe_det,truck_target_det

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(EsrDetection, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.path_id_acc_stat is None:
        self.path_id_acc_stat = 0
      if self.path_id_acc is None:
        self.path_id_acc = 0
      if self.path_id_cmbb_move is None:
        self.path_id_cmbb_move = 0
      if self.path_id_cmbb_stat is None:
        self.path_id_cmbb_stat = 0
      if self.path_id_fcw_move is None:
        self.path_id_fcw_move = 0
      if self.path_id_fcw_stat is None:
        self.path_id_fcw_stat = 0
      if self.water_spray_target_id is None:
        self.water_spray_target_id = 0
      if self.filtered_xohp_acc_cipv is None:
        self.filtered_xohp_acc_cipv = 0.
      if self.path_id_acc_2 is None:
        self.path_id_acc_2 = 0
      if self.path_id_acc_3 is None:
        self.path_id_acc_3 = 0
      if self.lr_only_grating_lobe_det is None:
        self.lr_only_grating_lobe_det = False
      if self.truck_target_det is None:
        self.truck_target_det = False
    else:
      self.header = std_msgs.msg.Header()
      self.path_id_acc_stat = 0
      self.path_id_acc = 0
      self.path_id_cmbb_move = 0
      self.path_id_cmbb_stat = 0
      self.path_id_fcw_move = 0
      self.path_id_fcw_stat = 0
      self.water_spray_target_id = 0
      self.filtered_xohp_acc_cipv = 0.
      self.path_id_acc_2 = 0
      self.path_id_acc_3 = 0
      self.lr_only_grating_lobe_det = False
      self.truck_target_det = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7Bf4B().pack(_x.path_id_acc_stat, _x.path_id_acc, _x.path_id_cmbb_move, _x.path_id_cmbb_stat, _x.path_id_fcw_move, _x.path_id_fcw_stat, _x.water_spray_target_id, _x.filtered_xohp_acc_cipv, _x.path_id_acc_2, _x.path_id_acc_3, _x.lr_only_grating_lobe_det, _x.truck_target_det))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 15
      (_x.path_id_acc_stat, _x.path_id_acc, _x.path_id_cmbb_move, _x.path_id_cmbb_stat, _x.path_id_fcw_move, _x.path_id_fcw_stat, _x.water_spray_target_id, _x.filtered_xohp_acc_cipv, _x.path_id_acc_2, _x.path_id_acc_3, _x.lr_only_grating_lobe_det, _x.truck_target_det,) = _get_struct_7Bf4B().unpack(str[start:end])
      self.lr_only_grating_lobe_det = bool(self.lr_only_grating_lobe_det)
      self.truck_target_det = bool(self.truck_target_det)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7Bf4B().pack(_x.path_id_acc_stat, _x.path_id_acc, _x.path_id_cmbb_move, _x.path_id_cmbb_stat, _x.path_id_fcw_move, _x.path_id_fcw_stat, _x.water_spray_target_id, _x.filtered_xohp_acc_cipv, _x.path_id_acc_2, _x.path_id_acc_3, _x.lr_only_grating_lobe_det, _x.truck_target_det))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 15
      (_x.path_id_acc_stat, _x.path_id_acc, _x.path_id_cmbb_move, _x.path_id_cmbb_stat, _x.path_id_fcw_move, _x.path_id_fcw_stat, _x.water_spray_target_id, _x.filtered_xohp_acc_cipv, _x.path_id_acc_2, _x.path_id_acc_3, _x.lr_only_grating_lobe_det, _x.truck_target_det,) = _get_struct_7Bf4B().unpack(str[start:end])
      self.lr_only_grating_lobe_det = bool(self.lr_only_grating_lobe_det)
      self.truck_target_det = bool(self.truck_target_det)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_7Bf4B = None
def _get_struct_7Bf4B():
    global _struct_7Bf4B
    if _struct_7Bf4B is None:
        _struct_7Bf4B = struct.Struct("<7Bf4B")
    return _struct_7Bf4B
