# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from itri_msgs/lane_waypoints_info.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import itri_msgs.msg
import std_msgs.msg

class lane_waypoints_info(genpy.Message):
  _md5sum = "01267141f4f69eaeb661c3d3af07f166"
  _type = "itri_msgs/lane_waypoints_info"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header

lane_info[] point

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: itri_msgs/lane_info
Header header
int32 lane_id   #current lane
int32 lane_num  #total number of lane
float32 lane_width

string[] line_pos

# Right = 'R'
# Left  = 'L'
# Front = 'F'

uint32[] line_type

# EMPTY = 0
# WHITE_DASHED_LINE = 1
# WHITE_SOLID_LINE = 2
# WHITE_DOUBLE_LINE = 3
# YELLOW_DASHED_LINE
# YELLOW_SOLID_LINE
# YELLOW_DOUBLE_LINE
# RED_SOLID_LINE
# STRAIGHT_ARROW
# TURN_LEFT_ARROW
# TURN_RIGHT_ARROW
# STRAIGHT_OR_RIGHT_ARROW
# STRAIGHT_OR_LEFT_ARROW
# TURN_RIGHT_ONLY
# STOP_LINE
# LONGER_BUMP
# SHORTER_BUMP
# SLOWDOWN
# YIELD
# STOP_SIGN
# SPEED_LIMIT_20KPH
# SPEED_LIMIT_30KPH
# SPEED_LIMIT_50KPH
# SCOOTER_PARKING_PLACE
# PARKING_SPACE

float64 front_line_dis

bool[] on_route_hint
int32[] traffic_stop_line
int32[] bumper
int32[] start_right_turn
int32[] end_right_turn
int32[] start_left_turn
int32[] end_left_turn

Waypoint front_marker_point

StationInfo[] stations
string station_msg

float64 remind_distance
int32 remind_time

int32 turn_type
float64 length_to_turn

================================================================================
MSG: itri_msgs/Waypoint
geometry_msgs/PoseStamped pose
geometry_msgs/TwistStamped twist
int32 laneId
int32 pointId
geometry_msgs/Point point
float32 heading
float32 curvature
float32 speed_limit
int32 point_id
int32 lane_id
int32 nroad_id
float32 s
float32 d
float32 left_space
float32 right_space
float32 width
int32 road_type

================================================================================
MSG: geometry_msgs/PoseStamped
# A Pose with reference coordinate frame and timestamp
Header header
Pose pose

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: geometry_msgs/TwistStamped
# A twist with reference coordinate frame and timestamp
Header header
Twist twist

================================================================================
MSG: geometry_msgs/Twist
# This expresses velocity in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: itri_msgs/StationInfo
string name
bool isPass
Waypoint location
int32 nearPointIndex
"""
  __slots__ = ['header','point']
  _slot_types = ['std_msgs/Header','itri_msgs/lane_info[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,point

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(lane_waypoints_info, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.point is None:
        self.point = []
    else:
      self.header = std_msgs.msg.Header()
      self.point = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.point)
      buff.write(_struct_I.pack(length))
      for val1 in self.point:
        _v1 = val1.header
        _x = _v1.seq
        buff.write(_get_struct_I().pack(_x))
        _v2 = _v1.stamp
        _x = _v2
        buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
        _x = _v1.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_2if().pack(_x.lane_id, _x.lane_num, _x.lane_width))
        length = len(val1.line_pos)
        buff.write(_struct_I.pack(length))
        for val2 in val1.line_pos:
          length = len(val2)
          if python3 or type(val2) == unicode:
            val2 = val2.encode('utf-8')
            length = len(val2)
          buff.write(struct.Struct('<I%ss'%length).pack(length, val2))
        length = len(val1.line_type)
        buff.write(_struct_I.pack(length))
        pattern = '<%sI'%length
        buff.write(struct.Struct(pattern).pack(*val1.line_type))
        _x = val1.front_line_dis
        buff.write(_get_struct_d().pack(_x))
        length = len(val1.on_route_hint)
        buff.write(_struct_I.pack(length))
        pattern = '<%sB'%length
        buff.write(struct.Struct(pattern).pack(*val1.on_route_hint))
        length = len(val1.traffic_stop_line)
        buff.write(_struct_I.pack(length))
        pattern = '<%si'%length
        buff.write(struct.Struct(pattern).pack(*val1.traffic_stop_line))
        length = len(val1.bumper)
        buff.write(_struct_I.pack(length))
        pattern = '<%si'%length
        buff.write(struct.Struct(pattern).pack(*val1.bumper))
        length = len(val1.start_right_turn)
        buff.write(_struct_I.pack(length))
        pattern = '<%si'%length
        buff.write(struct.Struct(pattern).pack(*val1.start_right_turn))
        length = len(val1.end_right_turn)
        buff.write(_struct_I.pack(length))
        pattern = '<%si'%length
        buff.write(struct.Struct(pattern).pack(*val1.end_right_turn))
        length = len(val1.start_left_turn)
        buff.write(_struct_I.pack(length))
        pattern = '<%si'%length
        buff.write(struct.Struct(pattern).pack(*val1.start_left_turn))
        length = len(val1.end_left_turn)
        buff.write(_struct_I.pack(length))
        pattern = '<%si'%length
        buff.write(struct.Struct(pattern).pack(*val1.end_left_turn))
        _v3 = val1.front_marker_point
        _v4 = _v3.pose
        _v5 = _v4.header
        _x = _v5.seq
        buff.write(_get_struct_I().pack(_x))
        _v6 = _v5.stamp
        _x = _v6
        buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
        _x = _v5.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v7 = _v4.pose
        _v8 = _v7.position
        _x = _v8
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v9 = _v7.orientation
        _x = _v9
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
        _v10 = _v3.twist
        _v11 = _v10.header
        _x = _v11.seq
        buff.write(_get_struct_I().pack(_x))
        _v12 = _v11.stamp
        _x = _v12
        buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
        _x = _v11.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v13 = _v10.twist
        _v14 = _v13.linear
        _x = _v14
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v15 = _v13.angular
        _x = _v15
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _x = _v3
        buff.write(_get_struct_2i().pack(_x.laneId, _x.pointId))
        _v16 = _v3.point
        _x = _v16
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _x = _v3
        buff.write(_get_struct_3f3i5fi().pack(_x.heading, _x.curvature, _x.speed_limit, _x.point_id, _x.lane_id, _x.nroad_id, _x.s, _x.d, _x.left_space, _x.right_space, _x.width, _x.road_type))
        length = len(val1.stations)
        buff.write(_struct_I.pack(length))
        for val2 in val1.stations:
          _x = val2.name
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val2.isPass
          buff.write(_get_struct_B().pack(_x))
          _v17 = val2.location
          _v18 = _v17.pose
          _v19 = _v18.header
          _x = _v19.seq
          buff.write(_get_struct_I().pack(_x))
          _v20 = _v19.stamp
          _x = _v20
          buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
          _x = _v19.frame_id
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _v21 = _v18.pose
          _v22 = _v21.position
          _x = _v22
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _v23 = _v21.orientation
          _x = _v23
          buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
          _v24 = _v17.twist
          _v25 = _v24.header
          _x = _v25.seq
          buff.write(_get_struct_I().pack(_x))
          _v26 = _v25.stamp
          _x = _v26
          buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
          _x = _v25.frame_id
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _v27 = _v24.twist
          _v28 = _v27.linear
          _x = _v28
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _v29 = _v27.angular
          _x = _v29
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _x = _v17
          buff.write(_get_struct_2i().pack(_x.laneId, _x.pointId))
          _v30 = _v17.point
          _x = _v30
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _x = _v17
          buff.write(_get_struct_3f3i5fi().pack(_x.heading, _x.curvature, _x.speed_limit, _x.point_id, _x.lane_id, _x.nroad_id, _x.s, _x.d, _x.left_space, _x.right_space, _x.width, _x.road_type))
          _x = val2.nearPointIndex
          buff.write(_get_struct_i().pack(_x))
        _x = val1.station_msg
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_d2id().pack(_x.remind_distance, _x.remind_time, _x.turn_type, _x.length_to_turn))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.point is None:
        self.point = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.point = []
      for i in range(0, length):
        val1 = itri_msgs.msg.lane_info()
        _v31 = val1.header
        start = end
        end += 4
        (_v31.seq,) = _get_struct_I().unpack(str[start:end])
        _v32 = _v31.stamp
        _x = _v32
        start = end
        end += 8
        (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v31.frame_id = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v31.frame_id = str[start:end]
        _x = val1
        start = end
        end += 12
        (_x.lane_id, _x.lane_num, _x.lane_width,) = _get_struct_2if().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.line_pos = []
        for i in range(0, length):
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2 = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val2 = str[start:end]
          val1.line_pos.append(val2)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sI'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.line_type = s.unpack(str[start:end])
        start = end
        end += 8
        (val1.front_line_dis,) = _get_struct_d().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sB'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.on_route_hint = s.unpack(str[start:end])
        val1.on_route_hint = list(map(bool, val1.on_route_hint))
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%si'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.traffic_stop_line = s.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%si'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.bumper = s.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%si'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.start_right_turn = s.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%si'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.end_right_turn = s.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%si'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.start_left_turn = s.unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%si'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.end_left_turn = s.unpack(str[start:end])
        _v33 = val1.front_marker_point
        _v34 = _v33.pose
        _v35 = _v34.header
        start = end
        end += 4
        (_v35.seq,) = _get_struct_I().unpack(str[start:end])
        _v36 = _v35.stamp
        _x = _v36
        start = end
        end += 8
        (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v35.frame_id = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v35.frame_id = str[start:end]
        _v37 = _v34.pose
        _v38 = _v37.position
        _x = _v38
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v39 = _v37.orientation
        _x = _v39
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
        _v40 = _v33.twist
        _v41 = _v40.header
        start = end
        end += 4
        (_v41.seq,) = _get_struct_I().unpack(str[start:end])
        _v42 = _v41.stamp
        _x = _v42
        start = end
        end += 8
        (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v41.frame_id = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v41.frame_id = str[start:end]
        _v43 = _v40.twist
        _v44 = _v43.linear
        _x = _v44
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v45 = _v43.angular
        _x = _v45
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _x = _v33
        start = end
        end += 8
        (_x.laneId, _x.pointId,) = _get_struct_2i().unpack(str[start:end])
        _v46 = _v33.point
        _x = _v46
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _x = _v33
        start = end
        end += 48
        (_x.heading, _x.curvature, _x.speed_limit, _x.point_id, _x.lane_id, _x.nroad_id, _x.s, _x.d, _x.left_space, _x.right_space, _x.width, _x.road_type,) = _get_struct_3f3i5fi().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.stations = []
        for i in range(0, length):
          val2 = itri_msgs.msg.StationInfo()
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.name = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val2.name = str[start:end]
          start = end
          end += 1
          (val2.isPass,) = _get_struct_B().unpack(str[start:end])
          val2.isPass = bool(val2.isPass)
          _v47 = val2.location
          _v48 = _v47.pose
          _v49 = _v48.header
          start = end
          end += 4
          (_v49.seq,) = _get_struct_I().unpack(str[start:end])
          _v50 = _v49.stamp
          _x = _v50
          start = end
          end += 8
          (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            _v49.frame_id = str[start:end].decode('utf-8', 'rosmsg')
          else:
            _v49.frame_id = str[start:end]
          _v51 = _v48.pose
          _v52 = _v51.position
          _x = _v52
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          _v53 = _v51.orientation
          _x = _v53
          start = end
          end += 32
          (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
          _v54 = _v47.twist
          _v55 = _v54.header
          start = end
          end += 4
          (_v55.seq,) = _get_struct_I().unpack(str[start:end])
          _v56 = _v55.stamp
          _x = _v56
          start = end
          end += 8
          (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            _v55.frame_id = str[start:end].decode('utf-8', 'rosmsg')
          else:
            _v55.frame_id = str[start:end]
          _v57 = _v54.twist
          _v58 = _v57.linear
          _x = _v58
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          _v59 = _v57.angular
          _x = _v59
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          _x = _v47
          start = end
          end += 8
          (_x.laneId, _x.pointId,) = _get_struct_2i().unpack(str[start:end])
          _v60 = _v47.point
          _x = _v60
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          _x = _v47
          start = end
          end += 48
          (_x.heading, _x.curvature, _x.speed_limit, _x.point_id, _x.lane_id, _x.nroad_id, _x.s, _x.d, _x.left_space, _x.right_space, _x.width, _x.road_type,) = _get_struct_3f3i5fi().unpack(str[start:end])
          start = end
          end += 4
          (val2.nearPointIndex,) = _get_struct_i().unpack(str[start:end])
          val1.stations.append(val2)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.station_msg = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.station_msg = str[start:end]
        _x = val1
        start = end
        end += 24
        (_x.remind_distance, _x.remind_time, _x.turn_type, _x.length_to_turn,) = _get_struct_d2id().unpack(str[start:end])
        self.point.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      length = len(self.point)
      buff.write(_struct_I.pack(length))
      for val1 in self.point:
        _v61 = val1.header
        _x = _v61.seq
        buff.write(_get_struct_I().pack(_x))
        _v62 = _v61.stamp
        _x = _v62
        buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
        _x = _v61.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_2if().pack(_x.lane_id, _x.lane_num, _x.lane_width))
        length = len(val1.line_pos)
        buff.write(_struct_I.pack(length))
        for val2 in val1.line_pos:
          length = len(val2)
          if python3 or type(val2) == unicode:
            val2 = val2.encode('utf-8')
            length = len(val2)
          buff.write(struct.Struct('<I%ss'%length).pack(length, val2))
        length = len(val1.line_type)
        buff.write(_struct_I.pack(length))
        pattern = '<%sI'%length
        buff.write(val1.line_type.tostring())
        _x = val1.front_line_dis
        buff.write(_get_struct_d().pack(_x))
        length = len(val1.on_route_hint)
        buff.write(_struct_I.pack(length))
        pattern = '<%sB'%length
        buff.write(val1.on_route_hint.tostring())
        length = len(val1.traffic_stop_line)
        buff.write(_struct_I.pack(length))
        pattern = '<%si'%length
        buff.write(val1.traffic_stop_line.tostring())
        length = len(val1.bumper)
        buff.write(_struct_I.pack(length))
        pattern = '<%si'%length
        buff.write(val1.bumper.tostring())
        length = len(val1.start_right_turn)
        buff.write(_struct_I.pack(length))
        pattern = '<%si'%length
        buff.write(val1.start_right_turn.tostring())
        length = len(val1.end_right_turn)
        buff.write(_struct_I.pack(length))
        pattern = '<%si'%length
        buff.write(val1.end_right_turn.tostring())
        length = len(val1.start_left_turn)
        buff.write(_struct_I.pack(length))
        pattern = '<%si'%length
        buff.write(val1.start_left_turn.tostring())
        length = len(val1.end_left_turn)
        buff.write(_struct_I.pack(length))
        pattern = '<%si'%length
        buff.write(val1.end_left_turn.tostring())
        _v63 = val1.front_marker_point
        _v64 = _v63.pose
        _v65 = _v64.header
        _x = _v65.seq
        buff.write(_get_struct_I().pack(_x))
        _v66 = _v65.stamp
        _x = _v66
        buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
        _x = _v65.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v67 = _v64.pose
        _v68 = _v67.position
        _x = _v68
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v69 = _v67.orientation
        _x = _v69
        buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
        _v70 = _v63.twist
        _v71 = _v70.header
        _x = _v71.seq
        buff.write(_get_struct_I().pack(_x))
        _v72 = _v71.stamp
        _x = _v72
        buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
        _x = _v71.frame_id
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _v73 = _v70.twist
        _v74 = _v73.linear
        _x = _v74
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _v75 = _v73.angular
        _x = _v75
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _x = _v63
        buff.write(_get_struct_2i().pack(_x.laneId, _x.pointId))
        _v76 = _v63.point
        _x = _v76
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
        _x = _v63
        buff.write(_get_struct_3f3i5fi().pack(_x.heading, _x.curvature, _x.speed_limit, _x.point_id, _x.lane_id, _x.nroad_id, _x.s, _x.d, _x.left_space, _x.right_space, _x.width, _x.road_type))
        length = len(val1.stations)
        buff.write(_struct_I.pack(length))
        for val2 in val1.stations:
          _x = val2.name
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _x = val2.isPass
          buff.write(_get_struct_B().pack(_x))
          _v77 = val2.location
          _v78 = _v77.pose
          _v79 = _v78.header
          _x = _v79.seq
          buff.write(_get_struct_I().pack(_x))
          _v80 = _v79.stamp
          _x = _v80
          buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
          _x = _v79.frame_id
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _v81 = _v78.pose
          _v82 = _v81.position
          _x = _v82
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _v83 = _v81.orientation
          _x = _v83
          buff.write(_get_struct_4d().pack(_x.x, _x.y, _x.z, _x.w))
          _v84 = _v77.twist
          _v85 = _v84.header
          _x = _v85.seq
          buff.write(_get_struct_I().pack(_x))
          _v86 = _v85.stamp
          _x = _v86
          buff.write(_get_struct_2I().pack(_x.secs, _x.nsecs))
          _x = _v85.frame_id
          length = len(_x)
          if python3 or type(_x) == unicode:
            _x = _x.encode('utf-8')
            length = len(_x)
          buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
          _v87 = _v84.twist
          _v88 = _v87.linear
          _x = _v88
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _v89 = _v87.angular
          _x = _v89
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _x = _v77
          buff.write(_get_struct_2i().pack(_x.laneId, _x.pointId))
          _v90 = _v77.point
          _x = _v90
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.z))
          _x = _v77
          buff.write(_get_struct_3f3i5fi().pack(_x.heading, _x.curvature, _x.speed_limit, _x.point_id, _x.lane_id, _x.nroad_id, _x.s, _x.d, _x.left_space, _x.right_space, _x.width, _x.road_type))
          _x = val2.nearPointIndex
          buff.write(_get_struct_i().pack(_x))
        _x = val1.station_msg
        length = len(_x)
        if python3 or type(_x) == unicode:
          _x = _x.encode('utf-8')
          length = len(_x)
        buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
        _x = val1
        buff.write(_get_struct_d2id().pack(_x.remind_distance, _x.remind_time, _x.turn_type, _x.length_to_turn))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.point is None:
        self.point = None
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.point = []
      for i in range(0, length):
        val1 = itri_msgs.msg.lane_info()
        _v91 = val1.header
        start = end
        end += 4
        (_v91.seq,) = _get_struct_I().unpack(str[start:end])
        _v92 = _v91.stamp
        _x = _v92
        start = end
        end += 8
        (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v91.frame_id = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v91.frame_id = str[start:end]
        _x = val1
        start = end
        end += 12
        (_x.lane_id, _x.lane_num, _x.lane_width,) = _get_struct_2if().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.line_pos = []
        for i in range(0, length):
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2 = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val2 = str[start:end]
          val1.line_pos.append(val2)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sI'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.line_type = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=length)
        start = end
        end += 8
        (val1.front_line_dis,) = _get_struct_d().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sB'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.on_route_hint = numpy.frombuffer(str[start:end], dtype=numpy.bool, count=length)
        val1.on_route_hint = list(map(bool, val1.on_route_hint))
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%si'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.traffic_stop_line = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%si'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.bumper = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%si'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.start_right_turn = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%si'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.end_right_turn = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%si'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.start_left_turn = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%si'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.end_left_turn = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=length)
        _v93 = val1.front_marker_point
        _v94 = _v93.pose
        _v95 = _v94.header
        start = end
        end += 4
        (_v95.seq,) = _get_struct_I().unpack(str[start:end])
        _v96 = _v95.stamp
        _x = _v96
        start = end
        end += 8
        (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v95.frame_id = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v95.frame_id = str[start:end]
        _v97 = _v94.pose
        _v98 = _v97.position
        _x = _v98
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v99 = _v97.orientation
        _x = _v99
        start = end
        end += 32
        (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
        _v100 = _v93.twist
        _v101 = _v100.header
        start = end
        end += 4
        (_v101.seq,) = _get_struct_I().unpack(str[start:end])
        _v102 = _v101.stamp
        _x = _v102
        start = end
        end += 8
        (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          _v101.frame_id = str[start:end].decode('utf-8', 'rosmsg')
        else:
          _v101.frame_id = str[start:end]
        _v103 = _v100.twist
        _v104 = _v103.linear
        _x = _v104
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _v105 = _v103.angular
        _x = _v105
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _x = _v93
        start = end
        end += 8
        (_x.laneId, _x.pointId,) = _get_struct_2i().unpack(str[start:end])
        _v106 = _v93.point
        _x = _v106
        start = end
        end += 24
        (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
        _x = _v93
        start = end
        end += 48
        (_x.heading, _x.curvature, _x.speed_limit, _x.point_id, _x.lane_id, _x.nroad_id, _x.s, _x.d, _x.left_space, _x.right_space, _x.width, _x.road_type,) = _get_struct_3f3i5fi().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.stations = []
        for i in range(0, length):
          val2 = itri_msgs.msg.StationInfo()
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            val2.name = str[start:end].decode('utf-8', 'rosmsg')
          else:
            val2.name = str[start:end]
          start = end
          end += 1
          (val2.isPass,) = _get_struct_B().unpack(str[start:end])
          val2.isPass = bool(val2.isPass)
          _v107 = val2.location
          _v108 = _v107.pose
          _v109 = _v108.header
          start = end
          end += 4
          (_v109.seq,) = _get_struct_I().unpack(str[start:end])
          _v110 = _v109.stamp
          _x = _v110
          start = end
          end += 8
          (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            _v109.frame_id = str[start:end].decode('utf-8', 'rosmsg')
          else:
            _v109.frame_id = str[start:end]
          _v111 = _v108.pose
          _v112 = _v111.position
          _x = _v112
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          _v113 = _v111.orientation
          _x = _v113
          start = end
          end += 32
          (_x.x, _x.y, _x.z, _x.w,) = _get_struct_4d().unpack(str[start:end])
          _v114 = _v107.twist
          _v115 = _v114.header
          start = end
          end += 4
          (_v115.seq,) = _get_struct_I().unpack(str[start:end])
          _v116 = _v115.stamp
          _x = _v116
          start = end
          end += 8
          (_x.secs, _x.nsecs,) = _get_struct_2I().unpack(str[start:end])
          start = end
          end += 4
          (length,) = _struct_I.unpack(str[start:end])
          start = end
          end += length
          if python3:
            _v115.frame_id = str[start:end].decode('utf-8', 'rosmsg')
          else:
            _v115.frame_id = str[start:end]
          _v117 = _v114.twist
          _v118 = _v117.linear
          _x = _v118
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          _v119 = _v117.angular
          _x = _v119
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          _x = _v107
          start = end
          end += 8
          (_x.laneId, _x.pointId,) = _get_struct_2i().unpack(str[start:end])
          _v120 = _v107.point
          _x = _v120
          start = end
          end += 24
          (_x.x, _x.y, _x.z,) = _get_struct_3d().unpack(str[start:end])
          _x = _v107
          start = end
          end += 48
          (_x.heading, _x.curvature, _x.speed_limit, _x.point_id, _x.lane_id, _x.nroad_id, _x.s, _x.d, _x.left_space, _x.right_space, _x.width, _x.road_type,) = _get_struct_3f3i5fi().unpack(str[start:end])
          start = end
          end += 4
          (val2.nearPointIndex,) = _get_struct_i().unpack(str[start:end])
          val1.stations.append(val2)
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        start = end
        end += length
        if python3:
          val1.station_msg = str[start:end].decode('utf-8', 'rosmsg')
        else:
          val1.station_msg = str[start:end]
        _x = val1
        start = end
        end += 24
        (_x.remind_distance, _x.remind_time, _x.turn_type, _x.length_to_turn,) = _get_struct_d2id().unpack(str[start:end])
        self.point.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
_struct_2i = None
def _get_struct_2i():
    global _struct_2i
    if _struct_2i is None:
        _struct_2i = struct.Struct("<2i")
    return _struct_2i
_struct_2if = None
def _get_struct_2if():
    global _struct_2if
    if _struct_2if is None:
        _struct_2if = struct.Struct("<2if")
    return _struct_2if
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
_struct_3f3i5fi = None
def _get_struct_3f3i5fi():
    global _struct_3f3i5fi
    if _struct_3f3i5fi is None:
        _struct_3f3i5fi = struct.Struct("<3f3i5fi")
    return _struct_3f3i5fi
_struct_4d = None
def _get_struct_4d():
    global _struct_4d
    if _struct_4d is None:
        _struct_4d = struct.Struct("<4d")
    return _struct_4d
_struct_B = None
def _get_struct_B():
    global _struct_B
    if _struct_B is None:
        _struct_B = struct.Struct("<B")
    return _struct_B
_struct_d = None
def _get_struct_d():
    global _struct_d
    if _struct_d is None:
        _struct_d = struct.Struct("<d")
    return _struct_d
_struct_d2id = None
def _get_struct_d2id():
    global _struct_d2id
    if _struct_d2id is None:
        _struct_d2id = struct.Struct("<d2id")
    return _struct_d2id
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
