# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from itri_msgs/NdtStatistics.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class NdtStatistics(genpy.Message):
  _md5sum = "b21481a49aaae81584b34de5ce8cef65"
  _type = "itri_msgs/NdtStatistics"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header

float32 execution_time
float32 fitness_score
float32 fitness_score_valid
uint32 invalid_points_number
uint32 iteration
float32 map_coverage
float32 matching_score
float32 matching_score_valid
float32 regulate_matching_score
uint32 scan_valid_ratio
uint32 source_points_number
uint32 valid_points_number

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','execution_time','fitness_score','fitness_score_valid','invalid_points_number','iteration','map_coverage','matching_score','matching_score_valid','regulate_matching_score','scan_valid_ratio','source_points_number','valid_points_number']
  _slot_types = ['std_msgs/Header','float32','float32','float32','uint32','uint32','float32','float32','float32','float32','uint32','uint32','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,execution_time,fitness_score,fitness_score_valid,invalid_points_number,iteration,map_coverage,matching_score,matching_score_valid,regulate_matching_score,scan_valid_ratio,source_points_number,valid_points_number

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(NdtStatistics, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.execution_time is None:
        self.execution_time = 0.
      if self.fitness_score is None:
        self.fitness_score = 0.
      if self.fitness_score_valid is None:
        self.fitness_score_valid = 0.
      if self.invalid_points_number is None:
        self.invalid_points_number = 0
      if self.iteration is None:
        self.iteration = 0
      if self.map_coverage is None:
        self.map_coverage = 0.
      if self.matching_score is None:
        self.matching_score = 0.
      if self.matching_score_valid is None:
        self.matching_score_valid = 0.
      if self.regulate_matching_score is None:
        self.regulate_matching_score = 0.
      if self.scan_valid_ratio is None:
        self.scan_valid_ratio = 0
      if self.source_points_number is None:
        self.source_points_number = 0
      if self.valid_points_number is None:
        self.valid_points_number = 0
    else:
      self.header = std_msgs.msg.Header()
      self.execution_time = 0.
      self.fitness_score = 0.
      self.fitness_score_valid = 0.
      self.invalid_points_number = 0
      self.iteration = 0
      self.map_coverage = 0.
      self.matching_score = 0.
      self.matching_score_valid = 0.
      self.regulate_matching_score = 0.
      self.scan_valid_ratio = 0
      self.source_points_number = 0
      self.valid_points_number = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3f2I4f3I().pack(_x.execution_time, _x.fitness_score, _x.fitness_score_valid, _x.invalid_points_number, _x.iteration, _x.map_coverage, _x.matching_score, _x.matching_score_valid, _x.regulate_matching_score, _x.scan_valid_ratio, _x.source_points_number, _x.valid_points_number))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 48
      (_x.execution_time, _x.fitness_score, _x.fitness_score_valid, _x.invalid_points_number, _x.iteration, _x.map_coverage, _x.matching_score, _x.matching_score_valid, _x.regulate_matching_score, _x.scan_valid_ratio, _x.source_points_number, _x.valid_points_number,) = _get_struct_3f2I4f3I().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3f2I4f3I().pack(_x.execution_time, _x.fitness_score, _x.fitness_score_valid, _x.invalid_points_number, _x.iteration, _x.map_coverage, _x.matching_score, _x.matching_score_valid, _x.regulate_matching_score, _x.scan_valid_ratio, _x.source_points_number, _x.valid_points_number))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 48
      (_x.execution_time, _x.fitness_score, _x.fitness_score_valid, _x.invalid_points_number, _x.iteration, _x.map_coverage, _x.matching_score, _x.matching_score_valid, _x.regulate_matching_score, _x.scan_valid_ratio, _x.source_points_number, _x.valid_points_number,) = _get_struct_3f2I4f3I().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3f2I4f3I = None
def _get_struct_3f2I4f3I():
    global _struct_3f2I4f3I
    if _struct_3f2I4f3I is None:
        _struct_3f2I4f3I = struct.Struct("<3f2I4f3I")
    return _struct_3f2I4f3I
