<?xml version="1.0"?>
<package format="2">
  <name>simulation_monitor</name>
  <version>0.0.0</version>
  <description>The simulation_monitor package</description>

  <maintainer email="zackhsu@itri.org.tw">Hsiu-Wei Hsu</maintainer>
  <license>ITRI</license>

  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>geometry_msgs</build_depend>
  <build_depend>message_generation</build_depend>
  <build_depend>message_runtime</build_depend>
  <build_depend>roscpp</build_depend>
  <build_depend>rospy</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>itri_msgs</build_depend>
  <build_depend>rss_msgs</build_depend>
  <build_export_depend>geometry_msgs</build_export_depend>
  <build_export_depend>roscpp</build_export_depend>
  <build_export_depend>rospy</build_export_depend>
  <build_export_depend>std_msgs</build_export_depend>
  <build_export_depend>itri_msgs</build_export_depend>
  <build_export_depend>rss_msgs</build_export_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>message_runtime</exec_depend>
  <exec_depend>roscpp</exec_depend>
  <exec_depend>rospy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>itri_msgs</exec_depend>
  <exec_depend>rss_msgs</exec_depend>
  <depend>route_mission_handler</depend>
  <depend>simulation_msgs</depend>


  <!-- The export tag contains other, unspecified, tags -->
  <export>
    <!-- Other tools can request additional information be placed here -->

  </export>
</package>
