Header header

int32 safetyParam
float32 steerRatioRear
bool enableDsu
Lateraltuning lateralTuning
uint32 steerControlType # enum const: SteerControlType
string[] carFingerprint
float32 rotationalInertia
uint32 safetyModelPassive # enum const: SafetyModel
CarFw[] carFw
float32 minEnableSpeed
bool enableGasInterceptor
bool radarOffCan
float32 steerRatio
float32 vEgoStopping
bool enableCamera
bool enableCruise
float32 tireStiffnessFront
float32 minSteerSpeed
bool stoppingControl
float32 steerLimitTimer
uint32 transmissionType # enum const: TransmissionType
float32[] steerMaxV
bool openpilotLongitudinalControl
float32[] gasMaxBP
bool enableApgs
float32 radarTimeStep
string[] carName
uint32 safetyModel # enum const: SafetyModel
string[] carVin
float32[] steerMaxBP
float32[] gasMaxV
float32 steerRateCost
float32[] brakeMaxV
float32 tireStiffnessRear
float32 centerToFront
bool dashcamOnly
float32 startAccel
float32 wheelbase
float32[] brakeMaxBP
float32 mass
float32 steerActuatorDelay
LongitudinalPIDTuning longitudinalTuning
bool directAccelControl
bool communityFeature
bool isPandaBlack
bool steerLimitAlert
