Header header

uint32 gearShifter # enum const: GearShifter
bool seatbeltUnlatched
bool clutchPressed
float32 vEgoRaw
uint32[] errorsDEPRECATED # enum const: EventName
float32 brake
float32 vEgo
float32 steeringAngle
bool leftBlinker
WheelSpeeds wheelSpeeds
bool steeringRateLimited
bool stockFcw
bool doorOpen
float32 steeringRate
CarEvent[] events
bool steeringPressed
bool canValid
CruiseState cruiseState
float32 yawRate
float32 steeringTorqueEps
float32 gas
float32 steeringTorque
bool genericToggle
bool brakeLights
ButtonEvent[] buttonEvents
bool standstill
bool gasPressed
bool stockAeb
bool rightBlinker
bool brakePressed
float32 aEgo
int64[] canMonoTimes
