Header header

float32 ufSteerDEPRECATED
float32 angleSteersDes
bool decelForTurn
bool steerOverride
bool rearViewCam
int64 canErrorCounter
Lateralcontrolstate lateralControlState
float32 vEgoRaw
bool forceDecel
uint32 alertSound # enum const: AudibleAlert
float32 upSteerDEPRECATED
float32 vEgo
float32 angleSteers
float32 jerkFactor
string[] alertType
float32 aTarget
uint32 alertStatus # enum const: AlertStatus
uint32 alertSize # enum const: AlertSize
int64 planMonoTime
float32 aTargetMaxDEPRECATED
float32 uiAccelCmd
uint32 state # enum const: OpenpilotState
float32 alertBlinkingRate
float32 angleModelBiasDEPRECATED
string[] alertText2
string[] alertText1
float32 yDesDEPRECATED
float32 vPid
float32 vTargetLead
bool decelForModel
bool gpsPlannerActive
int64 startMonoTime
int64 canMonoTimeDEPRECATED
float32 curvature
float32 upAccelCmd
float32 vCurvature
int32 hudLeadDEPRECATED
bool active
float32 awarenessStatus
float32 uiSteerDEPRECATED
float32 aEgoDEPRECATED
string[] alertSoundDEPRECATED
float32 ufAccelCmd
float32 vCruise
float32 yActualDEPRECATED
bool enabled
float32 aTargetMinDEPRECATED
float32 cumLagMs
bool mapValid
int64 pathPlanMonoTime
bool engageable
int64 mdMonoTimeDEPRECATED
bool driverMonitoringOn
int64[] canMonoTimes
int64 radarStateMonoTimeDEPRECATED
uint32 longControlState # enum const: LongControlState
