Header header

bool gasInterceptorDetected
uint32 faultStatus # enum const: FaultStatus
bool hasGps
int64 fanSpeedRpm
bool startedSignalDetectedDeprecated
int64 canRxErrs
uint32[] faults # enum const: FaultType
int64 canFwdErrs
int64 uptime
bool powerSaveEnabled
int64 current
uint32 hwType # enum const: HwType
bool ignitionCan
int64 voltage
int64 canSendErrs
uint32 usbPowerMode # enum const: UsbPowerMode
int64 gmlanSendErrs
bool ignitionLine
uint32 safetyModel # enum const: SafetyModel
bool controlsAllowed
