Header header

string[] kernelVersion
ChffrAndroidExtra chffrAndroidExtra
Map androidProperties
AndroidSensor[] androidSensors
PandaInfo pandaInfo
IosBuildInfo iosBuildInfo
string[] gitRemote
AndroidBuildInfo androidBuildInfo
bool passive
Map params
string[] version
uint32 deviceType # enum const: DeviceType
string[] kernelArgs
string[] gitCommit
string[] gitBranch
string[] dongleId
string[] gctx
bool dirty
