Header header

float32 pitch
float32[] positionECEF
float32 alt
float32 speed
float32 lon
uint32 source # enum const: SensorSource
float32 roll
Accuracy accuracy
int64 status
float32 yawCalibration
float32[] vNED
float32[] accel
int64 fixMonoTime
float32 lat
float32[] imuFrame
float32 pitchCalibration
float32[] gyro
float32 timeOfWeek
float32[] poseQuatECEF
int32 gpsWeek
float32 trackAngle
float32 heading
float32 wanderAngle
