Header header

float32 angleSteers
bool commIssue
float32[] lPoly
uint32 laneChangeState # enum const: LaneChangeState
bool sensorValid
bool mpcSolutionValid
float32 lProb
bool modelValidDEPRECATED
float32 rProb
float32 cProb
float32[] rPoly
float32 laneWidth
float32 angleOffset
float32 rateSteers
uint32 laneChangeDirection # enum const: LaneChangeDirection
bool paramsValid
float32[] cPoly
bool posenetValid
float32[] dPoly
uint32 desire # enum const: Desire
