#!/usr/bin/env python2

import sys

def filter(message):
    buffer = bytes()
    process_star_count = 0
    for line in message.splitlines():
        if len(line) > 0:
            each = line.split()
            if each[0] == 'top':
                process_star_count += 1
        if process_star_count == 2:
            buffer += line + '\n'
    return buffer


def main():
    sys.stdout.write(filter(sys.stdin.read()))

if __name__ == "__main__":
    main()
