# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from openpilot_bridge/HUDControl.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class HUDControl(genpy.Message):
  _md5sum = "fae5883e88a08288a6e7673c35bc1b32"
  _type = "openpilot_bridge/HUDControl"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header

bool leadVisible
float32 setSpeed
bool leftLaneDepart
bool lanesVisible
bool leftLaneVisible
uint32 visualAlert # enum const: VisualAlert
uint32 audibleAlert # enum const: AudibleAlert
bool speedVisible
bool rightLaneVisible
bool rightLaneDepart

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','leadVisible','setSpeed','leftLaneDepart','lanesVisible','leftLaneVisible','visualAlert','audibleAlert','speedVisible','rightLaneVisible','rightLaneDepart']
  _slot_types = ['std_msgs/Header','bool','float32','bool','bool','bool','uint32','uint32','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,leadVisible,setSpeed,leftLaneDepart,lanesVisible,leftLaneVisible,visualAlert,audibleAlert,speedVisible,rightLaneVisible,rightLaneDepart

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(HUDControl, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.leadVisible is None:
        self.leadVisible = False
      if self.setSpeed is None:
        self.setSpeed = 0.
      if self.leftLaneDepart is None:
        self.leftLaneDepart = False
      if self.lanesVisible is None:
        self.lanesVisible = False
      if self.leftLaneVisible is None:
        self.leftLaneVisible = False
      if self.visualAlert is None:
        self.visualAlert = 0
      if self.audibleAlert is None:
        self.audibleAlert = 0
      if self.speedVisible is None:
        self.speedVisible = False
      if self.rightLaneVisible is None:
        self.rightLaneVisible = False
      if self.rightLaneDepart is None:
        self.rightLaneDepart = False
    else:
      self.header = std_msgs.msg.Header()
      self.leadVisible = False
      self.setSpeed = 0.
      self.leftLaneDepart = False
      self.lanesVisible = False
      self.leftLaneVisible = False
      self.visualAlert = 0
      self.audibleAlert = 0
      self.speedVisible = False
      self.rightLaneVisible = False
      self.rightLaneDepart = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_Bf3B2I3B().pack(_x.leadVisible, _x.setSpeed, _x.leftLaneDepart, _x.lanesVisible, _x.leftLaneVisible, _x.visualAlert, _x.audibleAlert, _x.speedVisible, _x.rightLaneVisible, _x.rightLaneDepart))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 19
      (_x.leadVisible, _x.setSpeed, _x.leftLaneDepart, _x.lanesVisible, _x.leftLaneVisible, _x.visualAlert, _x.audibleAlert, _x.speedVisible, _x.rightLaneVisible, _x.rightLaneDepart,) = _get_struct_Bf3B2I3B().unpack(str[start:end])
      self.leadVisible = bool(self.leadVisible)
      self.leftLaneDepart = bool(self.leftLaneDepart)
      self.lanesVisible = bool(self.lanesVisible)
      self.leftLaneVisible = bool(self.leftLaneVisible)
      self.speedVisible = bool(self.speedVisible)
      self.rightLaneVisible = bool(self.rightLaneVisible)
      self.rightLaneDepart = bool(self.rightLaneDepart)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_Bf3B2I3B().pack(_x.leadVisible, _x.setSpeed, _x.leftLaneDepart, _x.lanesVisible, _x.leftLaneVisible, _x.visualAlert, _x.audibleAlert, _x.speedVisible, _x.rightLaneVisible, _x.rightLaneDepart))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 19
      (_x.leadVisible, _x.setSpeed, _x.leftLaneDepart, _x.lanesVisible, _x.leftLaneVisible, _x.visualAlert, _x.audibleAlert, _x.speedVisible, _x.rightLaneVisible, _x.rightLaneDepart,) = _get_struct_Bf3B2I3B().unpack(str[start:end])
      self.leadVisible = bool(self.leadVisible)
      self.leftLaneDepart = bool(self.leftLaneDepart)
      self.lanesVisible = bool(self.lanesVisible)
      self.leftLaneVisible = bool(self.leftLaneVisible)
      self.speedVisible = bool(self.speedVisible)
      self.rightLaneVisible = bool(self.rightLaneVisible)
      self.rightLaneDepart = bool(self.rightLaneDepart)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_Bf3B2I3B = None
def _get_struct_Bf3B2I3B():
    global _struct_Bf3B2I3B
    if _struct_Bf3B2I3B is None:
        _struct_Bf3B2I3B = struct.Struct("<Bf3B2I3B")
    return _struct_Bf3B2I3B
