# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from openpilot_bridge/SensorEventData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import openpilot_bridge.msg
import std_msgs.msg

class SensorEventData(genpy.Message):
  _md5sum = "b716bd78256e63045fe27b6249e4a04a"
  _type = "openpilot_bridge/SensorEventData"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header

SensorVec acceleration
SensorVec gyroUncalibrated
float32 light
SensorVec orientation
SensorVec pressure
int32 sensor
SensorVec magnetic
SensorVec magneticUncalibrated
uint32 source # enum const: SensorSource
SensorVec gyro
int32 version
int32 timestamp
int32 type
float32 proximity
bool uncalibratedDEPRECATED

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: openpilot_bridge/SensorVec
Header header

int32 status
float32[] v
"""
  __slots__ = ['header','acceleration','gyroUncalibrated','light','orientation','pressure','sensor','magnetic','magneticUncalibrated','source','gyro','version','timestamp','type','proximity','uncalibratedDEPRECATED']
  _slot_types = ['std_msgs/Header','openpilot_bridge/SensorVec','openpilot_bridge/SensorVec','float32','openpilot_bridge/SensorVec','openpilot_bridge/SensorVec','int32','openpilot_bridge/SensorVec','openpilot_bridge/SensorVec','uint32','openpilot_bridge/SensorVec','int32','int32','int32','float32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,acceleration,gyroUncalibrated,light,orientation,pressure,sensor,magnetic,magneticUncalibrated,source,gyro,version,timestamp,type,proximity,uncalibratedDEPRECATED

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SensorEventData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.acceleration is None:
        self.acceleration = openpilot_bridge.msg.SensorVec()
      if self.gyroUncalibrated is None:
        self.gyroUncalibrated = openpilot_bridge.msg.SensorVec()
      if self.light is None:
        self.light = 0.
      if self.orientation is None:
        self.orientation = openpilot_bridge.msg.SensorVec()
      if self.pressure is None:
        self.pressure = openpilot_bridge.msg.SensorVec()
      if self.sensor is None:
        self.sensor = 0
      if self.magnetic is None:
        self.magnetic = openpilot_bridge.msg.SensorVec()
      if self.magneticUncalibrated is None:
        self.magneticUncalibrated = openpilot_bridge.msg.SensorVec()
      if self.source is None:
        self.source = 0
      if self.gyro is None:
        self.gyro = openpilot_bridge.msg.SensorVec()
      if self.version is None:
        self.version = 0
      if self.timestamp is None:
        self.timestamp = 0
      if self.type is None:
        self.type = 0
      if self.proximity is None:
        self.proximity = 0.
      if self.uncalibratedDEPRECATED is None:
        self.uncalibratedDEPRECATED = False
    else:
      self.header = std_msgs.msg.Header()
      self.acceleration = openpilot_bridge.msg.SensorVec()
      self.gyroUncalibrated = openpilot_bridge.msg.SensorVec()
      self.light = 0.
      self.orientation = openpilot_bridge.msg.SensorVec()
      self.pressure = openpilot_bridge.msg.SensorVec()
      self.sensor = 0
      self.magnetic = openpilot_bridge.msg.SensorVec()
      self.magneticUncalibrated = openpilot_bridge.msg.SensorVec()
      self.source = 0
      self.gyro = openpilot_bridge.msg.SensorVec()
      self.version = 0
      self.timestamp = 0
      self.type = 0
      self.proximity = 0.
      self.uncalibratedDEPRECATED = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.acceleration.header.seq, _x.acceleration.header.stamp.secs, _x.acceleration.header.stamp.nsecs))
      _x = self.acceleration.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.acceleration.status
      buff.write(_get_struct_i().pack(_x))
      length = len(self.acceleration.v)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.acceleration.v))
      _x = self
      buff.write(_get_struct_3I().pack(_x.gyroUncalibrated.header.seq, _x.gyroUncalibrated.header.stamp.secs, _x.gyroUncalibrated.header.stamp.nsecs))
      _x = self.gyroUncalibrated.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.gyroUncalibrated.status
      buff.write(_get_struct_i().pack(_x))
      length = len(self.gyroUncalibrated.v)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.gyroUncalibrated.v))
      _x = self
      buff.write(_get_struct_f3I().pack(_x.light, _x.orientation.header.seq, _x.orientation.header.stamp.secs, _x.orientation.header.stamp.nsecs))
      _x = self.orientation.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.orientation.status
      buff.write(_get_struct_i().pack(_x))
      length = len(self.orientation.v)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.orientation.v))
      _x = self
      buff.write(_get_struct_3I().pack(_x.pressure.header.seq, _x.pressure.header.stamp.secs, _x.pressure.header.stamp.nsecs))
      _x = self.pressure.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.pressure.status
      buff.write(_get_struct_i().pack(_x))
      length = len(self.pressure.v)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.pressure.v))
      _x = self
      buff.write(_get_struct_i3I().pack(_x.sensor, _x.magnetic.header.seq, _x.magnetic.header.stamp.secs, _x.magnetic.header.stamp.nsecs))
      _x = self.magnetic.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.magnetic.status
      buff.write(_get_struct_i().pack(_x))
      length = len(self.magnetic.v)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.magnetic.v))
      _x = self
      buff.write(_get_struct_3I().pack(_x.magneticUncalibrated.header.seq, _x.magneticUncalibrated.header.stamp.secs, _x.magneticUncalibrated.header.stamp.nsecs))
      _x = self.magneticUncalibrated.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.magneticUncalibrated.status
      buff.write(_get_struct_i().pack(_x))
      length = len(self.magneticUncalibrated.v)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.magneticUncalibrated.v))
      _x = self
      buff.write(_get_struct_4I().pack(_x.source, _x.gyro.header.seq, _x.gyro.header.stamp.secs, _x.gyro.header.stamp.nsecs))
      _x = self.gyro.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.gyro.status
      buff.write(_get_struct_i().pack(_x))
      length = len(self.gyro.v)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(struct.Struct(pattern).pack(*self.gyro.v))
      _x = self
      buff.write(_get_struct_3ifB().pack(_x.version, _x.timestamp, _x.type, _x.proximity, _x.uncalibratedDEPRECATED))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.acceleration is None:
        self.acceleration = openpilot_bridge.msg.SensorVec()
      if self.gyroUncalibrated is None:
        self.gyroUncalibrated = openpilot_bridge.msg.SensorVec()
      if self.orientation is None:
        self.orientation = openpilot_bridge.msg.SensorVec()
      if self.pressure is None:
        self.pressure = openpilot_bridge.msg.SensorVec()
      if self.magnetic is None:
        self.magnetic = openpilot_bridge.msg.SensorVec()
      if self.magneticUncalibrated is None:
        self.magneticUncalibrated = openpilot_bridge.msg.SensorVec()
      if self.gyro is None:
        self.gyro = openpilot_bridge.msg.SensorVec()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.acceleration.header.seq, _x.acceleration.header.stamp.secs, _x.acceleration.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.acceleration.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.acceleration.header.frame_id = str[start:end]
      start = end
      end += 4
      (self.acceleration.status,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.acceleration.v = s.unpack(str[start:end])
      _x = self
      start = end
      end += 12
      (_x.gyroUncalibrated.header.seq, _x.gyroUncalibrated.header.stamp.secs, _x.gyroUncalibrated.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.gyroUncalibrated.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.gyroUncalibrated.header.frame_id = str[start:end]
      start = end
      end += 4
      (self.gyroUncalibrated.status,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.gyroUncalibrated.v = s.unpack(str[start:end])
      _x = self
      start = end
      end += 16
      (_x.light, _x.orientation.header.seq, _x.orientation.header.stamp.secs, _x.orientation.header.stamp.nsecs,) = _get_struct_f3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.orientation.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.orientation.header.frame_id = str[start:end]
      start = end
      end += 4
      (self.orientation.status,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.orientation.v = s.unpack(str[start:end])
      _x = self
      start = end
      end += 12
      (_x.pressure.header.seq, _x.pressure.header.stamp.secs, _x.pressure.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pressure.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.pressure.header.frame_id = str[start:end]
      start = end
      end += 4
      (self.pressure.status,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.pressure.v = s.unpack(str[start:end])
      _x = self
      start = end
      end += 16
      (_x.sensor, _x.magnetic.header.seq, _x.magnetic.header.stamp.secs, _x.magnetic.header.stamp.nsecs,) = _get_struct_i3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.magnetic.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.magnetic.header.frame_id = str[start:end]
      start = end
      end += 4
      (self.magnetic.status,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.magnetic.v = s.unpack(str[start:end])
      _x = self
      start = end
      end += 12
      (_x.magneticUncalibrated.header.seq, _x.magneticUncalibrated.header.stamp.secs, _x.magneticUncalibrated.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.magneticUncalibrated.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.magneticUncalibrated.header.frame_id = str[start:end]
      start = end
      end += 4
      (self.magneticUncalibrated.status,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.magneticUncalibrated.v = s.unpack(str[start:end])
      _x = self
      start = end
      end += 16
      (_x.source, _x.gyro.header.seq, _x.gyro.header.stamp.secs, _x.gyro.header.stamp.nsecs,) = _get_struct_4I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.gyro.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.gyro.header.frame_id = str[start:end]
      start = end
      end += 4
      (self.gyro.status,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.gyro.v = s.unpack(str[start:end])
      _x = self
      start = end
      end += 17
      (_x.version, _x.timestamp, _x.type, _x.proximity, _x.uncalibratedDEPRECATED,) = _get_struct_3ifB().unpack(str[start:end])
      self.uncalibratedDEPRECATED = bool(self.uncalibratedDEPRECATED)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.acceleration.header.seq, _x.acceleration.header.stamp.secs, _x.acceleration.header.stamp.nsecs))
      _x = self.acceleration.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.acceleration.status
      buff.write(_get_struct_i().pack(_x))
      length = len(self.acceleration.v)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.acceleration.v.tostring())
      _x = self
      buff.write(_get_struct_3I().pack(_x.gyroUncalibrated.header.seq, _x.gyroUncalibrated.header.stamp.secs, _x.gyroUncalibrated.header.stamp.nsecs))
      _x = self.gyroUncalibrated.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.gyroUncalibrated.status
      buff.write(_get_struct_i().pack(_x))
      length = len(self.gyroUncalibrated.v)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.gyroUncalibrated.v.tostring())
      _x = self
      buff.write(_get_struct_f3I().pack(_x.light, _x.orientation.header.seq, _x.orientation.header.stamp.secs, _x.orientation.header.stamp.nsecs))
      _x = self.orientation.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.orientation.status
      buff.write(_get_struct_i().pack(_x))
      length = len(self.orientation.v)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.orientation.v.tostring())
      _x = self
      buff.write(_get_struct_3I().pack(_x.pressure.header.seq, _x.pressure.header.stamp.secs, _x.pressure.header.stamp.nsecs))
      _x = self.pressure.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.pressure.status
      buff.write(_get_struct_i().pack(_x))
      length = len(self.pressure.v)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.pressure.v.tostring())
      _x = self
      buff.write(_get_struct_i3I().pack(_x.sensor, _x.magnetic.header.seq, _x.magnetic.header.stamp.secs, _x.magnetic.header.stamp.nsecs))
      _x = self.magnetic.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.magnetic.status
      buff.write(_get_struct_i().pack(_x))
      length = len(self.magnetic.v)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.magnetic.v.tostring())
      _x = self
      buff.write(_get_struct_3I().pack(_x.magneticUncalibrated.header.seq, _x.magneticUncalibrated.header.stamp.secs, _x.magneticUncalibrated.header.stamp.nsecs))
      _x = self.magneticUncalibrated.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.magneticUncalibrated.status
      buff.write(_get_struct_i().pack(_x))
      length = len(self.magneticUncalibrated.v)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.magneticUncalibrated.v.tostring())
      _x = self
      buff.write(_get_struct_4I().pack(_x.source, _x.gyro.header.seq, _x.gyro.header.stamp.secs, _x.gyro.header.stamp.nsecs))
      _x = self.gyro.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.gyro.status
      buff.write(_get_struct_i().pack(_x))
      length = len(self.gyro.v)
      buff.write(_struct_I.pack(length))
      pattern = '<%sf'%length
      buff.write(self.gyro.v.tostring())
      _x = self
      buff.write(_get_struct_3ifB().pack(_x.version, _x.timestamp, _x.type, _x.proximity, _x.uncalibratedDEPRECATED))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.acceleration is None:
        self.acceleration = openpilot_bridge.msg.SensorVec()
      if self.gyroUncalibrated is None:
        self.gyroUncalibrated = openpilot_bridge.msg.SensorVec()
      if self.orientation is None:
        self.orientation = openpilot_bridge.msg.SensorVec()
      if self.pressure is None:
        self.pressure = openpilot_bridge.msg.SensorVec()
      if self.magnetic is None:
        self.magnetic = openpilot_bridge.msg.SensorVec()
      if self.magneticUncalibrated is None:
        self.magneticUncalibrated = openpilot_bridge.msg.SensorVec()
      if self.gyro is None:
        self.gyro = openpilot_bridge.msg.SensorVec()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.acceleration.header.seq, _x.acceleration.header.stamp.secs, _x.acceleration.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.acceleration.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.acceleration.header.frame_id = str[start:end]
      start = end
      end += 4
      (self.acceleration.status,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.acceleration.v = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      _x = self
      start = end
      end += 12
      (_x.gyroUncalibrated.header.seq, _x.gyroUncalibrated.header.stamp.secs, _x.gyroUncalibrated.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.gyroUncalibrated.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.gyroUncalibrated.header.frame_id = str[start:end]
      start = end
      end += 4
      (self.gyroUncalibrated.status,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.gyroUncalibrated.v = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      _x = self
      start = end
      end += 16
      (_x.light, _x.orientation.header.seq, _x.orientation.header.stamp.secs, _x.orientation.header.stamp.nsecs,) = _get_struct_f3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.orientation.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.orientation.header.frame_id = str[start:end]
      start = end
      end += 4
      (self.orientation.status,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.orientation.v = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      _x = self
      start = end
      end += 12
      (_x.pressure.header.seq, _x.pressure.header.stamp.secs, _x.pressure.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.pressure.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.pressure.header.frame_id = str[start:end]
      start = end
      end += 4
      (self.pressure.status,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.pressure.v = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      _x = self
      start = end
      end += 16
      (_x.sensor, _x.magnetic.header.seq, _x.magnetic.header.stamp.secs, _x.magnetic.header.stamp.nsecs,) = _get_struct_i3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.magnetic.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.magnetic.header.frame_id = str[start:end]
      start = end
      end += 4
      (self.magnetic.status,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.magnetic.v = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      _x = self
      start = end
      end += 12
      (_x.magneticUncalibrated.header.seq, _x.magneticUncalibrated.header.stamp.secs, _x.magneticUncalibrated.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.magneticUncalibrated.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.magneticUncalibrated.header.frame_id = str[start:end]
      start = end
      end += 4
      (self.magneticUncalibrated.status,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.magneticUncalibrated.v = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      _x = self
      start = end
      end += 16
      (_x.source, _x.gyro.header.seq, _x.gyro.header.stamp.secs, _x.gyro.header.stamp.nsecs,) = _get_struct_4I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.gyro.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.gyro.header.frame_id = str[start:end]
      start = end
      end += 4
      (self.gyro.status,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sf'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.gyro.v = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=length)
      _x = self
      start = end
      end += 17
      (_x.version, _x.timestamp, _x.type, _x.proximity, _x.uncalibratedDEPRECATED,) = _get_struct_3ifB().unpack(str[start:end])
      self.uncalibratedDEPRECATED = bool(self.uncalibratedDEPRECATED)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_3ifB = None
def _get_struct_3ifB():
    global _struct_3ifB
    if _struct_3ifB is None:
        _struct_3ifB = struct.Struct("<3ifB")
    return _struct_3ifB
_struct_4I = None
def _get_struct_4I():
    global _struct_4I
    if _struct_4I is None:
        _struct_4I = struct.Struct("<4I")
    return _struct_4I
_struct_f3I = None
def _get_struct_f3I():
    global _struct_f3I
    if _struct_f3I is None:
        _struct_f3I = struct.Struct("<f3I")
    return _struct_f3I
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
_struct_i3I = None
def _get_struct_i3I():
    global _struct_i3I
    if _struct_i3I is None:
        _struct_i3I = struct.Struct("<i3I")
    return _struct_i3I
