// Generated by gencpp from file openpilot_bridge/ButtonEvent.msg
// DO NOT EDIT!


#ifndef OPENPILOT_BRIDGE_MESSAGE_BUTTONEVENT_H
#define OPENPILOT_BRIDGE_MESSAGE_BUTTONEVENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace openpilot_bridge
{
template <class ContainerAllocator>
struct ButtonEvent_
{
  typedef ButtonEvent_<ContainerAllocator> Type;

  ButtonEvent_()
    : header()
    , type(0)
    , pressed(false)  {
    }
  ButtonEvent_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , type(0)
    , pressed(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _type_type;
  _type_type type;

   typedef uint8_t _pressed_type;
  _pressed_type pressed;





  typedef boost::shared_ptr< ::openpilot_bridge::ButtonEvent_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::openpilot_bridge::ButtonEvent_<ContainerAllocator> const> ConstPtr;

}; // struct ButtonEvent_

typedef ::openpilot_bridge::ButtonEvent_<std::allocator<void> > ButtonEvent;

typedef boost::shared_ptr< ::openpilot_bridge::ButtonEvent > ButtonEventPtr;
typedef boost::shared_ptr< ::openpilot_bridge::ButtonEvent const> ButtonEventConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::openpilot_bridge::ButtonEvent_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::openpilot_bridge::ButtonEvent_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::openpilot_bridge::ButtonEvent_<ContainerAllocator1> & lhs, const ::openpilot_bridge::ButtonEvent_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.type == rhs.type &&
    lhs.pressed == rhs.pressed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::openpilot_bridge::ButtonEvent_<ContainerAllocator1> & lhs, const ::openpilot_bridge::ButtonEvent_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace openpilot_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::openpilot_bridge::ButtonEvent_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::openpilot_bridge::ButtonEvent_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpilot_bridge::ButtonEvent_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpilot_bridge::ButtonEvent_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpilot_bridge::ButtonEvent_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpilot_bridge::ButtonEvent_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::openpilot_bridge::ButtonEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a73eec4face11f6e7d39beb188805386";
  }

  static const char* value(const ::openpilot_bridge::ButtonEvent_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa73eec4face11f6eULL;
  static const uint64_t static_value2 = 0x7d39beb188805386ULL;
};

template<class ContainerAllocator>
struct DataType< ::openpilot_bridge::ButtonEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "openpilot_bridge/ButtonEvent";
  }

  static const char* value(const ::openpilot_bridge::ButtonEvent_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::openpilot_bridge::ButtonEvent_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"uint32 type # enum const: Type\n"
"bool pressed\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::openpilot_bridge::ButtonEvent_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::openpilot_bridge::ButtonEvent_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.type);
      stream.next(m.pressed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ButtonEvent_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::openpilot_bridge::ButtonEvent_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::openpilot_bridge::ButtonEvent_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "type: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.type);
    s << indent << "pressed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.pressed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPENPILOT_BRIDGE_MESSAGE_BUTTONEVENT_H
