// Generated by gencpp from file openpilot_bridge/CarParams.msg
// DO NOT EDIT!


#ifndef OPENPILOT_BRIDGE_MESSAGE_CARPARAMS_H
#define OPENPILOT_BRIDGE_MESSAGE_CARPARAMS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <openpilot_bridge/Lateraltuning.h>
#include <openpilot_bridge/CarFw.h>
#include <openpilot_bridge/LongitudinalPIDTuning.h>

namespace openpilot_bridge
{
template <class ContainerAllocator>
struct CarParams_
{
  typedef CarParams_<ContainerAllocator> Type;

  CarParams_()
    : header()
    , safetyParam(0)
    , steerRatioRear(0.0)
    , enableDsu(false)
    , lateralTuning()
    , steerControlType(0)
    , carFingerprint()
    , rotationalInertia(0.0)
    , safetyModelPassive(0)
    , carFw()
    , minEnableSpeed(0.0)
    , enableGasInterceptor(false)
    , radarOffCan(false)
    , steerRatio(0.0)
    , vEgoStopping(0.0)
    , enableCamera(false)
    , enableCruise(false)
    , tireStiffnessFront(0.0)
    , minSteerSpeed(0.0)
    , stoppingControl(false)
    , steerLimitTimer(0.0)
    , transmissionType(0)
    , steerMaxV()
    , openpilotLongitudinalControl(false)
    , gasMaxBP()
    , enableApgs(false)
    , radarTimeStep(0.0)
    , carName()
    , safetyModel(0)
    , carVin()
    , steerMaxBP()
    , gasMaxV()
    , steerRateCost(0.0)
    , brakeMaxV()
    , tireStiffnessRear(0.0)
    , centerToFront(0.0)
    , dashcamOnly(false)
    , startAccel(0.0)
    , wheelbase(0.0)
    , brakeMaxBP()
    , mass(0.0)
    , steerActuatorDelay(0.0)
    , longitudinalTuning()
    , directAccelControl(false)
    , communityFeature(false)
    , isPandaBlack(false)
    , steerLimitAlert(false)  {
    }
  CarParams_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , safetyParam(0)
    , steerRatioRear(0.0)
    , enableDsu(false)
    , lateralTuning(_alloc)
    , steerControlType(0)
    , carFingerprint(_alloc)
    , rotationalInertia(0.0)
    , safetyModelPassive(0)
    , carFw(_alloc)
    , minEnableSpeed(0.0)
    , enableGasInterceptor(false)
    , radarOffCan(false)
    , steerRatio(0.0)
    , vEgoStopping(0.0)
    , enableCamera(false)
    , enableCruise(false)
    , tireStiffnessFront(0.0)
    , minSteerSpeed(0.0)
    , stoppingControl(false)
    , steerLimitTimer(0.0)
    , transmissionType(0)
    , steerMaxV(_alloc)
    , openpilotLongitudinalControl(false)
    , gasMaxBP(_alloc)
    , enableApgs(false)
    , radarTimeStep(0.0)
    , carName(_alloc)
    , safetyModel(0)
    , carVin(_alloc)
    , steerMaxBP(_alloc)
    , gasMaxV(_alloc)
    , steerRateCost(0.0)
    , brakeMaxV(_alloc)
    , tireStiffnessRear(0.0)
    , centerToFront(0.0)
    , dashcamOnly(false)
    , startAccel(0.0)
    , wheelbase(0.0)
    , brakeMaxBP(_alloc)
    , mass(0.0)
    , steerActuatorDelay(0.0)
    , longitudinalTuning(_alloc)
    , directAccelControl(false)
    , communityFeature(false)
    , isPandaBlack(false)
    , steerLimitAlert(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _safetyParam_type;
  _safetyParam_type safetyParam;

   typedef float _steerRatioRear_type;
  _steerRatioRear_type steerRatioRear;

   typedef uint8_t _enableDsu_type;
  _enableDsu_type enableDsu;

   typedef  ::openpilot_bridge::Lateraltuning_<ContainerAllocator>  _lateralTuning_type;
  _lateralTuning_type lateralTuning;

   typedef uint32_t _steerControlType_type;
  _steerControlType_type steerControlType;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _carFingerprint_type;
  _carFingerprint_type carFingerprint;

   typedef float _rotationalInertia_type;
  _rotationalInertia_type rotationalInertia;

   typedef uint32_t _safetyModelPassive_type;
  _safetyModelPassive_type safetyModelPassive;

   typedef std::vector< ::openpilot_bridge::CarFw_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::openpilot_bridge::CarFw_<ContainerAllocator> >::other >  _carFw_type;
  _carFw_type carFw;

   typedef float _minEnableSpeed_type;
  _minEnableSpeed_type minEnableSpeed;

   typedef uint8_t _enableGasInterceptor_type;
  _enableGasInterceptor_type enableGasInterceptor;

   typedef uint8_t _radarOffCan_type;
  _radarOffCan_type radarOffCan;

   typedef float _steerRatio_type;
  _steerRatio_type steerRatio;

   typedef float _vEgoStopping_type;
  _vEgoStopping_type vEgoStopping;

   typedef uint8_t _enableCamera_type;
  _enableCamera_type enableCamera;

   typedef uint8_t _enableCruise_type;
  _enableCruise_type enableCruise;

   typedef float _tireStiffnessFront_type;
  _tireStiffnessFront_type tireStiffnessFront;

   typedef float _minSteerSpeed_type;
  _minSteerSpeed_type minSteerSpeed;

   typedef uint8_t _stoppingControl_type;
  _stoppingControl_type stoppingControl;

   typedef float _steerLimitTimer_type;
  _steerLimitTimer_type steerLimitTimer;

   typedef uint32_t _transmissionType_type;
  _transmissionType_type transmissionType;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _steerMaxV_type;
  _steerMaxV_type steerMaxV;

   typedef uint8_t _openpilotLongitudinalControl_type;
  _openpilotLongitudinalControl_type openpilotLongitudinalControl;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _gasMaxBP_type;
  _gasMaxBP_type gasMaxBP;

   typedef uint8_t _enableApgs_type;
  _enableApgs_type enableApgs;

   typedef float _radarTimeStep_type;
  _radarTimeStep_type radarTimeStep;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _carName_type;
  _carName_type carName;

   typedef uint32_t _safetyModel_type;
  _safetyModel_type safetyModel;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _carVin_type;
  _carVin_type carVin;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _steerMaxBP_type;
  _steerMaxBP_type steerMaxBP;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _gasMaxV_type;
  _gasMaxV_type gasMaxV;

   typedef float _steerRateCost_type;
  _steerRateCost_type steerRateCost;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _brakeMaxV_type;
  _brakeMaxV_type brakeMaxV;

   typedef float _tireStiffnessRear_type;
  _tireStiffnessRear_type tireStiffnessRear;

   typedef float _centerToFront_type;
  _centerToFront_type centerToFront;

   typedef uint8_t _dashcamOnly_type;
  _dashcamOnly_type dashcamOnly;

   typedef float _startAccel_type;
  _startAccel_type startAccel;

   typedef float _wheelbase_type;
  _wheelbase_type wheelbase;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _brakeMaxBP_type;
  _brakeMaxBP_type brakeMaxBP;

   typedef float _mass_type;
  _mass_type mass;

   typedef float _steerActuatorDelay_type;
  _steerActuatorDelay_type steerActuatorDelay;

   typedef  ::openpilot_bridge::LongitudinalPIDTuning_<ContainerAllocator>  _longitudinalTuning_type;
  _longitudinalTuning_type longitudinalTuning;

   typedef uint8_t _directAccelControl_type;
  _directAccelControl_type directAccelControl;

   typedef uint8_t _communityFeature_type;
  _communityFeature_type communityFeature;

   typedef uint8_t _isPandaBlack_type;
  _isPandaBlack_type isPandaBlack;

   typedef uint8_t _steerLimitAlert_type;
  _steerLimitAlert_type steerLimitAlert;





  typedef boost::shared_ptr< ::openpilot_bridge::CarParams_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::openpilot_bridge::CarParams_<ContainerAllocator> const> ConstPtr;

}; // struct CarParams_

typedef ::openpilot_bridge::CarParams_<std::allocator<void> > CarParams;

typedef boost::shared_ptr< ::openpilot_bridge::CarParams > CarParamsPtr;
typedef boost::shared_ptr< ::openpilot_bridge::CarParams const> CarParamsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::openpilot_bridge::CarParams_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::openpilot_bridge::CarParams_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::openpilot_bridge::CarParams_<ContainerAllocator1> & lhs, const ::openpilot_bridge::CarParams_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.safetyParam == rhs.safetyParam &&
    lhs.steerRatioRear == rhs.steerRatioRear &&
    lhs.enableDsu == rhs.enableDsu &&
    lhs.lateralTuning == rhs.lateralTuning &&
    lhs.steerControlType == rhs.steerControlType &&
    lhs.carFingerprint == rhs.carFingerprint &&
    lhs.rotationalInertia == rhs.rotationalInertia &&
    lhs.safetyModelPassive == rhs.safetyModelPassive &&
    lhs.carFw == rhs.carFw &&
    lhs.minEnableSpeed == rhs.minEnableSpeed &&
    lhs.enableGasInterceptor == rhs.enableGasInterceptor &&
    lhs.radarOffCan == rhs.radarOffCan &&
    lhs.steerRatio == rhs.steerRatio &&
    lhs.vEgoStopping == rhs.vEgoStopping &&
    lhs.enableCamera == rhs.enableCamera &&
    lhs.enableCruise == rhs.enableCruise &&
    lhs.tireStiffnessFront == rhs.tireStiffnessFront &&
    lhs.minSteerSpeed == rhs.minSteerSpeed &&
    lhs.stoppingControl == rhs.stoppingControl &&
    lhs.steerLimitTimer == rhs.steerLimitTimer &&
    lhs.transmissionType == rhs.transmissionType &&
    lhs.steerMaxV == rhs.steerMaxV &&
    lhs.openpilotLongitudinalControl == rhs.openpilotLongitudinalControl &&
    lhs.gasMaxBP == rhs.gasMaxBP &&
    lhs.enableApgs == rhs.enableApgs &&
    lhs.radarTimeStep == rhs.radarTimeStep &&
    lhs.carName == rhs.carName &&
    lhs.safetyModel == rhs.safetyModel &&
    lhs.carVin == rhs.carVin &&
    lhs.steerMaxBP == rhs.steerMaxBP &&
    lhs.gasMaxV == rhs.gasMaxV &&
    lhs.steerRateCost == rhs.steerRateCost &&
    lhs.brakeMaxV == rhs.brakeMaxV &&
    lhs.tireStiffnessRear == rhs.tireStiffnessRear &&
    lhs.centerToFront == rhs.centerToFront &&
    lhs.dashcamOnly == rhs.dashcamOnly &&
    lhs.startAccel == rhs.startAccel &&
    lhs.wheelbase == rhs.wheelbase &&
    lhs.brakeMaxBP == rhs.brakeMaxBP &&
    lhs.mass == rhs.mass &&
    lhs.steerActuatorDelay == rhs.steerActuatorDelay &&
    lhs.longitudinalTuning == rhs.longitudinalTuning &&
    lhs.directAccelControl == rhs.directAccelControl &&
    lhs.communityFeature == rhs.communityFeature &&
    lhs.isPandaBlack == rhs.isPandaBlack &&
    lhs.steerLimitAlert == rhs.steerLimitAlert;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::openpilot_bridge::CarParams_<ContainerAllocator1> & lhs, const ::openpilot_bridge::CarParams_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace openpilot_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::openpilot_bridge::CarParams_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::openpilot_bridge::CarParams_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpilot_bridge::CarParams_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpilot_bridge::CarParams_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpilot_bridge::CarParams_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpilot_bridge::CarParams_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::openpilot_bridge::CarParams_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ef560c6163951e81bdbf13272f514bb1";
  }

  static const char* value(const ::openpilot_bridge::CarParams_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xef560c6163951e81ULL;
  static const uint64_t static_value2 = 0xbdbf13272f514bb1ULL;
};

template<class ContainerAllocator>
struct DataType< ::openpilot_bridge::CarParams_<ContainerAllocator> >
{
  static const char* value()
  {
    return "openpilot_bridge/CarParams";
  }

  static const char* value(const ::openpilot_bridge::CarParams_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::openpilot_bridge::CarParams_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"int32 safetyParam\n"
"float32 steerRatioRear\n"
"bool enableDsu\n"
"Lateraltuning lateralTuning\n"
"uint32 steerControlType # enum const: SteerControlType\n"
"string[] carFingerprint\n"
"float32 rotationalInertia\n"
"uint32 safetyModelPassive # enum const: SafetyModel\n"
"CarFw[] carFw\n"
"float32 minEnableSpeed\n"
"bool enableGasInterceptor\n"
"bool radarOffCan\n"
"float32 steerRatio\n"
"float32 vEgoStopping\n"
"bool enableCamera\n"
"bool enableCruise\n"
"float32 tireStiffnessFront\n"
"float32 minSteerSpeed\n"
"bool stoppingControl\n"
"float32 steerLimitTimer\n"
"uint32 transmissionType # enum const: TransmissionType\n"
"float32[] steerMaxV\n"
"bool openpilotLongitudinalControl\n"
"float32[] gasMaxBP\n"
"bool enableApgs\n"
"float32 radarTimeStep\n"
"string[] carName\n"
"uint32 safetyModel # enum const: SafetyModel\n"
"string[] carVin\n"
"float32[] steerMaxBP\n"
"float32[] gasMaxV\n"
"float32 steerRateCost\n"
"float32[] brakeMaxV\n"
"float32 tireStiffnessRear\n"
"float32 centerToFront\n"
"bool dashcamOnly\n"
"float32 startAccel\n"
"float32 wheelbase\n"
"float32[] brakeMaxBP\n"
"float32 mass\n"
"float32 steerActuatorDelay\n"
"LongitudinalPIDTuning longitudinalTuning\n"
"bool directAccelControl\n"
"bool communityFeature\n"
"bool isPandaBlack\n"
"bool steerLimitAlert\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: openpilot_bridge/Lateraltuning\n"
"Header header\n"
"\n"
"LateralINDITuning indi\n"
"LateralPIDTuning pid\n"
"LateralLQRTuning lqr\n"
"\n"
"================================================================================\n"
"MSG: openpilot_bridge/LateralINDITuning\n"
"Header header\n"
"\n"
"float32 actuatorEffectiveness\n"
"float32 outerLoopGain\n"
"float32 innerLoopGain\n"
"float32 timeConstant\n"
"\n"
"================================================================================\n"
"MSG: openpilot_bridge/LateralPIDTuning\n"
"Header header\n"
"\n"
"float32[] kiBP\n"
"float32 kf\n"
"float32[] kiV\n"
"float32[] kpV\n"
"float32[] kpBP\n"
"\n"
"================================================================================\n"
"MSG: openpilot_bridge/LateralLQRTuning\n"
"Header header\n"
"\n"
"float32[] a\n"
"float32[] c\n"
"float32 scale\n"
"float32 ki\n"
"float32[] l\n"
"float32[] b\n"
"float32 dcGain\n"
"float32[] k\n"
"\n"
"================================================================================\n"
"MSG: openpilot_bridge/CarFw\n"
"Header header\n"
"\n"
"uint32 ecu # enum const: Ecu\n"
"int64 subAddress\n"
"string[] fwVersion\n"
"int64 address\n"
"\n"
"================================================================================\n"
"MSG: openpilot_bridge/LongitudinalPIDTuning\n"
"Header header\n"
"\n"
"float32[] kpV\n"
"float32[] kpBP\n"
"float32[] deadzoneBP\n"
"float32[] kiV\n"
"float32[] deadzoneV\n"
"float32[] kiBP\n"
;
  }

  static const char* value(const ::openpilot_bridge::CarParams_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::openpilot_bridge::CarParams_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.safetyParam);
      stream.next(m.steerRatioRear);
      stream.next(m.enableDsu);
      stream.next(m.lateralTuning);
      stream.next(m.steerControlType);
      stream.next(m.carFingerprint);
      stream.next(m.rotationalInertia);
      stream.next(m.safetyModelPassive);
      stream.next(m.carFw);
      stream.next(m.minEnableSpeed);
      stream.next(m.enableGasInterceptor);
      stream.next(m.radarOffCan);
      stream.next(m.steerRatio);
      stream.next(m.vEgoStopping);
      stream.next(m.enableCamera);
      stream.next(m.enableCruise);
      stream.next(m.tireStiffnessFront);
      stream.next(m.minSteerSpeed);
      stream.next(m.stoppingControl);
      stream.next(m.steerLimitTimer);
      stream.next(m.transmissionType);
      stream.next(m.steerMaxV);
      stream.next(m.openpilotLongitudinalControl);
      stream.next(m.gasMaxBP);
      stream.next(m.enableApgs);
      stream.next(m.radarTimeStep);
      stream.next(m.carName);
      stream.next(m.safetyModel);
      stream.next(m.carVin);
      stream.next(m.steerMaxBP);
      stream.next(m.gasMaxV);
      stream.next(m.steerRateCost);
      stream.next(m.brakeMaxV);
      stream.next(m.tireStiffnessRear);
      stream.next(m.centerToFront);
      stream.next(m.dashcamOnly);
      stream.next(m.startAccel);
      stream.next(m.wheelbase);
      stream.next(m.brakeMaxBP);
      stream.next(m.mass);
      stream.next(m.steerActuatorDelay);
      stream.next(m.longitudinalTuning);
      stream.next(m.directAccelControl);
      stream.next(m.communityFeature);
      stream.next(m.isPandaBlack);
      stream.next(m.steerLimitAlert);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CarParams_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::openpilot_bridge::CarParams_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::openpilot_bridge::CarParams_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "safetyParam: ";
    Printer<int32_t>::stream(s, indent + "  ", v.safetyParam);
    s << indent << "steerRatioRear: ";
    Printer<float>::stream(s, indent + "  ", v.steerRatioRear);
    s << indent << "enableDsu: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enableDsu);
    s << indent << "lateralTuning: ";
    s << std::endl;
    Printer< ::openpilot_bridge::Lateraltuning_<ContainerAllocator> >::stream(s, indent + "  ", v.lateralTuning);
    s << indent << "steerControlType: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.steerControlType);
    s << indent << "carFingerprint[]" << std::endl;
    for (size_t i = 0; i < v.carFingerprint.size(); ++i)
    {
      s << indent << "  carFingerprint[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.carFingerprint[i]);
    }
    s << indent << "rotationalInertia: ";
    Printer<float>::stream(s, indent + "  ", v.rotationalInertia);
    s << indent << "safetyModelPassive: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.safetyModelPassive);
    s << indent << "carFw[]" << std::endl;
    for (size_t i = 0; i < v.carFw.size(); ++i)
    {
      s << indent << "  carFw[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::openpilot_bridge::CarFw_<ContainerAllocator> >::stream(s, indent + "    ", v.carFw[i]);
    }
    s << indent << "minEnableSpeed: ";
    Printer<float>::stream(s, indent + "  ", v.minEnableSpeed);
    s << indent << "enableGasInterceptor: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enableGasInterceptor);
    s << indent << "radarOffCan: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.radarOffCan);
    s << indent << "steerRatio: ";
    Printer<float>::stream(s, indent + "  ", v.steerRatio);
    s << indent << "vEgoStopping: ";
    Printer<float>::stream(s, indent + "  ", v.vEgoStopping);
    s << indent << "enableCamera: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enableCamera);
    s << indent << "enableCruise: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enableCruise);
    s << indent << "tireStiffnessFront: ";
    Printer<float>::stream(s, indent + "  ", v.tireStiffnessFront);
    s << indent << "minSteerSpeed: ";
    Printer<float>::stream(s, indent + "  ", v.minSteerSpeed);
    s << indent << "stoppingControl: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.stoppingControl);
    s << indent << "steerLimitTimer: ";
    Printer<float>::stream(s, indent + "  ", v.steerLimitTimer);
    s << indent << "transmissionType: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.transmissionType);
    s << indent << "steerMaxV[]" << std::endl;
    for (size_t i = 0; i < v.steerMaxV.size(); ++i)
    {
      s << indent << "  steerMaxV[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.steerMaxV[i]);
    }
    s << indent << "openpilotLongitudinalControl: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.openpilotLongitudinalControl);
    s << indent << "gasMaxBP[]" << std::endl;
    for (size_t i = 0; i < v.gasMaxBP.size(); ++i)
    {
      s << indent << "  gasMaxBP[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.gasMaxBP[i]);
    }
    s << indent << "enableApgs: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enableApgs);
    s << indent << "radarTimeStep: ";
    Printer<float>::stream(s, indent + "  ", v.radarTimeStep);
    s << indent << "carName[]" << std::endl;
    for (size_t i = 0; i < v.carName.size(); ++i)
    {
      s << indent << "  carName[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.carName[i]);
    }
    s << indent << "safetyModel: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.safetyModel);
    s << indent << "carVin[]" << std::endl;
    for (size_t i = 0; i < v.carVin.size(); ++i)
    {
      s << indent << "  carVin[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.carVin[i]);
    }
    s << indent << "steerMaxBP[]" << std::endl;
    for (size_t i = 0; i < v.steerMaxBP.size(); ++i)
    {
      s << indent << "  steerMaxBP[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.steerMaxBP[i]);
    }
    s << indent << "gasMaxV[]" << std::endl;
    for (size_t i = 0; i < v.gasMaxV.size(); ++i)
    {
      s << indent << "  gasMaxV[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.gasMaxV[i]);
    }
    s << indent << "steerRateCost: ";
    Printer<float>::stream(s, indent + "  ", v.steerRateCost);
    s << indent << "brakeMaxV[]" << std::endl;
    for (size_t i = 0; i < v.brakeMaxV.size(); ++i)
    {
      s << indent << "  brakeMaxV[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.brakeMaxV[i]);
    }
    s << indent << "tireStiffnessRear: ";
    Printer<float>::stream(s, indent + "  ", v.tireStiffnessRear);
    s << indent << "centerToFront: ";
    Printer<float>::stream(s, indent + "  ", v.centerToFront);
    s << indent << "dashcamOnly: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dashcamOnly);
    s << indent << "startAccel: ";
    Printer<float>::stream(s, indent + "  ", v.startAccel);
    s << indent << "wheelbase: ";
    Printer<float>::stream(s, indent + "  ", v.wheelbase);
    s << indent << "brakeMaxBP[]" << std::endl;
    for (size_t i = 0; i < v.brakeMaxBP.size(); ++i)
    {
      s << indent << "  brakeMaxBP[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.brakeMaxBP[i]);
    }
    s << indent << "mass: ";
    Printer<float>::stream(s, indent + "  ", v.mass);
    s << indent << "steerActuatorDelay: ";
    Printer<float>::stream(s, indent + "  ", v.steerActuatorDelay);
    s << indent << "longitudinalTuning: ";
    s << std::endl;
    Printer< ::openpilot_bridge::LongitudinalPIDTuning_<ContainerAllocator> >::stream(s, indent + "  ", v.longitudinalTuning);
    s << indent << "directAccelControl: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.directAccelControl);
    s << indent << "communityFeature: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.communityFeature);
    s << indent << "isPandaBlack: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isPandaBlack);
    s << indent << "steerLimitAlert: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.steerLimitAlert);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPENPILOT_BRIDGE_MESSAGE_CARPARAMS_H
