// Generated by gencpp from file openpilot_bridge/ChffrAndroidExtra.msg
// DO NOT EDIT!


#ifndef OPENPILOT_BRIDGE_MESSAGE_CHFFRANDROIDEXTRA_H
#define OPENPILOT_BRIDGE_MESSAGE_CHFFRANDROIDEXTRA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <openpilot_bridge/Map.h>

namespace openpilot_bridge
{
template <class ContainerAllocator>
struct ChffrAndroidExtra_
{
  typedef ChffrAndroidExtra_<ContainerAllocator> Type;

  ChffrAndroidExtra_()
    : header()
    , allCameraCharacteristics()  {
    }
  ChffrAndroidExtra_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , allCameraCharacteristics(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::openpilot_bridge::Map_<ContainerAllocator>  _allCameraCharacteristics_type;
  _allCameraCharacteristics_type allCameraCharacteristics;





  typedef boost::shared_ptr< ::openpilot_bridge::ChffrAndroidExtra_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::openpilot_bridge::ChffrAndroidExtra_<ContainerAllocator> const> ConstPtr;

}; // struct ChffrAndroidExtra_

typedef ::openpilot_bridge::ChffrAndroidExtra_<std::allocator<void> > ChffrAndroidExtra;

typedef boost::shared_ptr< ::openpilot_bridge::ChffrAndroidExtra > ChffrAndroidExtraPtr;
typedef boost::shared_ptr< ::openpilot_bridge::ChffrAndroidExtra const> ChffrAndroidExtraConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::openpilot_bridge::ChffrAndroidExtra_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::openpilot_bridge::ChffrAndroidExtra_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::openpilot_bridge::ChffrAndroidExtra_<ContainerAllocator1> & lhs, const ::openpilot_bridge::ChffrAndroidExtra_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.allCameraCharacteristics == rhs.allCameraCharacteristics;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::openpilot_bridge::ChffrAndroidExtra_<ContainerAllocator1> & lhs, const ::openpilot_bridge::ChffrAndroidExtra_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace openpilot_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::openpilot_bridge::ChffrAndroidExtra_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::openpilot_bridge::ChffrAndroidExtra_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpilot_bridge::ChffrAndroidExtra_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpilot_bridge::ChffrAndroidExtra_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpilot_bridge::ChffrAndroidExtra_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpilot_bridge::ChffrAndroidExtra_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::openpilot_bridge::ChffrAndroidExtra_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b43d42df107e761f273426529e592a9c";
  }

  static const char* value(const ::openpilot_bridge::ChffrAndroidExtra_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb43d42df107e761fULL;
  static const uint64_t static_value2 = 0x273426529e592a9cULL;
};

template<class ContainerAllocator>
struct DataType< ::openpilot_bridge::ChffrAndroidExtra_<ContainerAllocator> >
{
  static const char* value()
  {
    return "openpilot_bridge/ChffrAndroidExtra";
  }

  static const char* value(const ::openpilot_bridge::ChffrAndroidExtra_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::openpilot_bridge::ChffrAndroidExtra_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"Map allCameraCharacteristics\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: openpilot_bridge/Map\n"
"Header header\n"
"\n"
"Entry[] entries\n"
"\n"
"================================================================================\n"
"MSG: openpilot_bridge/Entry\n"
"Header header\n"
"\n"
"string value\n"
"string key\n"
;
  }

  static const char* value(const ::openpilot_bridge::ChffrAndroidExtra_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::openpilot_bridge::ChffrAndroidExtra_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.allCameraCharacteristics);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChffrAndroidExtra_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::openpilot_bridge::ChffrAndroidExtra_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::openpilot_bridge::ChffrAndroidExtra_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "allCameraCharacteristics: ";
    s << std::endl;
    Printer< ::openpilot_bridge::Map_<ContainerAllocator> >::stream(s, indent + "  ", v.allCameraCharacteristics);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPENPILOT_BRIDGE_MESSAGE_CHFFRANDROIDEXTRA_H
