// Generated by gencpp from file openpilot_bridge/Desire.msg
// DO NOT EDIT!


#ifndef OPENPILOT_BRIDGE_MESSAGE_DESIRE_H
#define OPENPILOT_BRIDGE_MESSAGE_DESIRE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace openpilot_bridge
{
template <class ContainerAllocator>
struct Desire_
{
  typedef Desire_<ContainerAllocator> Type;

  Desire_()
    {
    }
  Desire_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }





// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(none)
  #undef none
#endif
#if defined(_WIN32) && defined(turnLeft)
  #undef turnLeft
#endif
#if defined(_WIN32) && defined(laneChangeRight)
  #undef laneChangeRight
#endif
#if defined(_WIN32) && defined(laneChangeLeft)
  #undef laneChangeLeft
#endif
#if defined(_WIN32) && defined(turnRight)
  #undef turnRight
#endif
#if defined(_WIN32) && defined(keepRight)
  #undef keepRight
#endif
#if defined(_WIN32) && defined(keepLeft)
  #undef keepLeft
#endif

  enum {
    none = 0u,
    turnLeft = 1u,
    laneChangeRight = 4u,
    laneChangeLeft = 3u,
    turnRight = 2u,
    keepRight = 6u,
    keepLeft = 5u,
  };


  typedef boost::shared_ptr< ::openpilot_bridge::Desire_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::openpilot_bridge::Desire_<ContainerAllocator> const> ConstPtr;

}; // struct Desire_

typedef ::openpilot_bridge::Desire_<std::allocator<void> > Desire;

typedef boost::shared_ptr< ::openpilot_bridge::Desire > DesirePtr;
typedef boost::shared_ptr< ::openpilot_bridge::Desire const> DesireConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::openpilot_bridge::Desire_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::openpilot_bridge::Desire_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace openpilot_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::openpilot_bridge::Desire_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::openpilot_bridge::Desire_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpilot_bridge::Desire_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpilot_bridge::Desire_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpilot_bridge::Desire_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpilot_bridge::Desire_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::openpilot_bridge::Desire_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b80700589a9a6c06d4798f291a92dd6e";
  }

  static const char* value(const ::openpilot_bridge::Desire_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb80700589a9a6c06ULL;
  static const uint64_t static_value2 = 0xd4798f291a92dd6eULL;
};

template<class ContainerAllocator>
struct DataType< ::openpilot_bridge::Desire_<ContainerAllocator> >
{
  static const char* value()
  {
    return "openpilot_bridge/Desire";
  }

  static const char* value(const ::openpilot_bridge::Desire_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::openpilot_bridge::Desire_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 none=0\n"
"uint32 turnLeft=1\n"
"uint32 laneChangeRight=4\n"
"uint32 laneChangeLeft=3\n"
"uint32 turnRight=2\n"
"uint32 keepRight=6\n"
"uint32 keepLeft=5\n"
;
  }

  static const char* value(const ::openpilot_bridge::Desire_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::openpilot_bridge::Desire_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Desire_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::openpilot_bridge::Desire_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::openpilot_bridge::Desire_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // OPENPILOT_BRIDGE_MESSAGE_DESIRE_H
