// Generated by gencpp from file openpilot_bridge/Ecu.msg
// DO NOT EDIT!


#ifndef OPENPILOT_BRIDGE_MESSAGE_ECU_H
#define OPENPILOT_BRIDGE_MESSAGE_ECU_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace openpilot_bridge
{
template <class ContainerAllocator>
struct Ecu_
{
  typedef Ecu_<ContainerAllocator> Type;

  Ecu_()
    {
    }
  Ecu_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }





// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(engine)
  #undef engine
#endif
#if defined(_WIN32) && defined(esp)
  #undef esp
#endif
#if defined(_WIN32) && defined(unknown)
  #undef unknown
#endif
#if defined(_WIN32) && defined(dsu)
  #undef dsu
#endif
#if defined(_WIN32) && defined(eps)
  #undef eps
#endif
#if defined(_WIN32) && defined(apgs)
  #undef apgs
#endif
#if defined(_WIN32) && defined(fwdRadar)
  #undef fwdRadar
#endif
#if defined(_WIN32) && defined(fwdCamera)
  #undef fwdCamera
#endif

  enum {
    engine = 4u,
    esp = 1u,
    unknown = 5u,
    dsu = 6u,
    eps = 0u,
    apgs = 7u,
    fwdRadar = 2u,
    fwdCamera = 3u,
  };


  typedef boost::shared_ptr< ::openpilot_bridge::Ecu_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::openpilot_bridge::Ecu_<ContainerAllocator> const> ConstPtr;

}; // struct Ecu_

typedef ::openpilot_bridge::Ecu_<std::allocator<void> > Ecu;

typedef boost::shared_ptr< ::openpilot_bridge::Ecu > EcuPtr;
typedef boost::shared_ptr< ::openpilot_bridge::Ecu const> EcuConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::openpilot_bridge::Ecu_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::openpilot_bridge::Ecu_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace openpilot_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::openpilot_bridge::Ecu_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::openpilot_bridge::Ecu_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpilot_bridge::Ecu_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpilot_bridge::Ecu_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpilot_bridge::Ecu_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpilot_bridge::Ecu_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::openpilot_bridge::Ecu_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b4567db0d123c6b76edb282c1d1130de";
  }

  static const char* value(const ::openpilot_bridge::Ecu_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb4567db0d123c6b7ULL;
  static const uint64_t static_value2 = 0x6edb282c1d1130deULL;
};

template<class ContainerAllocator>
struct DataType< ::openpilot_bridge::Ecu_<ContainerAllocator> >
{
  static const char* value()
  {
    return "openpilot_bridge/Ecu";
  }

  static const char* value(const ::openpilot_bridge::Ecu_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::openpilot_bridge::Ecu_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 engine=4\n"
"uint32 esp=1\n"
"uint32 unknown=5\n"
"uint32 dsu=6\n"
"uint32 eps=0\n"
"uint32 apgs=7\n"
"uint32 fwdRadar=2\n"
"uint32 fwdCamera=3\n"
;
  }

  static const char* value(const ::openpilot_bridge::Ecu_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::openpilot_bridge::Ecu_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Ecu_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::openpilot_bridge::Ecu_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::openpilot_bridge::Ecu_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // OPENPILOT_BRIDGE_MESSAGE_ECU_H
