// Generated by gencpp from file openpilot_bridge/EncodeIndex.msg
// DO NOT EDIT!


#ifndef OPENPILOT_BRIDGE_MESSAGE_ENCODEINDEX_H
#define OPENPILOT_BRIDGE_MESSAGE_ENCODEINDEX_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace openpilot_bridge
{
template <class ContainerAllocator>
struct EncodeIndex_
{
  typedef EncodeIndex_<ContainerAllocator> Type;

  EncodeIndex_()
    : header()
    , segmentId(0)
    , segmentIdEncode(0)
    , frameId(0)
    , encodeId(0)
    , type(0)
    , segmentNum(0)  {
    }
  EncodeIndex_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , segmentId(0)
    , segmentIdEncode(0)
    , frameId(0)
    , encodeId(0)
    , type(0)
    , segmentNum(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int64_t _segmentId_type;
  _segmentId_type segmentId;

   typedef int64_t _segmentIdEncode_type;
  _segmentIdEncode_type segmentIdEncode;

   typedef int64_t _frameId_type;
  _frameId_type frameId;

   typedef int64_t _encodeId_type;
  _encodeId_type encodeId;

   typedef uint32_t _type_type;
  _type_type type;

   typedef int32_t _segmentNum_type;
  _segmentNum_type segmentNum;





  typedef boost::shared_ptr< ::openpilot_bridge::EncodeIndex_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::openpilot_bridge::EncodeIndex_<ContainerAllocator> const> ConstPtr;

}; // struct EncodeIndex_

typedef ::openpilot_bridge::EncodeIndex_<std::allocator<void> > EncodeIndex;

typedef boost::shared_ptr< ::openpilot_bridge::EncodeIndex > EncodeIndexPtr;
typedef boost::shared_ptr< ::openpilot_bridge::EncodeIndex const> EncodeIndexConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::openpilot_bridge::EncodeIndex_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::openpilot_bridge::EncodeIndex_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::openpilot_bridge::EncodeIndex_<ContainerAllocator1> & lhs, const ::openpilot_bridge::EncodeIndex_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.segmentId == rhs.segmentId &&
    lhs.segmentIdEncode == rhs.segmentIdEncode &&
    lhs.frameId == rhs.frameId &&
    lhs.encodeId == rhs.encodeId &&
    lhs.type == rhs.type &&
    lhs.segmentNum == rhs.segmentNum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::openpilot_bridge::EncodeIndex_<ContainerAllocator1> & lhs, const ::openpilot_bridge::EncodeIndex_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace openpilot_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::openpilot_bridge::EncodeIndex_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::openpilot_bridge::EncodeIndex_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpilot_bridge::EncodeIndex_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpilot_bridge::EncodeIndex_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpilot_bridge::EncodeIndex_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpilot_bridge::EncodeIndex_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::openpilot_bridge::EncodeIndex_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8777c88982f7111522c38f60cd2e924a";
  }

  static const char* value(const ::openpilot_bridge::EncodeIndex_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8777c88982f71115ULL;
  static const uint64_t static_value2 = 0x22c38f60cd2e924aULL;
};

template<class ContainerAllocator>
struct DataType< ::openpilot_bridge::EncodeIndex_<ContainerAllocator> >
{
  static const char* value()
  {
    return "openpilot_bridge/EncodeIndex";
  }

  static const char* value(const ::openpilot_bridge::EncodeIndex_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::openpilot_bridge::EncodeIndex_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"int64 segmentId\n"
"int64 segmentIdEncode\n"
"int64 frameId\n"
"int64 encodeId\n"
"uint32 type # enum const: Type\n"
"int32 segmentNum\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::openpilot_bridge::EncodeIndex_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::openpilot_bridge::EncodeIndex_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.segmentId);
      stream.next(m.segmentIdEncode);
      stream.next(m.frameId);
      stream.next(m.encodeId);
      stream.next(m.type);
      stream.next(m.segmentNum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EncodeIndex_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::openpilot_bridge::EncodeIndex_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::openpilot_bridge::EncodeIndex_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "segmentId: ";
    Printer<int64_t>::stream(s, indent + "  ", v.segmentId);
    s << indent << "segmentIdEncode: ";
    Printer<int64_t>::stream(s, indent + "  ", v.segmentIdEncode);
    s << indent << "frameId: ";
    Printer<int64_t>::stream(s, indent + "  ", v.frameId);
    s << indent << "encodeId: ";
    Printer<int64_t>::stream(s, indent + "  ", v.encodeId);
    s << indent << "type: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.type);
    s << indent << "segmentNum: ";
    Printer<int32_t>::stream(s, indent + "  ", v.segmentNum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPENPILOT_BRIDGE_MESSAGE_ENCODEINDEX_H
