// Generated by gencpp from file openpilot_bridge/FaultType.msg
// DO NOT EDIT!


#ifndef OPENPILOT_BRIDGE_MESSAGE_FAULTTYPE_H
#define OPENPILOT_BRIDGE_MESSAGE_FAULTTYPE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace openpilot_bridge
{
template <class ContainerAllocator>
struct FaultType_
{
  typedef FaultType_<ContainerAllocator> Type;

  FaultType_()
    {
    }
  FaultType_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }





// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(relayMalfunction)
  #undef relayMalfunction
#endif

  enum {
    relayMalfunction = 0u,
  };


  typedef boost::shared_ptr< ::openpilot_bridge::FaultType_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::openpilot_bridge::FaultType_<ContainerAllocator> const> ConstPtr;

}; // struct FaultType_

typedef ::openpilot_bridge::FaultType_<std::allocator<void> > FaultType;

typedef boost::shared_ptr< ::openpilot_bridge::FaultType > FaultTypePtr;
typedef boost::shared_ptr< ::openpilot_bridge::FaultType const> FaultTypeConstPtr;

// constants requiring out of line definition

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::openpilot_bridge::FaultType_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::openpilot_bridge::FaultType_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace openpilot_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::openpilot_bridge::FaultType_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::openpilot_bridge::FaultType_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpilot_bridge::FaultType_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpilot_bridge::FaultType_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpilot_bridge::FaultType_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpilot_bridge::FaultType_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::openpilot_bridge::FaultType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "197e186f39d4aadb0366bf19217c7333";
  }

  static const char* value(const ::openpilot_bridge::FaultType_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x197e186f39d4aadbULL;
  static const uint64_t static_value2 = 0x0366bf19217c7333ULL;
};

template<class ContainerAllocator>
struct DataType< ::openpilot_bridge::FaultType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "openpilot_bridge/FaultType";
  }

  static const char* value(const ::openpilot_bridge::FaultType_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::openpilot_bridge::FaultType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 relayMalfunction=0\n"
;
  }

  static const char* value(const ::openpilot_bridge::FaultType_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::openpilot_bridge::FaultType_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FaultType_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::openpilot_bridge::FaultType_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::openpilot_bridge::FaultType_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // OPENPILOT_BRIDGE_MESSAGE_FAULTTYPE_H
