// Generated by gencpp from file openpilot_bridge/GPSPlannerPlan.msg
// DO NOT EDIT!


#ifndef OPENPILOT_BRIDGE_MESSAGE_GPSPLANNERPLAN_H
#define OPENPILOT_BRIDGE_MESSAGE_GPSPLANNERPLAN_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <openpilot_bridge/ECEFPointDEPRECATED.h>
#include <openpilot_bridge/ECEFPoint.h>

namespace openpilot_bridge
{
template <class ContainerAllocator>
struct GPSPlannerPlan_
{
  typedef GPSPlannerPlan_<ContainerAllocator> Type;

  GPSPlannerPlan_()
    : header()
    , acceleration(0.0)
    , pointsDEPRECATED()
    , trackName()
    , poly()
    , xLookahead(0.0)
    , valid(false)
    , speed(0.0)
    , points()  {
    }
  GPSPlannerPlan_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , acceleration(0.0)
    , pointsDEPRECATED(_alloc)
    , trackName(_alloc)
    , poly(_alloc)
    , xLookahead(0.0)
    , valid(false)
    , speed(0.0)
    , points(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _acceleration_type;
  _acceleration_type acceleration;

   typedef std::vector< ::openpilot_bridge::ECEFPointDEPRECATED_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::openpilot_bridge::ECEFPointDEPRECATED_<ContainerAllocator> >::other >  _pointsDEPRECATED_type;
  _pointsDEPRECATED_type pointsDEPRECATED;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _trackName_type;
  _trackName_type trackName;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _poly_type;
  _poly_type poly;

   typedef float _xLookahead_type;
  _xLookahead_type xLookahead;

   typedef uint8_t _valid_type;
  _valid_type valid;

   typedef float _speed_type;
  _speed_type speed;

   typedef std::vector< ::openpilot_bridge::ECEFPoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::openpilot_bridge::ECEFPoint_<ContainerAllocator> >::other >  _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::openpilot_bridge::GPSPlannerPlan_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::openpilot_bridge::GPSPlannerPlan_<ContainerAllocator> const> ConstPtr;

}; // struct GPSPlannerPlan_

typedef ::openpilot_bridge::GPSPlannerPlan_<std::allocator<void> > GPSPlannerPlan;

typedef boost::shared_ptr< ::openpilot_bridge::GPSPlannerPlan > GPSPlannerPlanPtr;
typedef boost::shared_ptr< ::openpilot_bridge::GPSPlannerPlan const> GPSPlannerPlanConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::openpilot_bridge::GPSPlannerPlan_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::openpilot_bridge::GPSPlannerPlan_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::openpilot_bridge::GPSPlannerPlan_<ContainerAllocator1> & lhs, const ::openpilot_bridge::GPSPlannerPlan_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.acceleration == rhs.acceleration &&
    lhs.pointsDEPRECATED == rhs.pointsDEPRECATED &&
    lhs.trackName == rhs.trackName &&
    lhs.poly == rhs.poly &&
    lhs.xLookahead == rhs.xLookahead &&
    lhs.valid == rhs.valid &&
    lhs.speed == rhs.speed &&
    lhs.points == rhs.points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::openpilot_bridge::GPSPlannerPlan_<ContainerAllocator1> & lhs, const ::openpilot_bridge::GPSPlannerPlan_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace openpilot_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::openpilot_bridge::GPSPlannerPlan_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::openpilot_bridge::GPSPlannerPlan_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpilot_bridge::GPSPlannerPlan_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpilot_bridge::GPSPlannerPlan_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpilot_bridge::GPSPlannerPlan_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpilot_bridge::GPSPlannerPlan_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::openpilot_bridge::GPSPlannerPlan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "998c57b3107ccfd3fc1d648cdbc3c857";
  }

  static const char* value(const ::openpilot_bridge::GPSPlannerPlan_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x998c57b3107ccfd3ULL;
  static const uint64_t static_value2 = 0xfc1d648cdbc3c857ULL;
};

template<class ContainerAllocator>
struct DataType< ::openpilot_bridge::GPSPlannerPlan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "openpilot_bridge/GPSPlannerPlan";
  }

  static const char* value(const ::openpilot_bridge::GPSPlannerPlan_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::openpilot_bridge::GPSPlannerPlan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"float32 acceleration\n"
"ECEFPointDEPRECATED[] pointsDEPRECATED\n"
"string[] trackName\n"
"float32[] poly\n"
"float32 xLookahead\n"
"bool valid\n"
"float32 speed\n"
"ECEFPoint[] points\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: openpilot_bridge/ECEFPointDEPRECATED\n"
"Header header\n"
"\n"
"float32 y\n"
"float32 x\n"
"float32 z\n"
"\n"
"================================================================================\n"
"MSG: openpilot_bridge/ECEFPoint\n"
"Header header\n"
"\n"
"float32 y\n"
"float32 x\n"
"float32 z\n"
;
  }

  static const char* value(const ::openpilot_bridge::GPSPlannerPlan_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::openpilot_bridge::GPSPlannerPlan_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.acceleration);
      stream.next(m.pointsDEPRECATED);
      stream.next(m.trackName);
      stream.next(m.poly);
      stream.next(m.xLookahead);
      stream.next(m.valid);
      stream.next(m.speed);
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GPSPlannerPlan_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::openpilot_bridge::GPSPlannerPlan_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::openpilot_bridge::GPSPlannerPlan_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "acceleration: ";
    Printer<float>::stream(s, indent + "  ", v.acceleration);
    s << indent << "pointsDEPRECATED[]" << std::endl;
    for (size_t i = 0; i < v.pointsDEPRECATED.size(); ++i)
    {
      s << indent << "  pointsDEPRECATED[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::openpilot_bridge::ECEFPointDEPRECATED_<ContainerAllocator> >::stream(s, indent + "    ", v.pointsDEPRECATED[i]);
    }
    s << indent << "trackName[]" << std::endl;
    for (size_t i = 0; i < v.trackName.size(); ++i)
    {
      s << indent << "  trackName[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.trackName[i]);
    }
    s << indent << "poly[]" << std::endl;
    for (size_t i = 0; i < v.poly.size(); ++i)
    {
      s << indent << "  poly[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.poly[i]);
    }
    s << indent << "xLookahead: ";
    Printer<float>::stream(s, indent + "  ", v.xLookahead);
    s << indent << "valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.valid);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::openpilot_bridge::ECEFPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPENPILOT_BRIDGE_MESSAGE_GPSPLANNERPLAN_H
