// Generated by gencpp from file openpilot_bridge/HwType.msg
// DO NOT EDIT!


#ifndef OPENPILOT_BRIDGE_MESSAGE_HWTYPE_H
#define OPENPILOT_BRIDGE_MESSAGE_HWTYPE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace openpilot_bridge
{
template <class ContainerAllocator>
struct HwType_
{
  typedef HwType_<ContainerAllocator> Type;

  HwType_()
    {
    }
  HwType_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }





// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(greyPanda)
  #undef greyPanda
#endif
#if defined(_WIN32) && defined(unknown)
  #undef unknown
#endif
#if defined(_WIN32) && defined(blackPanda)
  #undef blackPanda
#endif
#if defined(_WIN32) && defined(pedal)
  #undef pedal
#endif
#if defined(_WIN32) && defined(whitePanda)
  #undef whitePanda
#endif
#if defined(_WIN32) && defined(uno)
  #undef uno
#endif

  enum {
    greyPanda = 2u,
    unknown = 0u,
    blackPanda = 3u,
    pedal = 4u,
    whitePanda = 1u,
    uno = 5u,
  };


  typedef boost::shared_ptr< ::openpilot_bridge::HwType_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::openpilot_bridge::HwType_<ContainerAllocator> const> ConstPtr;

}; // struct HwType_

typedef ::openpilot_bridge::HwType_<std::allocator<void> > HwType;

typedef boost::shared_ptr< ::openpilot_bridge::HwType > HwTypePtr;
typedef boost::shared_ptr< ::openpilot_bridge::HwType const> HwTypeConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::openpilot_bridge::HwType_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::openpilot_bridge::HwType_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace openpilot_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::openpilot_bridge::HwType_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::openpilot_bridge::HwType_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpilot_bridge::HwType_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpilot_bridge::HwType_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpilot_bridge::HwType_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpilot_bridge::HwType_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::openpilot_bridge::HwType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "75860a38b6f0e635f9859e3fbce3d516";
  }

  static const char* value(const ::openpilot_bridge::HwType_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x75860a38b6f0e635ULL;
  static const uint64_t static_value2 = 0xf9859e3fbce3d516ULL;
};

template<class ContainerAllocator>
struct DataType< ::openpilot_bridge::HwType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "openpilot_bridge/HwType";
  }

  static const char* value(const ::openpilot_bridge::HwType_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::openpilot_bridge::HwType_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 greyPanda=2\n"
"uint32 unknown=0\n"
"uint32 blackPanda=3\n"
"uint32 pedal=4\n"
"uint32 whitePanda=1\n"
"uint32 uno=5\n"
;
  }

  static const char* value(const ::openpilot_bridge::HwType_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::openpilot_bridge::HwType_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HwType_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::openpilot_bridge::HwType_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::openpilot_bridge::HwType_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // OPENPILOT_BRIDGE_MESSAGE_HWTYPE_H
