// Generated by gencpp from file openpilot_bridge/LiveParametersData.msg
// DO NOT EDIT!


#ifndef OPENPILOT_BRIDGE_MESSAGE_LIVEPARAMETERSDATA_H
#define OPENPILOT_BRIDGE_MESSAGE_LIVEPARAMETERSDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace openpilot_bridge
{
template <class ContainerAllocator>
struct LiveParametersData_
{
  typedef LiveParametersData_<ContainerAllocator> Type;

  LiveParametersData_()
    : header()
    , steerRatio(0.0)
    , sensorValid(false)
    , stiffnessFactor(0.0)
    , posenetValid(false)
    , angleOffset(0.0)
    , yawRate(0.0)
    , gyroBias(0.0)
    , valid(false)
    , posenetSpeed(0.0)
    , angleOffsetAverage(0.0)  {
    }
  LiveParametersData_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , steerRatio(0.0)
    , sensorValid(false)
    , stiffnessFactor(0.0)
    , posenetValid(false)
    , angleOffset(0.0)
    , yawRate(0.0)
    , gyroBias(0.0)
    , valid(false)
    , posenetSpeed(0.0)
    , angleOffsetAverage(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _steerRatio_type;
  _steerRatio_type steerRatio;

   typedef uint8_t _sensorValid_type;
  _sensorValid_type sensorValid;

   typedef float _stiffnessFactor_type;
  _stiffnessFactor_type stiffnessFactor;

   typedef uint8_t _posenetValid_type;
  _posenetValid_type posenetValid;

   typedef float _angleOffset_type;
  _angleOffset_type angleOffset;

   typedef float _yawRate_type;
  _yawRate_type yawRate;

   typedef float _gyroBias_type;
  _gyroBias_type gyroBias;

   typedef uint8_t _valid_type;
  _valid_type valid;

   typedef float _posenetSpeed_type;
  _posenetSpeed_type posenetSpeed;

   typedef float _angleOffsetAverage_type;
  _angleOffsetAverage_type angleOffsetAverage;





  typedef boost::shared_ptr< ::openpilot_bridge::LiveParametersData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::openpilot_bridge::LiveParametersData_<ContainerAllocator> const> ConstPtr;

}; // struct LiveParametersData_

typedef ::openpilot_bridge::LiveParametersData_<std::allocator<void> > LiveParametersData;

typedef boost::shared_ptr< ::openpilot_bridge::LiveParametersData > LiveParametersDataPtr;
typedef boost::shared_ptr< ::openpilot_bridge::LiveParametersData const> LiveParametersDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::openpilot_bridge::LiveParametersData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::openpilot_bridge::LiveParametersData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::openpilot_bridge::LiveParametersData_<ContainerAllocator1> & lhs, const ::openpilot_bridge::LiveParametersData_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.steerRatio == rhs.steerRatio &&
    lhs.sensorValid == rhs.sensorValid &&
    lhs.stiffnessFactor == rhs.stiffnessFactor &&
    lhs.posenetValid == rhs.posenetValid &&
    lhs.angleOffset == rhs.angleOffset &&
    lhs.yawRate == rhs.yawRate &&
    lhs.gyroBias == rhs.gyroBias &&
    lhs.valid == rhs.valid &&
    lhs.posenetSpeed == rhs.posenetSpeed &&
    lhs.angleOffsetAverage == rhs.angleOffsetAverage;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::openpilot_bridge::LiveParametersData_<ContainerAllocator1> & lhs, const ::openpilot_bridge::LiveParametersData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace openpilot_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::openpilot_bridge::LiveParametersData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::openpilot_bridge::LiveParametersData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpilot_bridge::LiveParametersData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpilot_bridge::LiveParametersData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpilot_bridge::LiveParametersData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpilot_bridge::LiveParametersData_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::openpilot_bridge::LiveParametersData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2c7f16316c870354eebb72d972911e81";
  }

  static const char* value(const ::openpilot_bridge::LiveParametersData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2c7f16316c870354ULL;
  static const uint64_t static_value2 = 0xeebb72d972911e81ULL;
};

template<class ContainerAllocator>
struct DataType< ::openpilot_bridge::LiveParametersData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "openpilot_bridge/LiveParametersData";
  }

  static const char* value(const ::openpilot_bridge::LiveParametersData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::openpilot_bridge::LiveParametersData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"float32 steerRatio\n"
"bool sensorValid\n"
"float32 stiffnessFactor\n"
"bool posenetValid\n"
"float32 angleOffset\n"
"float32 yawRate\n"
"float32 gyroBias\n"
"bool valid\n"
"float32 posenetSpeed\n"
"float32 angleOffsetAverage\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::openpilot_bridge::LiveParametersData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::openpilot_bridge::LiveParametersData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.steerRatio);
      stream.next(m.sensorValid);
      stream.next(m.stiffnessFactor);
      stream.next(m.posenetValid);
      stream.next(m.angleOffset);
      stream.next(m.yawRate);
      stream.next(m.gyroBias);
      stream.next(m.valid);
      stream.next(m.posenetSpeed);
      stream.next(m.angleOffsetAverage);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LiveParametersData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::openpilot_bridge::LiveParametersData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::openpilot_bridge::LiveParametersData_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "steerRatio: ";
    Printer<float>::stream(s, indent + "  ", v.steerRatio);
    s << indent << "sensorValid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sensorValid);
    s << indent << "stiffnessFactor: ";
    Printer<float>::stream(s, indent + "  ", v.stiffnessFactor);
    s << indent << "posenetValid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.posenetValid);
    s << indent << "angleOffset: ";
    Printer<float>::stream(s, indent + "  ", v.angleOffset);
    s << indent << "yawRate: ";
    Printer<float>::stream(s, indent + "  ", v.yawRate);
    s << indent << "gyroBias: ";
    Printer<float>::stream(s, indent + "  ", v.gyroBias);
    s << indent << "valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.valid);
    s << indent << "posenetSpeed: ";
    Printer<float>::stream(s, indent + "  ", v.posenetSpeed);
    s << indent << "angleOffsetAverage: ";
    Printer<float>::stream(s, indent + "  ", v.angleOffsetAverage);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPENPILOT_BRIDGE_MESSAGE_LIVEPARAMETERSDATA_H
