// Generated by gencpp from file openpilot_bridge/OrbFeaturesSummary.msg
// DO NOT EDIT!


#ifndef OPENPILOT_BRIDGE_MESSAGE_ORBFEATURESSUMMARY_H
#define OPENPILOT_BRIDGE_MESSAGE_ORBFEATURESSUMMARY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace openpilot_bridge
{
template <class ContainerAllocator>
struct OrbFeaturesSummary_
{
  typedef OrbFeaturesSummary_<ContainerAllocator> Type;

  OrbFeaturesSummary_()
    : header()
    , timestampEof(0)
    , featureCount(0)
    , matchCount(0)
    , timestampLastEof(0)
    , computeNs(0)  {
    }
  OrbFeaturesSummary_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , timestampEof(0)
    , featureCount(0)
    , matchCount(0)
    , timestampLastEof(0)
    , computeNs(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int64_t _timestampEof_type;
  _timestampEof_type timestampEof;

   typedef int64_t _featureCount_type;
  _featureCount_type featureCount;

   typedef int64_t _matchCount_type;
  _matchCount_type matchCount;

   typedef int64_t _timestampLastEof_type;
  _timestampLastEof_type timestampLastEof;

   typedef int64_t _computeNs_type;
  _computeNs_type computeNs;





  typedef boost::shared_ptr< ::openpilot_bridge::OrbFeaturesSummary_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::openpilot_bridge::OrbFeaturesSummary_<ContainerAllocator> const> ConstPtr;

}; // struct OrbFeaturesSummary_

typedef ::openpilot_bridge::OrbFeaturesSummary_<std::allocator<void> > OrbFeaturesSummary;

typedef boost::shared_ptr< ::openpilot_bridge::OrbFeaturesSummary > OrbFeaturesSummaryPtr;
typedef boost::shared_ptr< ::openpilot_bridge::OrbFeaturesSummary const> OrbFeaturesSummaryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::openpilot_bridge::OrbFeaturesSummary_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::openpilot_bridge::OrbFeaturesSummary_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::openpilot_bridge::OrbFeaturesSummary_<ContainerAllocator1> & lhs, const ::openpilot_bridge::OrbFeaturesSummary_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.timestampEof == rhs.timestampEof &&
    lhs.featureCount == rhs.featureCount &&
    lhs.matchCount == rhs.matchCount &&
    lhs.timestampLastEof == rhs.timestampLastEof &&
    lhs.computeNs == rhs.computeNs;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::openpilot_bridge::OrbFeaturesSummary_<ContainerAllocator1> & lhs, const ::openpilot_bridge::OrbFeaturesSummary_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace openpilot_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::openpilot_bridge::OrbFeaturesSummary_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::openpilot_bridge::OrbFeaturesSummary_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpilot_bridge::OrbFeaturesSummary_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpilot_bridge::OrbFeaturesSummary_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpilot_bridge::OrbFeaturesSummary_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpilot_bridge::OrbFeaturesSummary_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::openpilot_bridge::OrbFeaturesSummary_<ContainerAllocator> >
{
  static const char* value()
  {
    return "afb40913cace05ea0c7922dff3fa207f";
  }

  static const char* value(const ::openpilot_bridge::OrbFeaturesSummary_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xafb40913cace05eaULL;
  static const uint64_t static_value2 = 0x0c7922dff3fa207fULL;
};

template<class ContainerAllocator>
struct DataType< ::openpilot_bridge::OrbFeaturesSummary_<ContainerAllocator> >
{
  static const char* value()
  {
    return "openpilot_bridge/OrbFeaturesSummary";
  }

  static const char* value(const ::openpilot_bridge::OrbFeaturesSummary_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::openpilot_bridge::OrbFeaturesSummary_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"int64 timestampEof\n"
"int64 featureCount\n"
"int64 matchCount\n"
"int64 timestampLastEof\n"
"int64 computeNs\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::openpilot_bridge::OrbFeaturesSummary_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::openpilot_bridge::OrbFeaturesSummary_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.timestampEof);
      stream.next(m.featureCount);
      stream.next(m.matchCount);
      stream.next(m.timestampLastEof);
      stream.next(m.computeNs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OrbFeaturesSummary_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::openpilot_bridge::OrbFeaturesSummary_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::openpilot_bridge::OrbFeaturesSummary_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "timestampEof: ";
    Printer<int64_t>::stream(s, indent + "  ", v.timestampEof);
    s << indent << "featureCount: ";
    Printer<int64_t>::stream(s, indent + "  ", v.featureCount);
    s << indent << "matchCount: ";
    Printer<int64_t>::stream(s, indent + "  ", v.matchCount);
    s << indent << "timestampLastEof: ";
    Printer<int64_t>::stream(s, indent + "  ", v.timestampLastEof);
    s << indent << "computeNs: ";
    Printer<int64_t>::stream(s, indent + "  ", v.computeNs);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPENPILOT_BRIDGE_MESSAGE_ORBFEATURESSUMMARY_H
