// Generated by gencpp from file openpilot_bridge/OrbObservation.msg
// DO NOT EDIT!


#ifndef OPENPILOT_BRIDGE_MESSAGE_ORBOBSERVATION_H
#define OPENPILOT_BRIDGE_MESSAGE_ORBOBSERVATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace openpilot_bridge
{
template <class ContainerAllocator>
struct OrbObservation_
{
  typedef OrbObservation_<ContainerAllocator> Type;

  OrbObservation_()
    : header()
    , matchDistance(0)
    , locationECEF()
    , normalizedCoordinates()
    , observationMonoTime(0)  {
    }
  OrbObservation_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , matchDistance(0)
    , locationECEF(_alloc)
    , normalizedCoordinates(_alloc)
    , observationMonoTime(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int64_t _matchDistance_type;
  _matchDistance_type matchDistance;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _locationECEF_type;
  _locationECEF_type locationECEF;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _normalizedCoordinates_type;
  _normalizedCoordinates_type normalizedCoordinates;

   typedef int64_t _observationMonoTime_type;
  _observationMonoTime_type observationMonoTime;





  typedef boost::shared_ptr< ::openpilot_bridge::OrbObservation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::openpilot_bridge::OrbObservation_<ContainerAllocator> const> ConstPtr;

}; // struct OrbObservation_

typedef ::openpilot_bridge::OrbObservation_<std::allocator<void> > OrbObservation;

typedef boost::shared_ptr< ::openpilot_bridge::OrbObservation > OrbObservationPtr;
typedef boost::shared_ptr< ::openpilot_bridge::OrbObservation const> OrbObservationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::openpilot_bridge::OrbObservation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::openpilot_bridge::OrbObservation_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::openpilot_bridge::OrbObservation_<ContainerAllocator1> & lhs, const ::openpilot_bridge::OrbObservation_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.matchDistance == rhs.matchDistance &&
    lhs.locationECEF == rhs.locationECEF &&
    lhs.normalizedCoordinates == rhs.normalizedCoordinates &&
    lhs.observationMonoTime == rhs.observationMonoTime;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::openpilot_bridge::OrbObservation_<ContainerAllocator1> & lhs, const ::openpilot_bridge::OrbObservation_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace openpilot_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::openpilot_bridge::OrbObservation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::openpilot_bridge::OrbObservation_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpilot_bridge::OrbObservation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpilot_bridge::OrbObservation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpilot_bridge::OrbObservation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpilot_bridge::OrbObservation_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::openpilot_bridge::OrbObservation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6de73ce37ca42db3178ce06f49587a3a";
  }

  static const char* value(const ::openpilot_bridge::OrbObservation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6de73ce37ca42db3ULL;
  static const uint64_t static_value2 = 0x178ce06f49587a3aULL;
};

template<class ContainerAllocator>
struct DataType< ::openpilot_bridge::OrbObservation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "openpilot_bridge/OrbObservation";
  }

  static const char* value(const ::openpilot_bridge::OrbObservation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::openpilot_bridge::OrbObservation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"int64 matchDistance\n"
"float32[] locationECEF\n"
"float32[] normalizedCoordinates\n"
"int64 observationMonoTime\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::openpilot_bridge::OrbObservation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::openpilot_bridge::OrbObservation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.matchDistance);
      stream.next(m.locationECEF);
      stream.next(m.normalizedCoordinates);
      stream.next(m.observationMonoTime);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OrbObservation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::openpilot_bridge::OrbObservation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::openpilot_bridge::OrbObservation_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "matchDistance: ";
    Printer<int64_t>::stream(s, indent + "  ", v.matchDistance);
    s << indent << "locationECEF[]" << std::endl;
    for (size_t i = 0; i < v.locationECEF.size(); ++i)
    {
      s << indent << "  locationECEF[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.locationECEF[i]);
    }
    s << indent << "normalizedCoordinates[]" << std::endl;
    for (size_t i = 0; i < v.normalizedCoordinates.size(); ++i)
    {
      s << indent << "  normalizedCoordinates[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.normalizedCoordinates[i]);
    }
    s << indent << "observationMonoTime: ";
    Printer<int64_t>::stream(s, indent + "  ", v.observationMonoTime);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPENPILOT_BRIDGE_MESSAGE_ORBOBSERVATION_H
