// Generated by gencpp from file openpilot_bridge/OrbslamCorrection.msg
// DO NOT EDIT!


#ifndef OPENPILOT_BRIDGE_MESSAGE_ORBSLAMCORRECTION_H
#define OPENPILOT_BRIDGE_MESSAGE_ORBSLAMCORRECTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace openpilot_bridge
{
template <class ContainerAllocator>
struct OrbslamCorrection_
{
  typedef OrbslamCorrection_<ContainerAllocator> Type;

  OrbslamCorrection_()
    : header()
    , correctionMonoTime(0)
    , prePositionECEF()
    , postPositionECEF()
    , postPoseQuatECEF()
    , numInliers(0)
    , prePoseQuatECEF()  {
    }
  OrbslamCorrection_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , correctionMonoTime(0)
    , prePositionECEF(_alloc)
    , postPositionECEF(_alloc)
    , postPoseQuatECEF(_alloc)
    , numInliers(0)
    , prePoseQuatECEF(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int64_t _correctionMonoTime_type;
  _correctionMonoTime_type correctionMonoTime;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _prePositionECEF_type;
  _prePositionECEF_type prePositionECEF;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _postPositionECEF_type;
  _postPositionECEF_type postPositionECEF;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _postPoseQuatECEF_type;
  _postPoseQuatECEF_type postPoseQuatECEF;

   typedef int64_t _numInliers_type;
  _numInliers_type numInliers;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _prePoseQuatECEF_type;
  _prePoseQuatECEF_type prePoseQuatECEF;





  typedef boost::shared_ptr< ::openpilot_bridge::OrbslamCorrection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::openpilot_bridge::OrbslamCorrection_<ContainerAllocator> const> ConstPtr;

}; // struct OrbslamCorrection_

typedef ::openpilot_bridge::OrbslamCorrection_<std::allocator<void> > OrbslamCorrection;

typedef boost::shared_ptr< ::openpilot_bridge::OrbslamCorrection > OrbslamCorrectionPtr;
typedef boost::shared_ptr< ::openpilot_bridge::OrbslamCorrection const> OrbslamCorrectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::openpilot_bridge::OrbslamCorrection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::openpilot_bridge::OrbslamCorrection_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::openpilot_bridge::OrbslamCorrection_<ContainerAllocator1> & lhs, const ::openpilot_bridge::OrbslamCorrection_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.correctionMonoTime == rhs.correctionMonoTime &&
    lhs.prePositionECEF == rhs.prePositionECEF &&
    lhs.postPositionECEF == rhs.postPositionECEF &&
    lhs.postPoseQuatECEF == rhs.postPoseQuatECEF &&
    lhs.numInliers == rhs.numInliers &&
    lhs.prePoseQuatECEF == rhs.prePoseQuatECEF;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::openpilot_bridge::OrbslamCorrection_<ContainerAllocator1> & lhs, const ::openpilot_bridge::OrbslamCorrection_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace openpilot_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::openpilot_bridge::OrbslamCorrection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::openpilot_bridge::OrbslamCorrection_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpilot_bridge::OrbslamCorrection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpilot_bridge::OrbslamCorrection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpilot_bridge::OrbslamCorrection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpilot_bridge::OrbslamCorrection_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::openpilot_bridge::OrbslamCorrection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5782313d8262eba95695c847d7e1398d";
  }

  static const char* value(const ::openpilot_bridge::OrbslamCorrection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5782313d8262eba9ULL;
  static const uint64_t static_value2 = 0x5695c847d7e1398dULL;
};

template<class ContainerAllocator>
struct DataType< ::openpilot_bridge::OrbslamCorrection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "openpilot_bridge/OrbslamCorrection";
  }

  static const char* value(const ::openpilot_bridge::OrbslamCorrection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::openpilot_bridge::OrbslamCorrection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"int64 correctionMonoTime\n"
"float32[] prePositionECEF\n"
"float32[] postPositionECEF\n"
"float32[] postPoseQuatECEF\n"
"int64 numInliers\n"
"float32[] prePoseQuatECEF\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::openpilot_bridge::OrbslamCorrection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::openpilot_bridge::OrbslamCorrection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.correctionMonoTime);
      stream.next(m.prePositionECEF);
      stream.next(m.postPositionECEF);
      stream.next(m.postPoseQuatECEF);
      stream.next(m.numInliers);
      stream.next(m.prePoseQuatECEF);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OrbslamCorrection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::openpilot_bridge::OrbslamCorrection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::openpilot_bridge::OrbslamCorrection_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "correctionMonoTime: ";
    Printer<int64_t>::stream(s, indent + "  ", v.correctionMonoTime);
    s << indent << "prePositionECEF[]" << std::endl;
    for (size_t i = 0; i < v.prePositionECEF.size(); ++i)
    {
      s << indent << "  prePositionECEF[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.prePositionECEF[i]);
    }
    s << indent << "postPositionECEF[]" << std::endl;
    for (size_t i = 0; i < v.postPositionECEF.size(); ++i)
    {
      s << indent << "  postPositionECEF[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.postPositionECEF[i]);
    }
    s << indent << "postPoseQuatECEF[]" << std::endl;
    for (size_t i = 0; i < v.postPoseQuatECEF.size(); ++i)
    {
      s << indent << "  postPoseQuatECEF[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.postPoseQuatECEF[i]);
    }
    s << indent << "numInliers: ";
    Printer<int64_t>::stream(s, indent + "  ", v.numInliers);
    s << indent << "prePoseQuatECEF[]" << std::endl;
    for (size_t i = 0; i < v.prePoseQuatECEF.size(); ++i)
    {
      s << indent << "  prePoseQuatECEF[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.prePoseQuatECEF[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPENPILOT_BRIDGE_MESSAGE_ORBSLAMCORRECTION_H
