// Generated by gencpp from file openpilot_bridge/Plan.msg
// DO NOT EDIT!


#ifndef OPENPILOT_BRIDGE_MESSAGE_PLAN_H
#define OPENPILOT_BRIDGE_MESSAGE_PLAN_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <openpilot_bridge/CarEvent.h>
#include <openpilot_bridge/GpsTrajectory.h>

namespace openpilot_bridge
{
template <class ContainerAllocator>
struct Plan_
{
  typedef Plan_<ContainerAllocator> Type;

  Plan_()
    : header()
    , decelForTurn(false)
    , vTarget(0.0)
    , lateralValidDEPRECATED(false)
    , longitudinalPlanSource(0)
    , hasLead(false)
    , radarStateMonoTime(0)
    , jerkFactor(0.0)
    , vCurvature(0.0)
    , aTarget(0.0)
    , mdMonoTime(0)
    , aTargetMaxDEPRECATED(0.0)
    , laneWidthDEPRECATED(0.0)
    , radarValid(false)
    , gpsPlannerActive(false)
    , fcw(false)
    , processingDelay(0.0)
    , longitudinalValidDEPRECATED(false)
    , aStart(0.0)
    , eventsDEPRECATED()
    , hasRightLaneDEPRECATED(false)
    , vStart(0.0)
    , aCruise(0.0)
    , commIssue(false)
    , vTargetFuture(0.0)
    , gpsTrajectory()
    , hasLeftLaneDEPRECATED(false)
    , vCruise(0.0)
    , aTargetMinDEPRECATED(0.0)
    , mapValid(false)
    , radarCanError(false)
    , vMax(0.0)
    , dPolyDEPRECATED()  {
    }
  Plan_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , decelForTurn(false)
    , vTarget(0.0)
    , lateralValidDEPRECATED(false)
    , longitudinalPlanSource(0)
    , hasLead(false)
    , radarStateMonoTime(0)
    , jerkFactor(0.0)
    , vCurvature(0.0)
    , aTarget(0.0)
    , mdMonoTime(0)
    , aTargetMaxDEPRECATED(0.0)
    , laneWidthDEPRECATED(0.0)
    , radarValid(false)
    , gpsPlannerActive(false)
    , fcw(false)
    , processingDelay(0.0)
    , longitudinalValidDEPRECATED(false)
    , aStart(0.0)
    , eventsDEPRECATED(_alloc)
    , hasRightLaneDEPRECATED(false)
    , vStart(0.0)
    , aCruise(0.0)
    , commIssue(false)
    , vTargetFuture(0.0)
    , gpsTrajectory(_alloc)
    , hasLeftLaneDEPRECATED(false)
    , vCruise(0.0)
    , aTargetMinDEPRECATED(0.0)
    , mapValid(false)
    , radarCanError(false)
    , vMax(0.0)
    , dPolyDEPRECATED(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _decelForTurn_type;
  _decelForTurn_type decelForTurn;

   typedef float _vTarget_type;
  _vTarget_type vTarget;

   typedef uint8_t _lateralValidDEPRECATED_type;
  _lateralValidDEPRECATED_type lateralValidDEPRECATED;

   typedef uint32_t _longitudinalPlanSource_type;
  _longitudinalPlanSource_type longitudinalPlanSource;

   typedef uint8_t _hasLead_type;
  _hasLead_type hasLead;

   typedef int64_t _radarStateMonoTime_type;
  _radarStateMonoTime_type radarStateMonoTime;

   typedef float _jerkFactor_type;
  _jerkFactor_type jerkFactor;

   typedef float _vCurvature_type;
  _vCurvature_type vCurvature;

   typedef float _aTarget_type;
  _aTarget_type aTarget;

   typedef int64_t _mdMonoTime_type;
  _mdMonoTime_type mdMonoTime;

   typedef float _aTargetMaxDEPRECATED_type;
  _aTargetMaxDEPRECATED_type aTargetMaxDEPRECATED;

   typedef float _laneWidthDEPRECATED_type;
  _laneWidthDEPRECATED_type laneWidthDEPRECATED;

   typedef uint8_t _radarValid_type;
  _radarValid_type radarValid;

   typedef uint8_t _gpsPlannerActive_type;
  _gpsPlannerActive_type gpsPlannerActive;

   typedef uint8_t _fcw_type;
  _fcw_type fcw;

   typedef float _processingDelay_type;
  _processingDelay_type processingDelay;

   typedef uint8_t _longitudinalValidDEPRECATED_type;
  _longitudinalValidDEPRECATED_type longitudinalValidDEPRECATED;

   typedef float _aStart_type;
  _aStart_type aStart;

   typedef std::vector< ::openpilot_bridge::CarEvent_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::openpilot_bridge::CarEvent_<ContainerAllocator> >::other >  _eventsDEPRECATED_type;
  _eventsDEPRECATED_type eventsDEPRECATED;

   typedef uint8_t _hasRightLaneDEPRECATED_type;
  _hasRightLaneDEPRECATED_type hasRightLaneDEPRECATED;

   typedef float _vStart_type;
  _vStart_type vStart;

   typedef float _aCruise_type;
  _aCruise_type aCruise;

   typedef uint8_t _commIssue_type;
  _commIssue_type commIssue;

   typedef float _vTargetFuture_type;
  _vTargetFuture_type vTargetFuture;

   typedef  ::openpilot_bridge::GpsTrajectory_<ContainerAllocator>  _gpsTrajectory_type;
  _gpsTrajectory_type gpsTrajectory;

   typedef uint8_t _hasLeftLaneDEPRECATED_type;
  _hasLeftLaneDEPRECATED_type hasLeftLaneDEPRECATED;

   typedef float _vCruise_type;
  _vCruise_type vCruise;

   typedef float _aTargetMinDEPRECATED_type;
  _aTargetMinDEPRECATED_type aTargetMinDEPRECATED;

   typedef uint8_t _mapValid_type;
  _mapValid_type mapValid;

   typedef uint8_t _radarCanError_type;
  _radarCanError_type radarCanError;

   typedef float _vMax_type;
  _vMax_type vMax;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _dPolyDEPRECATED_type;
  _dPolyDEPRECATED_type dPolyDEPRECATED;





  typedef boost::shared_ptr< ::openpilot_bridge::Plan_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::openpilot_bridge::Plan_<ContainerAllocator> const> ConstPtr;

}; // struct Plan_

typedef ::openpilot_bridge::Plan_<std::allocator<void> > Plan;

typedef boost::shared_ptr< ::openpilot_bridge::Plan > PlanPtr;
typedef boost::shared_ptr< ::openpilot_bridge::Plan const> PlanConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::openpilot_bridge::Plan_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::openpilot_bridge::Plan_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::openpilot_bridge::Plan_<ContainerAllocator1> & lhs, const ::openpilot_bridge::Plan_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.decelForTurn == rhs.decelForTurn &&
    lhs.vTarget == rhs.vTarget &&
    lhs.lateralValidDEPRECATED == rhs.lateralValidDEPRECATED &&
    lhs.longitudinalPlanSource == rhs.longitudinalPlanSource &&
    lhs.hasLead == rhs.hasLead &&
    lhs.radarStateMonoTime == rhs.radarStateMonoTime &&
    lhs.jerkFactor == rhs.jerkFactor &&
    lhs.vCurvature == rhs.vCurvature &&
    lhs.aTarget == rhs.aTarget &&
    lhs.mdMonoTime == rhs.mdMonoTime &&
    lhs.aTargetMaxDEPRECATED == rhs.aTargetMaxDEPRECATED &&
    lhs.laneWidthDEPRECATED == rhs.laneWidthDEPRECATED &&
    lhs.radarValid == rhs.radarValid &&
    lhs.gpsPlannerActive == rhs.gpsPlannerActive &&
    lhs.fcw == rhs.fcw &&
    lhs.processingDelay == rhs.processingDelay &&
    lhs.longitudinalValidDEPRECATED == rhs.longitudinalValidDEPRECATED &&
    lhs.aStart == rhs.aStart &&
    lhs.eventsDEPRECATED == rhs.eventsDEPRECATED &&
    lhs.hasRightLaneDEPRECATED == rhs.hasRightLaneDEPRECATED &&
    lhs.vStart == rhs.vStart &&
    lhs.aCruise == rhs.aCruise &&
    lhs.commIssue == rhs.commIssue &&
    lhs.vTargetFuture == rhs.vTargetFuture &&
    lhs.gpsTrajectory == rhs.gpsTrajectory &&
    lhs.hasLeftLaneDEPRECATED == rhs.hasLeftLaneDEPRECATED &&
    lhs.vCruise == rhs.vCruise &&
    lhs.aTargetMinDEPRECATED == rhs.aTargetMinDEPRECATED &&
    lhs.mapValid == rhs.mapValid &&
    lhs.radarCanError == rhs.radarCanError &&
    lhs.vMax == rhs.vMax &&
    lhs.dPolyDEPRECATED == rhs.dPolyDEPRECATED;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::openpilot_bridge::Plan_<ContainerAllocator1> & lhs, const ::openpilot_bridge::Plan_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace openpilot_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::openpilot_bridge::Plan_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::openpilot_bridge::Plan_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpilot_bridge::Plan_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpilot_bridge::Plan_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpilot_bridge::Plan_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpilot_bridge::Plan_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::openpilot_bridge::Plan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5122b757463340c2ae5f629a57ec2ba5";
  }

  static const char* value(const ::openpilot_bridge::Plan_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5122b757463340c2ULL;
  static const uint64_t static_value2 = 0xae5f629a57ec2ba5ULL;
};

template<class ContainerAllocator>
struct DataType< ::openpilot_bridge::Plan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "openpilot_bridge/Plan";
  }

  static const char* value(const ::openpilot_bridge::Plan_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::openpilot_bridge::Plan_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"bool decelForTurn\n"
"float32 vTarget\n"
"bool lateralValidDEPRECATED\n"
"uint32 longitudinalPlanSource # enum const: LongitudinalPlanSource\n"
"bool hasLead\n"
"int64 radarStateMonoTime\n"
"float32 jerkFactor\n"
"float32 vCurvature\n"
"float32 aTarget\n"
"int64 mdMonoTime\n"
"float32 aTargetMaxDEPRECATED\n"
"float32 laneWidthDEPRECATED\n"
"bool radarValid\n"
"bool gpsPlannerActive\n"
"bool fcw\n"
"float32 processingDelay\n"
"bool longitudinalValidDEPRECATED\n"
"float32 aStart\n"
"CarEvent[] eventsDEPRECATED\n"
"bool hasRightLaneDEPRECATED\n"
"float32 vStart\n"
"float32 aCruise\n"
"bool commIssue\n"
"float32 vTargetFuture\n"
"GpsTrajectory gpsTrajectory\n"
"bool hasLeftLaneDEPRECATED\n"
"float32 vCruise\n"
"float32 aTargetMinDEPRECATED\n"
"bool mapValid\n"
"bool radarCanError\n"
"float32 vMax\n"
"float32[] dPolyDEPRECATED\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: openpilot_bridge/CarEvent\n"
"Header header\n"
"\n"
"bool enable\n"
"bool noEntry\n"
"uint32 name # enum const: EventName\n"
"bool immediateDisable\n"
"bool warning\n"
"bool permanent\n"
"bool softDisable\n"
"bool userDisable\n"
"bool preEnable\n"
"\n"
"================================================================================\n"
"MSG: openpilot_bridge/GpsTrajectory\n"
"Header header\n"
"\n"
"float32[] y\n"
"float32[] x\n"
;
  }

  static const char* value(const ::openpilot_bridge::Plan_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::openpilot_bridge::Plan_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.decelForTurn);
      stream.next(m.vTarget);
      stream.next(m.lateralValidDEPRECATED);
      stream.next(m.longitudinalPlanSource);
      stream.next(m.hasLead);
      stream.next(m.radarStateMonoTime);
      stream.next(m.jerkFactor);
      stream.next(m.vCurvature);
      stream.next(m.aTarget);
      stream.next(m.mdMonoTime);
      stream.next(m.aTargetMaxDEPRECATED);
      stream.next(m.laneWidthDEPRECATED);
      stream.next(m.radarValid);
      stream.next(m.gpsPlannerActive);
      stream.next(m.fcw);
      stream.next(m.processingDelay);
      stream.next(m.longitudinalValidDEPRECATED);
      stream.next(m.aStart);
      stream.next(m.eventsDEPRECATED);
      stream.next(m.hasRightLaneDEPRECATED);
      stream.next(m.vStart);
      stream.next(m.aCruise);
      stream.next(m.commIssue);
      stream.next(m.vTargetFuture);
      stream.next(m.gpsTrajectory);
      stream.next(m.hasLeftLaneDEPRECATED);
      stream.next(m.vCruise);
      stream.next(m.aTargetMinDEPRECATED);
      stream.next(m.mapValid);
      stream.next(m.radarCanError);
      stream.next(m.vMax);
      stream.next(m.dPolyDEPRECATED);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Plan_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::openpilot_bridge::Plan_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::openpilot_bridge::Plan_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "decelForTurn: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.decelForTurn);
    s << indent << "vTarget: ";
    Printer<float>::stream(s, indent + "  ", v.vTarget);
    s << indent << "lateralValidDEPRECATED: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.lateralValidDEPRECATED);
    s << indent << "longitudinalPlanSource: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.longitudinalPlanSource);
    s << indent << "hasLead: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.hasLead);
    s << indent << "radarStateMonoTime: ";
    Printer<int64_t>::stream(s, indent + "  ", v.radarStateMonoTime);
    s << indent << "jerkFactor: ";
    Printer<float>::stream(s, indent + "  ", v.jerkFactor);
    s << indent << "vCurvature: ";
    Printer<float>::stream(s, indent + "  ", v.vCurvature);
    s << indent << "aTarget: ";
    Printer<float>::stream(s, indent + "  ", v.aTarget);
    s << indent << "mdMonoTime: ";
    Printer<int64_t>::stream(s, indent + "  ", v.mdMonoTime);
    s << indent << "aTargetMaxDEPRECATED: ";
    Printer<float>::stream(s, indent + "  ", v.aTargetMaxDEPRECATED);
    s << indent << "laneWidthDEPRECATED: ";
    Printer<float>::stream(s, indent + "  ", v.laneWidthDEPRECATED);
    s << indent << "radarValid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.radarValid);
    s << indent << "gpsPlannerActive: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gpsPlannerActive);
    s << indent << "fcw: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.fcw);
    s << indent << "processingDelay: ";
    Printer<float>::stream(s, indent + "  ", v.processingDelay);
    s << indent << "longitudinalValidDEPRECATED: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.longitudinalValidDEPRECATED);
    s << indent << "aStart: ";
    Printer<float>::stream(s, indent + "  ", v.aStart);
    s << indent << "eventsDEPRECATED[]" << std::endl;
    for (size_t i = 0; i < v.eventsDEPRECATED.size(); ++i)
    {
      s << indent << "  eventsDEPRECATED[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::openpilot_bridge::CarEvent_<ContainerAllocator> >::stream(s, indent + "    ", v.eventsDEPRECATED[i]);
    }
    s << indent << "hasRightLaneDEPRECATED: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.hasRightLaneDEPRECATED);
    s << indent << "vStart: ";
    Printer<float>::stream(s, indent + "  ", v.vStart);
    s << indent << "aCruise: ";
    Printer<float>::stream(s, indent + "  ", v.aCruise);
    s << indent << "commIssue: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.commIssue);
    s << indent << "vTargetFuture: ";
    Printer<float>::stream(s, indent + "  ", v.vTargetFuture);
    s << indent << "gpsTrajectory: ";
    s << std::endl;
    Printer< ::openpilot_bridge::GpsTrajectory_<ContainerAllocator> >::stream(s, indent + "  ", v.gpsTrajectory);
    s << indent << "hasLeftLaneDEPRECATED: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.hasLeftLaneDEPRECATED);
    s << indent << "vCruise: ";
    Printer<float>::stream(s, indent + "  ", v.vCruise);
    s << indent << "aTargetMinDEPRECATED: ";
    Printer<float>::stream(s, indent + "  ", v.aTargetMinDEPRECATED);
    s << indent << "mapValid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mapValid);
    s << indent << "radarCanError: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.radarCanError);
    s << indent << "vMax: ";
    Printer<float>::stream(s, indent + "  ", v.vMax);
    s << indent << "dPolyDEPRECATED[]" << std::endl;
    for (size_t i = 0; i < v.dPolyDEPRECATED.size(); ++i)
    {
      s << indent << "  dPolyDEPRECATED[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.dPolyDEPRECATED[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPENPILOT_BRIDGE_MESSAGE_PLAN_H
