// Generated by gencpp from file openpilot_bridge/RadarData.msg
// DO NOT EDIT!


#ifndef OPENPILOT_BRIDGE_MESSAGE_RADARDATA_H
#define OPENPILOT_BRIDGE_MESSAGE_RADARDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <openpilot_bridge/RadarPoint.h>

namespace openpilot_bridge
{
template <class ContainerAllocator>
struct RadarData_
{
  typedef RadarData_<ContainerAllocator> Type;

  RadarData_()
    : header()
    , canMonoTimes()
    , errors()
    , points()  {
    }
  RadarData_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , canMonoTimes(_alloc)
    , errors(_alloc)
    , points(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<int64_t, typename ContainerAllocator::template rebind<int64_t>::other >  _canMonoTimes_type;
  _canMonoTimes_type canMonoTimes;

   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _errors_type;
  _errors_type errors;

   typedef std::vector< ::openpilot_bridge::RadarPoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::openpilot_bridge::RadarPoint_<ContainerAllocator> >::other >  _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::openpilot_bridge::RadarData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::openpilot_bridge::RadarData_<ContainerAllocator> const> ConstPtr;

}; // struct RadarData_

typedef ::openpilot_bridge::RadarData_<std::allocator<void> > RadarData;

typedef boost::shared_ptr< ::openpilot_bridge::RadarData > RadarDataPtr;
typedef boost::shared_ptr< ::openpilot_bridge::RadarData const> RadarDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::openpilot_bridge::RadarData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::openpilot_bridge::RadarData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::openpilot_bridge::RadarData_<ContainerAllocator1> & lhs, const ::openpilot_bridge::RadarData_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.canMonoTimes == rhs.canMonoTimes &&
    lhs.errors == rhs.errors &&
    lhs.points == rhs.points;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::openpilot_bridge::RadarData_<ContainerAllocator1> & lhs, const ::openpilot_bridge::RadarData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace openpilot_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::openpilot_bridge::RadarData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::openpilot_bridge::RadarData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpilot_bridge::RadarData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpilot_bridge::RadarData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpilot_bridge::RadarData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpilot_bridge::RadarData_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::openpilot_bridge::RadarData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "76b62543761f0d42ee75ec49ef018fe1";
  }

  static const char* value(const ::openpilot_bridge::RadarData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x76b62543761f0d42ULL;
  static const uint64_t static_value2 = 0xee75ec49ef018fe1ULL;
};

template<class ContainerAllocator>
struct DataType< ::openpilot_bridge::RadarData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "openpilot_bridge/RadarData";
  }

  static const char* value(const ::openpilot_bridge::RadarData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::openpilot_bridge::RadarData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"int64[] canMonoTimes\n"
"uint32[] errors # enum const: Error\n"
"RadarPoint[] points\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: openpilot_bridge/RadarPoint\n"
"Header header\n"
"\n"
"float32 yRel\n"
"int64 trackId\n"
"float32 aRel\n"
"float32 vRel\n"
"float32 dRel\n"
"float32 yvRel\n"
"bool measured\n"
;
  }

  static const char* value(const ::openpilot_bridge::RadarData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::openpilot_bridge::RadarData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.canMonoTimes);
      stream.next(m.errors);
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RadarData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::openpilot_bridge::RadarData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::openpilot_bridge::RadarData_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "canMonoTimes[]" << std::endl;
    for (size_t i = 0; i < v.canMonoTimes.size(); ++i)
    {
      s << indent << "  canMonoTimes[" << i << "]: ";
      Printer<int64_t>::stream(s, indent + "  ", v.canMonoTimes[i]);
    }
    s << indent << "errors[]" << std::endl;
    for (size_t i = 0; i < v.errors.size(); ++i)
    {
      s << indent << "  errors[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.errors[i]);
    }
    s << indent << "points[]" << std::endl;
    for (size_t i = 0; i < v.points.size(); ++i)
    {
      s << indent << "  points[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::openpilot_bridge::RadarPoint_<ContainerAllocator> >::stream(s, indent + "    ", v.points[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPENPILOT_BRIDGE_MESSAGE_RADARDATA_H
