// Generated by gencpp from file openpilot_bridge/Segment.msg
// DO NOT EDIT!


#ifndef OPENPILOT_BRIDGE_MESSAGE_SEGMENT_H
#define OPENPILOT_BRIDGE_MESSAGE_SEGMENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <openpilot_bridge/LatLng.h>
#include <openpilot_bridge/LatLng.h>
#include <openpilot_bridge/LatLng.h>

namespace openpilot_bridge
{
template <class ContainerAllocator>
struct Segment_
{
  typedef Segment_<ContainerAllocator> Type;

  Segment_()
    : header()
    , distance(0)
    , updateTime(0)
    , from()
    , instruction(0)
    , parts()
    , to()
    , crossTime(0)
    , exitNo(0)  {
    }
  Segment_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , distance(0)
    , updateTime(0)
    , from(_alloc)
    , instruction(0)
    , parts(_alloc)
    , to(_alloc)
    , crossTime(0)
    , exitNo(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _distance_type;
  _distance_type distance;

   typedef int32_t _updateTime_type;
  _updateTime_type updateTime;

   typedef  ::openpilot_bridge::LatLng_<ContainerAllocator>  _from_type;
  _from_type from;

   typedef uint32_t _instruction_type;
  _instruction_type instruction;

   typedef std::vector< ::openpilot_bridge::LatLng_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::openpilot_bridge::LatLng_<ContainerAllocator> >::other >  _parts_type;
  _parts_type parts;

   typedef  ::openpilot_bridge::LatLng_<ContainerAllocator>  _to_type;
  _to_type to;

   typedef int32_t _crossTime_type;
  _crossTime_type crossTime;

   typedef int32_t _exitNo_type;
  _exitNo_type exitNo;





  typedef boost::shared_ptr< ::openpilot_bridge::Segment_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::openpilot_bridge::Segment_<ContainerAllocator> const> ConstPtr;

}; // struct Segment_

typedef ::openpilot_bridge::Segment_<std::allocator<void> > Segment;

typedef boost::shared_ptr< ::openpilot_bridge::Segment > SegmentPtr;
typedef boost::shared_ptr< ::openpilot_bridge::Segment const> SegmentConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::openpilot_bridge::Segment_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::openpilot_bridge::Segment_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::openpilot_bridge::Segment_<ContainerAllocator1> & lhs, const ::openpilot_bridge::Segment_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.distance == rhs.distance &&
    lhs.updateTime == rhs.updateTime &&
    lhs.from == rhs.from &&
    lhs.instruction == rhs.instruction &&
    lhs.parts == rhs.parts &&
    lhs.to == rhs.to &&
    lhs.crossTime == rhs.crossTime &&
    lhs.exitNo == rhs.exitNo;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::openpilot_bridge::Segment_<ContainerAllocator1> & lhs, const ::openpilot_bridge::Segment_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace openpilot_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::openpilot_bridge::Segment_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::openpilot_bridge::Segment_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpilot_bridge::Segment_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpilot_bridge::Segment_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpilot_bridge::Segment_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpilot_bridge::Segment_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::openpilot_bridge::Segment_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dfbd5c3557c55dec73407d19d628c5ef";
  }

  static const char* value(const ::openpilot_bridge::Segment_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdfbd5c3557c55decULL;
  static const uint64_t static_value2 = 0x73407d19d628c5efULL;
};

template<class ContainerAllocator>
struct DataType< ::openpilot_bridge::Segment_<ContainerAllocator> >
{
  static const char* value()
  {
    return "openpilot_bridge/Segment";
  }

  static const char* value(const ::openpilot_bridge::Segment_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::openpilot_bridge::Segment_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"int32 distance\n"
"int32 updateTime\n"
"LatLng from\n"
"uint32 instruction # enum const: Instruction\n"
"LatLng[] parts\n"
"LatLng to\n"
"int32 crossTime\n"
"int32 exitNo\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: openpilot_bridge/LatLng\n"
"Header header\n"
"\n"
"float32 lat\n"
"float32 lng\n"
;
  }

  static const char* value(const ::openpilot_bridge::Segment_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::openpilot_bridge::Segment_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.distance);
      stream.next(m.updateTime);
      stream.next(m.from);
      stream.next(m.instruction);
      stream.next(m.parts);
      stream.next(m.to);
      stream.next(m.crossTime);
      stream.next(m.exitNo);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Segment_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::openpilot_bridge::Segment_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::openpilot_bridge::Segment_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "distance: ";
    Printer<int32_t>::stream(s, indent + "  ", v.distance);
    s << indent << "updateTime: ";
    Printer<int32_t>::stream(s, indent + "  ", v.updateTime);
    s << indent << "from: ";
    s << std::endl;
    Printer< ::openpilot_bridge::LatLng_<ContainerAllocator> >::stream(s, indent + "  ", v.from);
    s << indent << "instruction: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.instruction);
    s << indent << "parts[]" << std::endl;
    for (size_t i = 0; i < v.parts.size(); ++i)
    {
      s << indent << "  parts[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::openpilot_bridge::LatLng_<ContainerAllocator> >::stream(s, indent + "    ", v.parts[i]);
    }
    s << indent << "to: ";
    s << std::endl;
    Printer< ::openpilot_bridge::LatLng_<ContainerAllocator> >::stream(s, indent + "  ", v.to);
    s << indent << "crossTime: ";
    Printer<int32_t>::stream(s, indent + "  ", v.crossTime);
    s << indent << "exitNo: ";
    Printer<int32_t>::stream(s, indent + "  ", v.exitNo);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPENPILOT_BRIDGE_MESSAGE_SEGMENT_H
