// Generated by gencpp from file openpilot_bridge/Status.msg
// DO NOT EDIT!


#ifndef OPENPILOT_BRIDGE_MESSAGE_STATUS_H
#define OPENPILOT_BRIDGE_MESSAGE_STATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace openpilot_bridge
{
template <class ContainerAllocator>
struct Status_
{
  typedef Status_<ContainerAllocator> Type;

  Status_()
    {
    }
  Status_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }





// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(passive)
  #undef passive
#endif
#if defined(_WIN32) && defined(active)
  #undef active
#endif
#if defined(_WIN32) && defined(none)
  #undef none
#endif
#if defined(_WIN32) && defined(approaching)
  #undef approaching
#endif

  enum {
    passive = 1u,
    active = 3u,
    none = 0u,
    approaching = 2u,
  };


  typedef boost::shared_ptr< ::openpilot_bridge::Status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::openpilot_bridge::Status_<ContainerAllocator> const> ConstPtr;

}; // struct Status_

typedef ::openpilot_bridge::Status_<std::allocator<void> > Status;

typedef boost::shared_ptr< ::openpilot_bridge::Status > StatusPtr;
typedef boost::shared_ptr< ::openpilot_bridge::Status const> StatusConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::openpilot_bridge::Status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::openpilot_bridge::Status_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace openpilot_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::openpilot_bridge::Status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::openpilot_bridge::Status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpilot_bridge::Status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpilot_bridge::Status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpilot_bridge::Status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpilot_bridge::Status_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::openpilot_bridge::Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "10b5b01494ec6ca3607a495b014d618e";
  }

  static const char* value(const ::openpilot_bridge::Status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x10b5b01494ec6ca3ULL;
  static const uint64_t static_value2 = 0x607a495b014d618eULL;
};

template<class ContainerAllocator>
struct DataType< ::openpilot_bridge::Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "openpilot_bridge/Status";
  }

  static const char* value(const ::openpilot_bridge::Status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::openpilot_bridge::Status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 passive=1\n"
"uint32 active=3\n"
"uint32 none=0\n"
"uint32 approaching=2\n"
;
  }

  static const char* value(const ::openpilot_bridge::Status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::openpilot_bridge::Status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::openpilot_bridge::Status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::openpilot_bridge::Status_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // OPENPILOT_BRIDGE_MESSAGE_STATUS_H
