// Generated by gencpp from file openpilot_bridge/ThermalStatus.msg
// DO NOT EDIT!


#ifndef OPENPILOT_BRIDGE_MESSAGE_THERMALSTATUS_H
#define OPENPILOT_BRIDGE_MESSAGE_THERMALSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace openpilot_bridge
{
template <class ContainerAllocator>
struct ThermalStatus_
{
  typedef ThermalStatus_<ContainerAllocator> Type;

  ThermalStatus_()
    {
    }
  ThermalStatus_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }





// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(green)
  #undef green
#endif
#if defined(_WIN32) && defined(red)
  #undef red
#endif
#if defined(_WIN32) && defined(yellow)
  #undef yellow
#endif
#if defined(_WIN32) && defined(danger)
  #undef danger
#endif

  enum {
    green = 0u,
    red = 2u,
    yellow = 1u,
    danger = 3u,
  };


  typedef boost::shared_ptr< ::openpilot_bridge::ThermalStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::openpilot_bridge::ThermalStatus_<ContainerAllocator> const> ConstPtr;

}; // struct ThermalStatus_

typedef ::openpilot_bridge::ThermalStatus_<std::allocator<void> > ThermalStatus;

typedef boost::shared_ptr< ::openpilot_bridge::ThermalStatus > ThermalStatusPtr;
typedef boost::shared_ptr< ::openpilot_bridge::ThermalStatus const> ThermalStatusConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::openpilot_bridge::ThermalStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::openpilot_bridge::ThermalStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace openpilot_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::openpilot_bridge::ThermalStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::openpilot_bridge::ThermalStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpilot_bridge::ThermalStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpilot_bridge::ThermalStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpilot_bridge::ThermalStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpilot_bridge::ThermalStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::openpilot_bridge::ThermalStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8ca17fd4cb32043ad3a4b48c68d9d536";
  }

  static const char* value(const ::openpilot_bridge::ThermalStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8ca17fd4cb32043aULL;
  static const uint64_t static_value2 = 0xd3a4b48c68d9d536ULL;
};

template<class ContainerAllocator>
struct DataType< ::openpilot_bridge::ThermalStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "openpilot_bridge/ThermalStatus";
  }

  static const char* value(const ::openpilot_bridge::ThermalStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::openpilot_bridge::ThermalStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 green=0\n"
"uint32 red=2\n"
"uint32 yellow=1\n"
"uint32 danger=3\n"
;
  }

  static const char* value(const ::openpilot_bridge::ThermalStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::openpilot_bridge::ThermalStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ThermalStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::openpilot_bridge::ThermalStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::openpilot_bridge::ThermalStatus_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // OPENPILOT_BRIDGE_MESSAGE_THERMALSTATUS_H
