// Generated by gencpp from file openpilot_bridge/ThermalData.msg
// DO NOT EDIT!


#ifndef OPENPILOT_BRIDGE_MESSAGE_THERMALDATA_H
#define OPENPILOT_BRIDGE_MESSAGE_THERMALDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace openpilot_bridge
{
template <class ContainerAllocator>
struct ThermalData_
{
  typedef ThermalData_<ContainerAllocator> Type;

  ThermalData_()
    : header()
    , batteryVoltage(0)
    , chargingError(false)
    , cpuPerc(0)
    , chargingDisabled(false)
    , fanSpeed(0)
    , batteryCurrent(0)
    , started(false)
    , pa0(0)
    , batteryPercent(0)
    , gpu(0)
    , thermalStatus(0)
    , freeSpace(0.0)
    , usbOnline(false)
    , mem(0)
    , cpu2(0)
    , cpu3(0)
    , cpu0(0)
    , cpu1(0)
    , startedTs(0)
    , batteryStatus()
    , memUsedPercent(0)
    , bat(0)  {
    }
  ThermalData_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , batteryVoltage(0)
    , chargingError(false)
    , cpuPerc(0)
    , chargingDisabled(false)
    , fanSpeed(0)
    , batteryCurrent(0)
    , started(false)
    , pa0(0)
    , batteryPercent(0)
    , gpu(0)
    , thermalStatus(0)
    , freeSpace(0.0)
    , usbOnline(false)
    , mem(0)
    , cpu2(0)
    , cpu3(0)
    , cpu0(0)
    , cpu1(0)
    , startedTs(0)
    , batteryStatus(_alloc)
    , memUsedPercent(0)
    , bat(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _batteryVoltage_type;
  _batteryVoltage_type batteryVoltage;

   typedef uint8_t _chargingError_type;
  _chargingError_type chargingError;

   typedef int32_t _cpuPerc_type;
  _cpuPerc_type cpuPerc;

   typedef uint8_t _chargingDisabled_type;
  _chargingDisabled_type chargingDisabled;

   typedef int64_t _fanSpeed_type;
  _fanSpeed_type fanSpeed;

   typedef int32_t _batteryCurrent_type;
  _batteryCurrent_type batteryCurrent;

   typedef uint8_t _started_type;
  _started_type started;

   typedef int64_t _pa0_type;
  _pa0_type pa0;

   typedef int32_t _batteryPercent_type;
  _batteryPercent_type batteryPercent;

   typedef int64_t _gpu_type;
  _gpu_type gpu;

   typedef uint32_t _thermalStatus_type;
  _thermalStatus_type thermalStatus;

   typedef float _freeSpace_type;
  _freeSpace_type freeSpace;

   typedef uint8_t _usbOnline_type;
  _usbOnline_type usbOnline;

   typedef int64_t _mem_type;
  _mem_type mem;

   typedef int64_t _cpu2_type;
  _cpu2_type cpu2;

   typedef int64_t _cpu3_type;
  _cpu3_type cpu3;

   typedef int64_t _cpu0_type;
  _cpu0_type cpu0;

   typedef int64_t _cpu1_type;
  _cpu1_type cpu1;

   typedef int64_t _startedTs_type;
  _startedTs_type startedTs;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _batteryStatus_type;
  _batteryStatus_type batteryStatus;

   typedef int32_t _memUsedPercent_type;
  _memUsedPercent_type memUsedPercent;

   typedef int64_t _bat_type;
  _bat_type bat;





  typedef boost::shared_ptr< ::openpilot_bridge::ThermalData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::openpilot_bridge::ThermalData_<ContainerAllocator> const> ConstPtr;

}; // struct ThermalData_

typedef ::openpilot_bridge::ThermalData_<std::allocator<void> > ThermalData;

typedef boost::shared_ptr< ::openpilot_bridge::ThermalData > ThermalDataPtr;
typedef boost::shared_ptr< ::openpilot_bridge::ThermalData const> ThermalDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::openpilot_bridge::ThermalData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::openpilot_bridge::ThermalData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::openpilot_bridge::ThermalData_<ContainerAllocator1> & lhs, const ::openpilot_bridge::ThermalData_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.batteryVoltage == rhs.batteryVoltage &&
    lhs.chargingError == rhs.chargingError &&
    lhs.cpuPerc == rhs.cpuPerc &&
    lhs.chargingDisabled == rhs.chargingDisabled &&
    lhs.fanSpeed == rhs.fanSpeed &&
    lhs.batteryCurrent == rhs.batteryCurrent &&
    lhs.started == rhs.started &&
    lhs.pa0 == rhs.pa0 &&
    lhs.batteryPercent == rhs.batteryPercent &&
    lhs.gpu == rhs.gpu &&
    lhs.thermalStatus == rhs.thermalStatus &&
    lhs.freeSpace == rhs.freeSpace &&
    lhs.usbOnline == rhs.usbOnline &&
    lhs.mem == rhs.mem &&
    lhs.cpu2 == rhs.cpu2 &&
    lhs.cpu3 == rhs.cpu3 &&
    lhs.cpu0 == rhs.cpu0 &&
    lhs.cpu1 == rhs.cpu1 &&
    lhs.startedTs == rhs.startedTs &&
    lhs.batteryStatus == rhs.batteryStatus &&
    lhs.memUsedPercent == rhs.memUsedPercent &&
    lhs.bat == rhs.bat;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::openpilot_bridge::ThermalData_<ContainerAllocator1> & lhs, const ::openpilot_bridge::ThermalData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace openpilot_bridge

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::openpilot_bridge::ThermalData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::openpilot_bridge::ThermalData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpilot_bridge::ThermalData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openpilot_bridge::ThermalData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpilot_bridge::ThermalData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openpilot_bridge::ThermalData_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::openpilot_bridge::ThermalData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b82c596c149fdb826f5238d89c0ed390";
  }

  static const char* value(const ::openpilot_bridge::ThermalData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb82c596c149fdb82ULL;
  static const uint64_t static_value2 = 0x6f5238d89c0ed390ULL;
};

template<class ContainerAllocator>
struct DataType< ::openpilot_bridge::ThermalData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "openpilot_bridge/ThermalData";
  }

  static const char* value(const ::openpilot_bridge::ThermalData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::openpilot_bridge::ThermalData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"int32 batteryVoltage\n"
"bool chargingError\n"
"int32 cpuPerc\n"
"bool chargingDisabled\n"
"int64 fanSpeed\n"
"int32 batteryCurrent\n"
"bool started\n"
"int64 pa0\n"
"int32 batteryPercent\n"
"int64 gpu\n"
"uint32 thermalStatus # enum const: ThermalStatus\n"
"float32 freeSpace\n"
"bool usbOnline\n"
"int64 mem\n"
"int64 cpu2\n"
"int64 cpu3\n"
"int64 cpu0\n"
"int64 cpu1\n"
"int64 startedTs\n"
"string[] batteryStatus\n"
"int32 memUsedPercent\n"
"int64 bat\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::openpilot_bridge::ThermalData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::openpilot_bridge::ThermalData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.batteryVoltage);
      stream.next(m.chargingError);
      stream.next(m.cpuPerc);
      stream.next(m.chargingDisabled);
      stream.next(m.fanSpeed);
      stream.next(m.batteryCurrent);
      stream.next(m.started);
      stream.next(m.pa0);
      stream.next(m.batteryPercent);
      stream.next(m.gpu);
      stream.next(m.thermalStatus);
      stream.next(m.freeSpace);
      stream.next(m.usbOnline);
      stream.next(m.mem);
      stream.next(m.cpu2);
      stream.next(m.cpu3);
      stream.next(m.cpu0);
      stream.next(m.cpu1);
      stream.next(m.startedTs);
      stream.next(m.batteryStatus);
      stream.next(m.memUsedPercent);
      stream.next(m.bat);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ThermalData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::openpilot_bridge::ThermalData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::openpilot_bridge::ThermalData_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "batteryVoltage: ";
    Printer<int32_t>::stream(s, indent + "  ", v.batteryVoltage);
    s << indent << "chargingError: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.chargingError);
    s << indent << "cpuPerc: ";
    Printer<int32_t>::stream(s, indent + "  ", v.cpuPerc);
    s << indent << "chargingDisabled: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.chargingDisabled);
    s << indent << "fanSpeed: ";
    Printer<int64_t>::stream(s, indent + "  ", v.fanSpeed);
    s << indent << "batteryCurrent: ";
    Printer<int32_t>::stream(s, indent + "  ", v.batteryCurrent);
    s << indent << "started: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.started);
    s << indent << "pa0: ";
    Printer<int64_t>::stream(s, indent + "  ", v.pa0);
    s << indent << "batteryPercent: ";
    Printer<int32_t>::stream(s, indent + "  ", v.batteryPercent);
    s << indent << "gpu: ";
    Printer<int64_t>::stream(s, indent + "  ", v.gpu);
    s << indent << "thermalStatus: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.thermalStatus);
    s << indent << "freeSpace: ";
    Printer<float>::stream(s, indent + "  ", v.freeSpace);
    s << indent << "usbOnline: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.usbOnline);
    s << indent << "mem: ";
    Printer<int64_t>::stream(s, indent + "  ", v.mem);
    s << indent << "cpu2: ";
    Printer<int64_t>::stream(s, indent + "  ", v.cpu2);
    s << indent << "cpu3: ";
    Printer<int64_t>::stream(s, indent + "  ", v.cpu3);
    s << indent << "cpu0: ";
    Printer<int64_t>::stream(s, indent + "  ", v.cpu0);
    s << indent << "cpu1: ";
    Printer<int64_t>::stream(s, indent + "  ", v.cpu1);
    s << indent << "startedTs: ";
    Printer<int64_t>::stream(s, indent + "  ", v.startedTs);
    s << indent << "batteryStatus[]" << std::endl;
    for (size_t i = 0; i < v.batteryStatus.size(); ++i)
    {
      s << indent << "  batteryStatus[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.batteryStatus[i]);
    }
    s << indent << "memUsedPercent: ";
    Printer<int32_t>::stream(s, indent + "  ", v.memUsedPercent);
    s << indent << "bat: ";
    Printer<int64_t>::stream(s, indent + "  ", v.bat);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPENPILOT_BRIDGE_MESSAGE_THERMALDATA_H
