(cl:in-package itri_msgs-msg)
(cl:export '(DONTCARE-VAL
          DONTCARE
          GREEN-VAL
          GREEN
          LEFT-VAL
          LEFT
          RED-VAL
          RED
          RIGHT-VAL
          RIGHT
          STRAIGHT-VAL
          STRAIGHT
          YELLOW-VAL
          YELLOW
          FLASHYELLOW-VAL
          FLASHYELLOW
          FLASHRED-VAL
          FLASHRED
          BLOCKED-VAL
          BLOCKED
          TRAFFIC_LIGHT_MAP_POINTS-VAL
          TRAFFIC_LIGHT_MAP_POINTS
          ROI-VAL
          ROI
          SCORE-VAL
          SCORE
          ID-VAL
          ID
          DISTANCE-VAL
          DISTANCE
          REMAIN_SEC-VAL
          REMAIN_SEC
          LIGHTS-VAL
          LIGHTS
          LIGHTSROI-VAL
          LIGHTSROI
          SOURCE-VAL
          SOURCE
))