(cl:in-package itri_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          LANE_ID-VAL
          LANE_ID
          LANE_NUM-VAL
          LANE_NUM
          LANE_WIDTH-VAL
          LANE_WIDTH
          LINE_POS-VAL
          LINE_POS
          LINE_TYPE-VAL
          LINE_TYPE
          FRONT_LINE_DIS-VAL
          FRONT_LINE_DIS
          ON_ROUTE_HINT-VAL
          ON_ROUTE_HINT
          TRAFFIC_STOP_LINE-VAL
          TRAFFIC_STOP_LINE
          BUMPER-VAL
          BUMPER
          START_RIGHT_TURN-VAL
          START_RIGHT_TURN
          END_RIGHT_TURN-VAL
          END_RIGHT_TURN
          START_LEFT_TURN-VAL
          START_LEFT_TURN
          END_LEFT_TURN-VAL
          END_LEFT_TURN
          FRONT_MARKER_POINT-VAL
          FRONT_MARKER_POINT
          STATIONS-VAL
          STATIONS
          STATION_MSG-VAL
          STATION_MSG
          REMIND_DISTANCE-VAL
          REMIND_DISTANCE
          REMIND_TIME-VAL
          REMIND_TIME
          TURN_TYPE-VAL
          TURN_TYPE
          LENGTH_TO_TURN-VAL
          LENGTH_TO_TURN
))