(cl:in-package itri_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          IMAGE_TOPIC-VAL
          IMAGE_TOPIC
          FULL_IMAGE-VAL
          FULL_IMAGE
          ID-VAL
          ID
          SIGN-VAL
          SIGN
          X_ENLARGE_FACTOR-VAL
          X_ENLARGE_FACTOR
          Y_ENLARGE_FACTOR-VAL
          Y_ENLARGE_FACTOR
          X_OFFSET_FACTOR-VAL
          X_OFFSET_FACTOR
          Y_OFFSET_FACTOR-VAL
          Y_OFFSET_FACTOR
          DISTANCE-VAL
          DISTANCE
          ROI_IMAGE-VAL
          ROI_IMAGE
          TONE_MAP_ROI_IMAGE-VAL
          TONE_MAP_ROI_IMAGE
          TRAFFIC_SIGN_MAP_POINTS-VAL
          TRAFFIC_SIGN_MAP_POINTS
          TRAFFIC_SIGN_POINTS-VAL
          TRAFFIC_SIGN_POINTS
          TRAFFIC_SIGN_ROI-VAL
          TRAFFIC_SIGN_ROI
          ALL_TRAFFIC_SIGN_POINTS-VAL
          ALL_TRAFFIC_SIGN_POINTS
          ALL_TRAFFIC_SIGN_ROI-VAL
          ALL_TRAFFIC_SIGN_ROI
          SIGN_BOX-VAL
          SIGN_BOX
          HAS_SIGN-VAL
          HAS_SIGN
))