(cl:in-package itri_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          ID-VAL
          ID
          LABEL-VAL
          LABEL
          SCORE-VAL
          SCORE
          COLOR-VAL
          COLOR
          TRACKEDPERIOD-VAL
          TRACKEDPERIOD
          POSE-VAL
          POSE
          DIMENSIONS-VAL
          DIMENSIONS
          VARIANCE-VAL
          VARIANCE
          VELOCITY-VAL
          VELOCITY
          ABS_VELOCITY-VAL
          ABS_VELOCITY
          CONVEX_HULL-VAL
          CONVEX_HULL
          POSE_RELIABLE-VAL
          POSE_RELIABLE
          VELOCITY_RELIABLE-VAL
          VELOCITY_RELIABLE
          POINTCLOUD-VAL
          POINTCLOUD
          IMAGE_FRAME-VAL
          IMAGE_FRAME
          X-VAL
          X
          Y-VAL
          Y
          WIDTH-VAL
          WIDTH
          HEIGHT-VAL
          HEIGHT
          ANGLE-VAL
          ANGLE
          SPACE_FRAME-VAL
          SPACE_FRAME
          BEHAVIOR_STATE-VAL
          BEHAVIOR_STATE
          HISTORY_PATH-VAL
          HISTORY_PATH
          PREDICTED_POSES-VAL
          PREDICTED_POSES
          PREDICTED_VARIANCE-VAL
          PREDICTED_VARIANCE
          PREDICTED_PATHS-VAL
          PREDICTED_PATHS
          ACCELERATION-VAL
          ACCELERATION
          RADARFUSIONPOINTS-VAL
          RADARFUSIONPOINTS
          CAMERAOBJECTFRUSTUM-VAL
          CAMERAOBJECTFRUSTUM
          OVERLAPOBJECTSNUMBER-VAL
          OVERLAPOBJECTSNUMBER
          VISIBLESEGMENTS-VAL
          VISIBLESEGMENTS
          IMAGE2DCUBE-VAL
          IMAGE2DCUBE
          ISMOVING-VAL
          ISMOVING
))