(cl:in-package itri_msgs-msg)
(cl:export '(POSE-VAL
          POSE
          TWIST-VAL
          TWIST
          LANEID-VAL
          LANEID
          POINTID-VAL
          POINTID
          POINT-VAL
          POINT
          HEADING-VAL
          HEADING
          CURVATURE-VAL
          CURVATURE
          SPEED_LIMIT-VAL
          SPEED_LIMIT
          POINT_ID-VAL
          POINT_ID
          LANE_ID-VAL
          LANE_ID
          NROAD_ID-VAL
          NROAD_ID
          S-VAL
          S
          D-VAL
          D
          LEFT_SPACE-VAL
          LEFT_SPACE
          RIGHT_SPACE-VAL
          RIGHT_SPACE
          WIDTH-VAL
          WIDTH
          ROAD_TYPE-VAL
          ROAD_TYPE
))