(cl:in-package itri_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          VEHICLE_READY_TO_DRIVE-VAL
          VEHICLE_READY_TO_DRIVE
          SPEED-VAL
          SPEED
          STEERING_ANGLE-VAL
          STEERING_ANGLE
          STEERING_TORQUE-VAL
          STEERING_TORQUE
          MODE-VAL
          MODE
          GEAR-VAL
          GEAR
          GEAR_STATE-VAL
          GEAR_STATE
          EPS_STATE-VAL
          EPS_STATE
          THROTTLE_STATE-VAL
          THROTTLE_STATE
          BRAKE_STATE-VAL
          BRAKE_STATE
          GEAR_MODE-VAL
          GEAR_MODE
          ENGINE_SPEED-VAL
          ENGINE_SPEED
          GATEWAY_KEEP_ALIVE-VAL
          GATEWAY_KEEP_ALIVE
          AMT_GEAR_POS-VAL
          AMT_GEAR_POS
          BLINKER-VAL
          BLINKER
          AEB_SET-VAL
          AEB_SET
          BRAKE_CMD_FB-VAL
          BRAKE_CMD_FB
          ACCELE_CMD_FB-VAL
          ACCELE_CMD_FB
          BRAKE_PEDAL-VAL
          BRAKE_PEDAL
          ACCELE_PEDAL-VAL
          ACCELE_PEDAL
          STEER_MCU_ERROR-VAL
          STEER_MCU_ERROR
          CTRL_SWITCH_AEB-VAL
          CTRL_SWITCH_AEB
          CTRL_SWITCH_AMT-VAL
          CTRL_SWITCH_AMT
          CTRL_SWITCH_BLINKER-VAL
          CTRL_SWITCH_BLINKER
          CTRL_SWITCH_BRAKE-VAL
          CTRL_SWITCH_BRAKE
          CTRL_SWITCH_ENGINE-VAL
          CTRL_SWITCH_ENGINE
          CTRL_SWITCH_STEER-VAL
          CTRL_SWITCH_STEER
          CTRL_SWITCH_GEAR-VAL
          CTRL_SWITCH_GEAR
          BRAKE_REQ_CHECK-VAL
          BRAKE_REQ_CHECK
          ENGINE_REQ_CHECK-VAL
          ENGINE_REQ_CHECK
          STEER_REQ_CHECK-VAL
          STEER_REQ_CHECK
          GEAR_REQ_CHECK-VAL
          GEAR_REQ_CHECK
          EME_BUTTON-VAL
          EME_BUTTON
          BRAKE_ACTIVE_FLAG-VAL
          BRAKE_ACTIVE_FLAG
          DBW_COUNTER-VAL
          DBW_COUNTER
          REQUESTCHECK-VAL
          REQUESTCHECK
          AEBENABLE-VAL
          AEBENABLE
          SPEEDCTRLSTATUS-VAL
          SPEEDCTRLSTATUS
          DOORFR-VAL
          DOORFR
          DOORRR-VAL
          DOORRR
          BRAKEPRESSURE-VAL
          BRAKEPRESSURE
))