(cl:in-package itri_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          EXECUTION_TIME-VAL
          EXECUTION_TIME
          FITNESS_SCORE-VAL
          FITNESS_SCORE
          FITNESS_SCORE_VALID-VAL
          FITNESS_SCORE_VALID
          INVALID_POINTS_NUMBER-VAL
          INVALID_POINTS_NUMBER
          ITERATION-VAL
          ITERATION
          MAP_COVERAGE-VAL
          MAP_COVERAGE
          MATCHING_SCORE-VAL
          MATCHING_SCORE
          MATCHING_SCORE_VALID-VAL
          MATCHING_SCORE_VALID
          REGULATE_MATCHING_SCORE-VAL
          REGULATE_MATCHING_SCORE
          SCAN_VALID_RATIO-VAL
          SCAN_VALID_RATIO
          SOURCE_POINTS_NUMBER-VAL
          SOURCE_POINTS_NUMBER
          VALID_POINTS_NUMBER-VAL
          VALID_POINTS_NUMBER
))